// Command gen-icons writes the app icons for both platforms.
//
// The output is committed, like generated protobuf: the mark lives in
// mobile/internal/icon as geometry, this writes it out at every size each
// platform wants, and `go run ./mobile/tools/gen-icons` is how you regenerate
// after changing it. Nothing in a build depends on this running.
package main

import (
	"fmt"
	"image"
	"image/png"
	"log"
	"os"
	"path/filepath"

	"github.com/ezcdlabs/clarity/mobile/internal/icon"
)

const (
	androidRes = "mobile/apps/android/app/src/main/res"
	iosAssets  = "mobile/apps/ios/Clarity/Assets.xcassets"
)

// Android densities, as the multiple of mdpi each one is.
var densities = []struct {
	name  string
	scale int
}{
	{"mdpi", 1},
	{"hdpi", 2}, // 1.5×, corrected below
	{"xhdpi", 2},
	{"xxhdpi", 3},
	{"xxxhdpi", 4},
}

func main() {
	root, err := repoRoot()
	if err != nil {
		log.Fatal(err)
	}
	if err := os.Chdir(root); err != nil {
		log.Fatal(err)
	}

	for _, d := range androidSizes() {
		dir := filepath.Join(androidRes, "mipmap-"+d.name)
		// The legacy icons are the mark itself. Android 7, which minSdk still
		// supports, does not mask them — and it does not need to, because the
		// mark is already a disc.
		write(filepath.Join(dir, "ic_launcher.png"), icon.Logo(d.legacy, icon.OnNothing, 1))
		write(filepath.Join(dir, "ic_launcher_round.png"), icon.Logo(d.legacy, icon.OnNothing, 1))
		// The adaptive foreground is the checks alone, shrunk into the safe
		// zone. Its navy comes from the background layer, which Android paints
		// and moves independently.
		write(filepath.Join(dir, "ic_launcher_foreground.png"),
			icon.Logo(d.adaptive, icon.InkOnly, icon.ForegroundScale))
	}

	writeFile(filepath.Join(androidRes, "mipmap-anydpi-v26", "ic_launcher.xml"), adaptiveXML)
	writeFile(filepath.Join(androidRes, "mipmap-anydpi-v26", "ic_launcher_round.xml"), adaptiveXML)
	writeFile(filepath.Join(androidRes, "values", "ic_launcher_background.xml"), backgroundXML())

	// One 1024px icon and let Xcode downscale: the single-size app icon has
	// been the supported form since Xcode 14, and a folder of fourteen sizes is
	// fourteen things to regenerate wrongly. Filled rather than transparent —
	// iOS rejects an app icon with any transparency at all, and the navy
	// reaching the corners is the same navy the disc is made of.
	write(filepath.Join(iosAssets, "AppIcon.appiconset", "icon-1024.png"),
		icon.Logo(1024, icon.OnNavy, 1))
	writeFile(filepath.Join(iosAssets, "AppIcon.appiconset", "Contents.json"), appIconContents)
	writeFile(filepath.Join(iosAssets, "LaunchBackground.colorset", "Contents.json"), launchColorContents())
	writeFile(filepath.Join(iosAssets, "Contents.json"), catalogContents)
}

type androidSize struct {
	name     string
	legacy   int // a 48dp launcher icon
	adaptive int // a 108dp adaptive foreground
}

func androidSizes() []androidSize {
	out := make([]androidSize, 0, len(densities))
	for _, d := range densities {
		out = append(out, androidSize{name: d.name, legacy: 48 * d.scale, adaptive: 108 * d.scale})
	}
	// hdpi is 1.5×, the one density that is not a whole multiple.
	out[1].legacy, out[1].adaptive = 72, 162
	return out
}

func write(path string, img image.Image) {
	mkdirAll(path)
	f, err := os.Create(path)
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()
	if err := png.Encode(f, img); err != nil {
		log.Fatal(err)
	}
	fmt.Println(path)
}

func writeFile(path, content string) {
	mkdirAll(path)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Println(path)
}

func mkdirAll(path string) {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		log.Fatal(err)
	}
}

// repoRoot walks up from the working directory until it finds go.mod, so this
// runs the same from anywhere.
func repoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("no go.mod above %s", dir)
		}
		dir = parent
	}
}

const adaptiveXML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by mobile/tools/gen-icons. Do not edit. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@mipmap/ic_launcher_foreground" />
</adaptive-icon>
`

func backgroundXML() string {
	n := icon.Navy
	return fmt.Sprintf(`<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by mobile/tools/gen-icons. Do not edit. -->
<resources>
    <color name="ic_launcher_background">#%02X%02X%02X</color>
    <color name="brand_navy">#%02X%02X%02X</color>
</resources>
`, n.R, n.G, n.B, n.R, n.G, n.B)
}

func launchColorContents() string {
	n := icon.Navy
	return fmt.Sprintf(`{
  "colors" : [
    {
      "color" : {
        "color-space" : "srgb",
        "components" : {
          "alpha" : "1.000",
          "blue" : "0x%02X",
          "green" : "0x%02X",
          "red" : "0x%02X"
        }
      },
      "idiom" : "universal"
    }
  ],
  "info" : {
    "author" : "mobile/tools/gen-icons",
    "version" : 1
  }
}
`, n.B, n.G, n.R)
}

const appIconContents = `{
  "images" : [
    {
      "filename" : "icon-1024.png",
      "idiom" : "universal",
      "platform" : "ios",
      "size" : "1024x1024"
    }
  ],
  "info" : {
    "author" : "mobile/tools/gen-icons",
    "version" : 1
  }
}
`

const catalogContents = `{
  "info" : {
    "author" : "mobile/tools/gen-icons",
    "version" : 1
  }
}
`
