// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clarity/v1/view.proto

package dev.ezcd.clarity.proto;

/**
 * <pre>
 * Batch is one deploy attempt and the commits it carried.
 * </pre>
 *
 * Protobuf type {@code clarity.v1.Batch}
 */
public  final class Batch extends
    com.google.protobuf.GeneratedMessageLite<
        Batch, Batch.Builder> implements
    // @@protoc_insertion_point(message_implements:clarity.v1.Batch)
    BatchOrBuilder {
  private Batch() {
    label_ = "";
    deployedAgo_ = "";
    weekLabel_ = "";
    commits_ = emptyProtobufList();
  }
  public static final int STATUS_FIELD_NUMBER = 1;
  private int status_;
  /**
   * <code>.clarity.v1.Status status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.clarity.v1.Status status = 1;</code>
   * @return The status.
   */
  @java.lang.Override
  public dev.ezcd.clarity.proto.Status getStatus() {
    dev.ezcd.clarity.proto.Status result = dev.ezcd.clarity.proto.Status.forNumber(status_);
    return result == null ? dev.ezcd.clarity.proto.Status.UNRECOGNIZED : result;
  }
  /**
   * <code>.clarity.v1.Status status = 1;</code>
   * @param value The enum numeric value on the wire for status to set.
   */
  private void setStatusValue(int value) {
      status_ = value;
  }
  /**
   * <code>.clarity.v1.Status status = 1;</code>
   * @param value The status to set.
   */
  private void setStatus(dev.ezcd.clarity.proto.Status value) {
    status_ = value.getNumber();
    
  }
  /**
   * <code>.clarity.v1.Status status = 1;</code>
   */
  private void clearStatus() {
    
    status_ = 0;
  }

  public static final int LABEL_FIELD_NUMBER = 2;
  private java.lang.String label_;
  /**
   * <pre>
   * Label is the subheader the TUI writes above the batch: "deploying…",
   * "deployed", "deploy failed", or "live on production · deployed". The time
   * is not part of it — deployed_ago carries that separately so a client can
   * place it apart and keep it ticking.
   * </pre>
   *
   * <code>string label = 2;</code>
   * @return The label.
   */
  @java.lang.Override
  public java.lang.String getLabel() {
    return label_;
  }
  /**
   * <pre>
   * Label is the subheader the TUI writes above the batch: "deploying…",
   * "deployed", "deploy failed", or "live on production · deployed". The time
   * is not part of it — deployed_ago carries that separately so a client can
   * place it apart and keep it ticking.
   * </pre>
   *
   * <code>string label = 2;</code>
   * @return The bytes for label.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLabelBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(label_);
  }
  /**
   * <pre>
   * Label is the subheader the TUI writes above the batch: "deploying…",
   * "deployed", "deploy failed", or "live on production · deployed". The time
   * is not part of it — deployed_ago carries that separately so a client can
   * place it apart and keep it ticking.
   * </pre>
   *
   * <code>string label = 2;</code>
   * @param value The label to set.
   */
  private void setLabel(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    label_ = value;
  }
  /**
   * <pre>
   * Label is the subheader the TUI writes above the batch: "deploying…",
   * "deployed", "deploy failed", or "live on production · deployed". The time
   * is not part of it — deployed_ago carries that separately so a client can
   * place it apart and keep it ticking.
   * </pre>
   *
   * <code>string label = 2;</code>
   */
  private void clearLabel() {
    
    label_ = getDefaultInstance().getLabel();
  }
  /**
   * <pre>
   * Label is the subheader the TUI writes above the batch: "deploying…",
   * "deployed", "deploy failed", or "live on production · deployed". The time
   * is not part of it — deployed_ago carries that separately so a client can
   * place it apart and keep it ticking.
   * </pre>
   *
   * <code>string label = 2;</code>
   * @param value The bytes for label to set.
   */
  private void setLabelBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    label_ = value.toStringUtf8();
    
  }

  public static final int DEPLOYED_UNIX_SECONDS_FIELD_NUMBER = 3;
  private long deployedUnixSeconds_;
  /**
   * <code>int64 deployed_unix_seconds = 3;</code>
   * @return The deployedUnixSeconds.
   */
  @java.lang.Override
  public long getDeployedUnixSeconds() {
    return deployedUnixSeconds_;
  }
  /**
   * <code>int64 deployed_unix_seconds = 3;</code>
   * @param value The deployedUnixSeconds to set.
   */
  private void setDeployedUnixSeconds(long value) {
    
    deployedUnixSeconds_ = value;
  }
  /**
   * <code>int64 deployed_unix_seconds = 3;</code>
   */
  private void clearDeployedUnixSeconds() {
    
    deployedUnixSeconds_ = 0L;
  }

  public static final int DEPLOYED_AGO_FIELD_NUMBER = 4;
  private java.lang.String deployedAgo_;
  /**
   * <pre>
   * "4m 43s ago"
   * </pre>
   *
   * <code>string deployed_ago = 4;</code>
   * @return The deployedAgo.
   */
  @java.lang.Override
  public java.lang.String getDeployedAgo() {
    return deployedAgo_;
  }
  /**
   * <pre>
   * "4m 43s ago"
   * </pre>
   *
   * <code>string deployed_ago = 4;</code>
   * @return The bytes for deployedAgo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeployedAgoBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(deployedAgo_);
  }
  /**
   * <pre>
   * "4m 43s ago"
   * </pre>
   *
   * <code>string deployed_ago = 4;</code>
   * @param value The deployedAgo to set.
   */
  private void setDeployedAgo(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    deployedAgo_ = value;
  }
  /**
   * <pre>
   * "4m 43s ago"
   * </pre>
   *
   * <code>string deployed_ago = 4;</code>
   */
  private void clearDeployedAgo() {
    
    deployedAgo_ = getDefaultInstance().getDeployedAgo();
  }
  /**
   * <pre>
   * "4m 43s ago"
   * </pre>
   *
   * <code>string deployed_ago = 4;</code>
   * @param value The bytes for deployedAgo to set.
   */
  private void setDeployedAgoBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    deployedAgo_ = value.toStringUtf8();
    
  }

  public static final int LIVE_FIELD_NUMBER = 5;
  private boolean live_;
  /**
   * <pre>
   * Live marks the newest passing batch: what is running in production right
   * now, as opposed to settled history. Exactly one batch in a flow has it.
   * </pre>
   *
   * <code>bool live = 5;</code>
   * @return The live.
   */
  @java.lang.Override
  public boolean getLive() {
    return live_;
  }
  /**
   * <pre>
   * Live marks the newest passing batch: what is running in production right
   * now, as opposed to settled history. Exactly one batch in a flow has it.
   * </pre>
   *
   * <code>bool live = 5;</code>
   * @param value The live to set.
   */
  private void setLive(boolean value) {
    
    live_ = value;
  }
  /**
   * <pre>
   * Live marks the newest passing batch: what is running in production right
   * now, as opposed to settled history. Exactly one batch in a flow has it.
   * </pre>
   *
   * <code>bool live = 5;</code>
   */
  private void clearLive() {
    
    live_ = false;
  }

  public static final int WEEK_LABEL_FIELD_NUMBER = 7;
  private java.lang.String weekLabel_;
  /**
   * <pre>
   * Set on the first batch of a week that has not been named yet — the week
   * divider the terminal draws above it. The current week is never repeated
   * here: it is already on the section, in summary.
   * Weeks are marked once, and batches are ordered by commit rather than by
   * deploy time, so a redeploy of an older commit can put a week out of
   * sequence. Which batch carries the label is therefore a decision, not a
   * position a client can work out.
   * </pre>
   *
   * <code>string week_label = 7;</code>
   * @return The weekLabel.
   */
  @java.lang.Override
  public java.lang.String getWeekLabel() {
    return weekLabel_;
  }
  /**
   * <pre>
   * Set on the first batch of a week that has not been named yet — the week
   * divider the terminal draws above it. The current week is never repeated
   * here: it is already on the section, in summary.
   * Weeks are marked once, and batches are ordered by commit rather than by
   * deploy time, so a redeploy of an older commit can put a week out of
   * sequence. Which batch carries the label is therefore a decision, not a
   * position a client can work out.
   * </pre>
   *
   * <code>string week_label = 7;</code>
   * @return The bytes for weekLabel.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWeekLabelBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(weekLabel_);
  }
  /**
   * <pre>
   * Set on the first batch of a week that has not been named yet — the week
   * divider the terminal draws above it. The current week is never repeated
   * here: it is already on the section, in summary.
   * Weeks are marked once, and batches are ordered by commit rather than by
   * deploy time, so a redeploy of an older commit can put a week out of
   * sequence. Which batch carries the label is therefore a decision, not a
   * position a client can work out.
   * </pre>
   *
   * <code>string week_label = 7;</code>
   * @param value The weekLabel to set.
   */
  private void setWeekLabel(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    weekLabel_ = value;
  }
  /**
   * <pre>
   * Set on the first batch of a week that has not been named yet — the week
   * divider the terminal draws above it. The current week is never repeated
   * here: it is already on the section, in summary.
   * Weeks are marked once, and batches are ordered by commit rather than by
   * deploy time, so a redeploy of an older commit can put a week out of
   * sequence. Which batch carries the label is therefore a decision, not a
   * position a client can work out.
   * </pre>
   *
   * <code>string week_label = 7;</code>
   */
  private void clearWeekLabel() {
    
    weekLabel_ = getDefaultInstance().getWeekLabel();
  }
  /**
   * <pre>
   * Set on the first batch of a week that has not been named yet — the week
   * divider the terminal draws above it. The current week is never repeated
   * here: it is already on the section, in summary.
   * Weeks are marked once, and batches are ordered by commit rather than by
   * deploy time, so a redeploy of an older commit can put a week out of
   * sequence. Which batch carries the label is therefore a decision, not a
   * position a client can work out.
   * </pre>
   *
   * <code>string week_label = 7;</code>
   * @param value The bytes for weekLabel to set.
   */
  private void setWeekLabelBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    weekLabel_ = value.toStringUtf8();
    
  }

  public static final int COMMITS_FIELD_NUMBER = 6;
  private com.google.protobuf.Internal.ProtobufList<dev.ezcd.clarity.proto.Commit> commits_;
  /**
   * <code>repeated .clarity.v1.Commit commits = 6;</code>
   */
  @java.lang.Override
  public java.util.List<dev.ezcd.clarity.proto.Commit> getCommitsList() {
    return commits_;
  }
  /**
   * <code>repeated .clarity.v1.Commit commits = 6;</code>
   */
  public java.util.List<? extends dev.ezcd.clarity.proto.CommitOrBuilder> 
      getCommitsOrBuilderList() {
    return commits_;
  }
  /**
   * <code>repeated .clarity.v1.Commit commits = 6;</code>
   */
  @java.lang.Override
  public int getCommitsCount() {
    return commits_.size();
  }
  /**
   * <code>repeated .clarity.v1.Commit commits = 6;</code>
   */
  @java.lang.Override
  public dev.ezcd.clarity.proto.Commit getCommits(int index) {
    return commits_.get(index);
  }
  /**
   * <code>repeated .clarity.v1.Commit commits = 6;</code>
   */
  public dev.ezcd.clarity.proto.CommitOrBuilder getCommitsOrBuilder(
      int index) {
    return commits_.get(index);
  }
  private void ensureCommitsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<dev.ezcd.clarity.proto.Commit> tmp = commits_;
    if (!tmp.isModifiable()) {
      commits_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .clarity.v1.Commit commits = 6;</code>
   */
  private void setCommits(
      int index, dev.ezcd.clarity.proto.Commit value) {
    value.getClass();
  ensureCommitsIsMutable();
    commits_.set(index, value);
  }
  /**
   * <code>repeated .clarity.v1.Commit commits = 6;</code>
   */
  private void addCommits(dev.ezcd.clarity.proto.Commit value) {
    value.getClass();
  ensureCommitsIsMutable();
    commits_.add(value);
  }
  /**
   * <code>repeated .clarity.v1.Commit commits = 6;</code>
   */
  private void addCommits(
      int index, dev.ezcd.clarity.proto.Commit value) {
    value.getClass();
  ensureCommitsIsMutable();
    commits_.add(index, value);
  }
  /**
   * <code>repeated .clarity.v1.Commit commits = 6;</code>
   */
  private void addAllCommits(
      java.lang.Iterable<? extends dev.ezcd.clarity.proto.Commit> values) {
    ensureCommitsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, commits_);
  }
  /**
   * <code>repeated .clarity.v1.Commit commits = 6;</code>
   */
  private void clearCommits() {
    commits_ = emptyProtobufList();
  }
  /**
   * <code>repeated .clarity.v1.Commit commits = 6;</code>
   */
  private void removeCommits(int index) {
    ensureCommitsIsMutable();
    commits_.remove(index);
  }

  public static dev.ezcd.clarity.proto.Batch parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.Batch parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.Batch parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.Batch parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.Batch parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.Batch parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.Batch parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.Batch parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.Batch parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.Batch parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.Batch parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.Batch parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(dev.ezcd.clarity.proto.Batch prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Batch is one deploy attempt and the commits it carried.
   * </pre>
   *
   * Protobuf type {@code clarity.v1.Batch}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        dev.ezcd.clarity.proto.Batch, Builder> implements
      // @@protoc_insertion_point(builder_implements:clarity.v1.Batch)
      dev.ezcd.clarity.proto.BatchOrBuilder {
    // Construct using dev.ezcd.clarity.proto.Batch.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.clarity.v1.Status status = 1;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override
    public int getStatusValue() {
      return instance.getStatusValue();
    }
    /**
     * <code>.clarity.v1.Status status = 1;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      copyOnWrite();
      instance.setStatusValue(value);
      return this;
    }
    /**
     * <code>.clarity.v1.Status status = 1;</code>
     * @return The status.
     */
    @java.lang.Override
    public dev.ezcd.clarity.proto.Status getStatus() {
      return instance.getStatus();
    }
    /**
     * <code>.clarity.v1.Status status = 1;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(dev.ezcd.clarity.proto.Status value) {
      copyOnWrite();
      instance.setStatus(value);
      return this;
    }
    /**
     * <code>.clarity.v1.Status status = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      copyOnWrite();
      instance.clearStatus();
      return this;
    }

    /**
     * <pre>
     * Label is the subheader the TUI writes above the batch: "deploying…",
     * "deployed", "deploy failed", or "live on production · deployed". The time
     * is not part of it — deployed_ago carries that separately so a client can
     * place it apart and keep it ticking.
     * </pre>
     *
     * <code>string label = 2;</code>
     * @return The label.
     */
    @java.lang.Override
    public java.lang.String getLabel() {
      return instance.getLabel();
    }
    /**
     * <pre>
     * Label is the subheader the TUI writes above the batch: "deploying…",
     * "deployed", "deploy failed", or "live on production · deployed". The time
     * is not part of it — deployed_ago carries that separately so a client can
     * place it apart and keep it ticking.
     * </pre>
     *
     * <code>string label = 2;</code>
     * @return The bytes for label.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLabelBytes() {
      return instance.getLabelBytes();
    }
    /**
     * <pre>
     * Label is the subheader the TUI writes above the batch: "deploying…",
     * "deployed", "deploy failed", or "live on production · deployed". The time
     * is not part of it — deployed_ago carries that separately so a client can
     * place it apart and keep it ticking.
     * </pre>
     *
     * <code>string label = 2;</code>
     * @param value The label to set.
     * @return This builder for chaining.
     */
    public Builder setLabel(
        java.lang.String value) {
      copyOnWrite();
      instance.setLabel(value);
      return this;
    }
    /**
     * <pre>
     * Label is the subheader the TUI writes above the batch: "deploying…",
     * "deployed", "deploy failed", or "live on production · deployed". The time
     * is not part of it — deployed_ago carries that separately so a client can
     * place it apart and keep it ticking.
     * </pre>
     *
     * <code>string label = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLabel() {
      copyOnWrite();
      instance.clearLabel();
      return this;
    }
    /**
     * <pre>
     * Label is the subheader the TUI writes above the batch: "deploying…",
     * "deployed", "deploy failed", or "live on production · deployed". The time
     * is not part of it — deployed_ago carries that separately so a client can
     * place it apart and keep it ticking.
     * </pre>
     *
     * <code>string label = 2;</code>
     * @param value The bytes for label to set.
     * @return This builder for chaining.
     */
    public Builder setLabelBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setLabelBytes(value);
      return this;
    }

    /**
     * <code>int64 deployed_unix_seconds = 3;</code>
     * @return The deployedUnixSeconds.
     */
    @java.lang.Override
    public long getDeployedUnixSeconds() {
      return instance.getDeployedUnixSeconds();
    }
    /**
     * <code>int64 deployed_unix_seconds = 3;</code>
     * @param value The deployedUnixSeconds to set.
     * @return This builder for chaining.
     */
    public Builder setDeployedUnixSeconds(long value) {
      copyOnWrite();
      instance.setDeployedUnixSeconds(value);
      return this;
    }
    /**
     * <code>int64 deployed_unix_seconds = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeployedUnixSeconds() {
      copyOnWrite();
      instance.clearDeployedUnixSeconds();
      return this;
    }

    /**
     * <pre>
     * "4m 43s ago"
     * </pre>
     *
     * <code>string deployed_ago = 4;</code>
     * @return The deployedAgo.
     */
    @java.lang.Override
    public java.lang.String getDeployedAgo() {
      return instance.getDeployedAgo();
    }
    /**
     * <pre>
     * "4m 43s ago"
     * </pre>
     *
     * <code>string deployed_ago = 4;</code>
     * @return The bytes for deployedAgo.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeployedAgoBytes() {
      return instance.getDeployedAgoBytes();
    }
    /**
     * <pre>
     * "4m 43s ago"
     * </pre>
     *
     * <code>string deployed_ago = 4;</code>
     * @param value The deployedAgo to set.
     * @return This builder for chaining.
     */
    public Builder setDeployedAgo(
        java.lang.String value) {
      copyOnWrite();
      instance.setDeployedAgo(value);
      return this;
    }
    /**
     * <pre>
     * "4m 43s ago"
     * </pre>
     *
     * <code>string deployed_ago = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeployedAgo() {
      copyOnWrite();
      instance.clearDeployedAgo();
      return this;
    }
    /**
     * <pre>
     * "4m 43s ago"
     * </pre>
     *
     * <code>string deployed_ago = 4;</code>
     * @param value The bytes for deployedAgo to set.
     * @return This builder for chaining.
     */
    public Builder setDeployedAgoBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDeployedAgoBytes(value);
      return this;
    }

    /**
     * <pre>
     * Live marks the newest passing batch: what is running in production right
     * now, as opposed to settled history. Exactly one batch in a flow has it.
     * </pre>
     *
     * <code>bool live = 5;</code>
     * @return The live.
     */
    @java.lang.Override
    public boolean getLive() {
      return instance.getLive();
    }
    /**
     * <pre>
     * Live marks the newest passing batch: what is running in production right
     * now, as opposed to settled history. Exactly one batch in a flow has it.
     * </pre>
     *
     * <code>bool live = 5;</code>
     * @param value The live to set.
     * @return This builder for chaining.
     */
    public Builder setLive(boolean value) {
      copyOnWrite();
      instance.setLive(value);
      return this;
    }
    /**
     * <pre>
     * Live marks the newest passing batch: what is running in production right
     * now, as opposed to settled history. Exactly one batch in a flow has it.
     * </pre>
     *
     * <code>bool live = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearLive() {
      copyOnWrite();
      instance.clearLive();
      return this;
    }

    /**
     * <pre>
     * Set on the first batch of a week that has not been named yet — the week
     * divider the terminal draws above it. The current week is never repeated
     * here: it is already on the section, in summary.
     * Weeks are marked once, and batches are ordered by commit rather than by
     * deploy time, so a redeploy of an older commit can put a week out of
     * sequence. Which batch carries the label is therefore a decision, not a
     * position a client can work out.
     * </pre>
     *
     * <code>string week_label = 7;</code>
     * @return The weekLabel.
     */
    @java.lang.Override
    public java.lang.String getWeekLabel() {
      return instance.getWeekLabel();
    }
    /**
     * <pre>
     * Set on the first batch of a week that has not been named yet — the week
     * divider the terminal draws above it. The current week is never repeated
     * here: it is already on the section, in summary.
     * Weeks are marked once, and batches are ordered by commit rather than by
     * deploy time, so a redeploy of an older commit can put a week out of
     * sequence. Which batch carries the label is therefore a decision, not a
     * position a client can work out.
     * </pre>
     *
     * <code>string week_label = 7;</code>
     * @return The bytes for weekLabel.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getWeekLabelBytes() {
      return instance.getWeekLabelBytes();
    }
    /**
     * <pre>
     * Set on the first batch of a week that has not been named yet — the week
     * divider the terminal draws above it. The current week is never repeated
     * here: it is already on the section, in summary.
     * Weeks are marked once, and batches are ordered by commit rather than by
     * deploy time, so a redeploy of an older commit can put a week out of
     * sequence. Which batch carries the label is therefore a decision, not a
     * position a client can work out.
     * </pre>
     *
     * <code>string week_label = 7;</code>
     * @param value The weekLabel to set.
     * @return This builder for chaining.
     */
    public Builder setWeekLabel(
        java.lang.String value) {
      copyOnWrite();
      instance.setWeekLabel(value);
      return this;
    }
    /**
     * <pre>
     * Set on the first batch of a week that has not been named yet — the week
     * divider the terminal draws above it. The current week is never repeated
     * here: it is already on the section, in summary.
     * Weeks are marked once, and batches are ordered by commit rather than by
     * deploy time, so a redeploy of an older commit can put a week out of
     * sequence. Which batch carries the label is therefore a decision, not a
     * position a client can work out.
     * </pre>
     *
     * <code>string week_label = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearWeekLabel() {
      copyOnWrite();
      instance.clearWeekLabel();
      return this;
    }
    /**
     * <pre>
     * Set on the first batch of a week that has not been named yet — the week
     * divider the terminal draws above it. The current week is never repeated
     * here: it is already on the section, in summary.
     * Weeks are marked once, and batches are ordered by commit rather than by
     * deploy time, so a redeploy of an older commit can put a week out of
     * sequence. Which batch carries the label is therefore a decision, not a
     * position a client can work out.
     * </pre>
     *
     * <code>string week_label = 7;</code>
     * @param value The bytes for weekLabel to set.
     * @return This builder for chaining.
     */
    public Builder setWeekLabelBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setWeekLabelBytes(value);
      return this;
    }

    /**
     * <code>repeated .clarity.v1.Commit commits = 6;</code>
     */
    @java.lang.Override
    public java.util.List<dev.ezcd.clarity.proto.Commit> getCommitsList() {
      return java.util.Collections.unmodifiableList(
          instance.getCommitsList());
    }
    /**
     * <code>repeated .clarity.v1.Commit commits = 6;</code>
     */
    @java.lang.Override
    public int getCommitsCount() {
      return instance.getCommitsCount();
    }/**
     * <code>repeated .clarity.v1.Commit commits = 6;</code>
     */
    @java.lang.Override
    public dev.ezcd.clarity.proto.Commit getCommits(int index) {
      return instance.getCommits(index);
    }
    /**
     * <code>repeated .clarity.v1.Commit commits = 6;</code>
     */
    public Builder setCommits(
        int index, dev.ezcd.clarity.proto.Commit value) {
      copyOnWrite();
      instance.setCommits(index, value);
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Commit commits = 6;</code>
     */
    public Builder setCommits(
        int index, dev.ezcd.clarity.proto.Commit.Builder builderForValue) {
      copyOnWrite();
      instance.setCommits(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Commit commits = 6;</code>
     */
    public Builder addCommits(dev.ezcd.clarity.proto.Commit value) {
      copyOnWrite();
      instance.addCommits(value);
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Commit commits = 6;</code>
     */
    public Builder addCommits(
        int index, dev.ezcd.clarity.proto.Commit value) {
      copyOnWrite();
      instance.addCommits(index, value);
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Commit commits = 6;</code>
     */
    public Builder addCommits(
        dev.ezcd.clarity.proto.Commit.Builder builderForValue) {
      copyOnWrite();
      instance.addCommits(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Commit commits = 6;</code>
     */
    public Builder addCommits(
        int index, dev.ezcd.clarity.proto.Commit.Builder builderForValue) {
      copyOnWrite();
      instance.addCommits(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Commit commits = 6;</code>
     */
    public Builder addAllCommits(
        java.lang.Iterable<? extends dev.ezcd.clarity.proto.Commit> values) {
      copyOnWrite();
      instance.addAllCommits(values);
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Commit commits = 6;</code>
     */
    public Builder clearCommits() {
      copyOnWrite();
      instance.clearCommits();
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Commit commits = 6;</code>
     */
    public Builder removeCommits(int index) {
      copyOnWrite();
      instance.removeCommits(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:clarity.v1.Batch)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new dev.ezcd.clarity.proto.Batch();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "status_",
            "label_",
            "deployedUnixSeconds_",
            "deployedAgo_",
            "live_",
            "commits_",
            dev.ezcd.clarity.proto.Commit.class,
            "weekLabel_",
          };
          java.lang.String info =
              "\u0000\u0007\u0000\u0000\u0001\u0007\u0007\u0000\u0001\u0000\u0001\f\u0002\u0208" +
              "\u0003\u0002\u0004\u0208\u0005\u0007\u0006\u001b\u0007\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<dev.ezcd.clarity.proto.Batch> parser = PARSER;
        if (parser == null) {
          synchronized (dev.ezcd.clarity.proto.Batch.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<dev.ezcd.clarity.proto.Batch>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:clarity.v1.Batch)
  private static final dev.ezcd.clarity.proto.Batch DEFAULT_INSTANCE;
  static {
    Batch defaultInstance = new Batch();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Batch.class, defaultInstance);
  }

  public static dev.ezcd.clarity.proto.Batch getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Batch> PARSER;

  public static com.google.protobuf.Parser<Batch> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

