// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clarity/v1/view.proto

package dev.ezcd.clarity.proto;

public interface BatchOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clarity.v1.Batch)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.clarity.v1.Status status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.clarity.v1.Status status = 1;</code>
   * @return The status.
   */
  dev.ezcd.clarity.proto.Status getStatus();

  /**
   * <pre>
   * Label is the subheader the TUI writes above the batch: "deploying…",
   * "deployed", "deploy failed", or "live on production · deployed". The time
   * is not part of it — deployed_ago carries that separately so a client can
   * place it apart and keep it ticking.
   * </pre>
   *
   * <code>string label = 2;</code>
   * @return The label.
   */
  java.lang.String getLabel();
  /**
   * <pre>
   * Label is the subheader the TUI writes above the batch: "deploying…",
   * "deployed", "deploy failed", or "live on production · deployed". The time
   * is not part of it — deployed_ago carries that separately so a client can
   * place it apart and keep it ticking.
   * </pre>
   *
   * <code>string label = 2;</code>
   * @return The bytes for label.
   */
  com.google.protobuf.ByteString
      getLabelBytes();

  /**
   * <code>int64 deployed_unix_seconds = 3;</code>
   * @return The deployedUnixSeconds.
   */
  long getDeployedUnixSeconds();

  /**
   * <pre>
   * "4m 43s ago"
   * </pre>
   *
   * <code>string deployed_ago = 4;</code>
   * @return The deployedAgo.
   */
  java.lang.String getDeployedAgo();
  /**
   * <pre>
   * "4m 43s ago"
   * </pre>
   *
   * <code>string deployed_ago = 4;</code>
   * @return The bytes for deployedAgo.
   */
  com.google.protobuf.ByteString
      getDeployedAgoBytes();

  /**
   * <pre>
   * Live marks the newest passing batch: what is running in production right
   * now, as opposed to settled history. Exactly one batch in a flow has it.
   * </pre>
   *
   * <code>bool live = 5;</code>
   * @return The live.
   */
  boolean getLive();

  /**
   * <pre>
   * Set on the first batch of a week that has not been named yet — the week
   * divider the terminal draws above it. The current week is never repeated
   * here: it is already on the section, in summary.
   * Weeks are marked once, and batches are ordered by commit rather than by
   * deploy time, so a redeploy of an older commit can put a week out of
   * sequence. Which batch carries the label is therefore a decision, not a
   * position a client can work out.
   * </pre>
   *
   * <code>string week_label = 7;</code>
   * @return The weekLabel.
   */
  java.lang.String getWeekLabel();
  /**
   * <pre>
   * Set on the first batch of a week that has not been named yet — the week
   * divider the terminal draws above it. The current week is never repeated
   * here: it is already on the section, in summary.
   * Weeks are marked once, and batches are ordered by commit rather than by
   * deploy time, so a redeploy of an older commit can put a week out of
   * sequence. Which batch carries the label is therefore a decision, not a
   * position a client can work out.
   * </pre>
   *
   * <code>string week_label = 7;</code>
   * @return The bytes for weekLabel.
   */
  com.google.protobuf.ByteString
      getWeekLabelBytes();

  /**
   * <code>repeated .clarity.v1.Commit commits = 6;</code>
   */
  java.util.List<dev.ezcd.clarity.proto.Commit> 
      getCommitsList();
  /**
   * <code>repeated .clarity.v1.Commit commits = 6;</code>
   */
  dev.ezcd.clarity.proto.Commit getCommits(int index);
  /**
   * <code>repeated .clarity.v1.Commit commits = 6;</code>
   */
  int getCommitsCount();
}
