// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clarity/v1/view.proto

package dev.ezcd.clarity.proto;

/**
 * <pre>
 * Change is one pipeline crossing between green and red.
 * </pre>
 *
 * Protobuf type {@code clarity.v1.Change}
 */
public  final class Change extends
    com.google.protobuf.GeneratedMessageLite<
        Change, Change.Builder> implements
    // @@protoc_insertion_point(message_implements:clarity.v1.Change)
    ChangeOrBuilder {
  private Change() {
    repoId_ = "";
    repoName_ = "";
    stage_ = "";
  }
  public static final int REPO_ID_FIELD_NUMBER = 1;
  private java.lang.String repoId_;
  /**
   * <code>string repo_id = 1;</code>
   * @return The repoId.
   */
  @java.lang.Override
  public java.lang.String getRepoId() {
    return repoId_;
  }
  /**
   * <code>string repo_id = 1;</code>
   * @return The bytes for repoId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRepoIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(repoId_);
  }
  /**
   * <code>string repo_id = 1;</code>
   * @param value The repoId to set.
   */
  private void setRepoId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    repoId_ = value;
  }
  /**
   * <code>string repo_id = 1;</code>
   */
  private void clearRepoId() {
    
    repoId_ = getDefaultInstance().getRepoId();
  }
  /**
   * <code>string repo_id = 1;</code>
   * @param value The bytes for repoId to set.
   */
  private void setRepoIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    repoId_ = value.toStringUtf8();
    
  }

  public static final int REPO_NAME_FIELD_NUMBER = 2;
  private java.lang.String repoName_;
  /**
   * <pre>
   * What to call the repository: its rename if it has one, otherwise the name
   * derived from the URL — the same label its row in the switcher carries.
   * </pre>
   *
   * <code>string repo_name = 2;</code>
   * @return The repoName.
   */
  @java.lang.Override
  public java.lang.String getRepoName() {
    return repoName_;
  }
  /**
   * <pre>
   * What to call the repository: its rename if it has one, otherwise the name
   * derived from the URL — the same label its row in the switcher carries.
   * </pre>
   *
   * <code>string repo_name = 2;</code>
   * @return The bytes for repoName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRepoNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(repoName_);
  }
  /**
   * <pre>
   * What to call the repository: its rename if it has one, otherwise the name
   * derived from the URL — the same label its row in the switcher carries.
   * </pre>
   *
   * <code>string repo_name = 2;</code>
   * @param value The repoName to set.
   */
  private void setRepoName(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    repoName_ = value;
  }
  /**
   * <pre>
   * What to call the repository: its rename if it has one, otherwise the name
   * derived from the URL — the same label its row in the switcher carries.
   * </pre>
   *
   * <code>string repo_name = 2;</code>
   */
  private void clearRepoName() {
    
    repoName_ = getDefaultInstance().getRepoName();
  }
  /**
   * <pre>
   * What to call the repository: its rename if it has one, otherwise the name
   * derived from the URL — the same label its row in the switcher carries.
   * </pre>
   *
   * <code>string repo_name = 2;</code>
   * @param value The bytes for repoName to set.
   */
  private void setRepoNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    repoName_ = value.toStringUtf8();
    
  }

  public static final int STAGE_FIELD_NUMBER = 3;
  private java.lang.String stage_;
  /**
   * <pre>
   * What moved, in the words a notification uses: "CI", or "deploy to ios".
   * Here rather than in each app so two clients cannot disagree about what to
   * call a deploy target.
   * </pre>
   *
   * <code>string stage = 3;</code>
   * @return The stage.
   */
  @java.lang.Override
  public java.lang.String getStage() {
    return stage_;
  }
  /**
   * <pre>
   * What moved, in the words a notification uses: "CI", or "deploy to ios".
   * Here rather than in each app so two clients cannot disagree about what to
   * call a deploy target.
   * </pre>
   *
   * <code>string stage = 3;</code>
   * @return The bytes for stage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStageBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(stage_);
  }
  /**
   * <pre>
   * What moved, in the words a notification uses: "CI", or "deploy to ios".
   * Here rather than in each app so two clients cannot disagree about what to
   * call a deploy target.
   * </pre>
   *
   * <code>string stage = 3;</code>
   * @param value The stage to set.
   */
  private void setStage(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    stage_ = value;
  }
  /**
   * <pre>
   * What moved, in the words a notification uses: "CI", or "deploy to ios".
   * Here rather than in each app so two clients cannot disagree about what to
   * call a deploy target.
   * </pre>
   *
   * <code>string stage = 3;</code>
   */
  private void clearStage() {
    
    stage_ = getDefaultInstance().getStage();
  }
  /**
   * <pre>
   * What moved, in the words a notification uses: "CI", or "deploy to ios".
   * Here rather than in each app so two clients cannot disagree about what to
   * call a deploy target.
   * </pre>
   *
   * <code>string stage = 3;</code>
   * @param value The bytes for stage to set.
   */
  private void setStageBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    stage_ = value.toStringUtf8();
    
  }

  public static final int BROKE_FIELD_NUMBER = 4;
  private boolean broke_;
  /**
   * <pre>
   * Which direction. Both are worth saying and they are not worth saying the
   * same way — one interrupts, the other can wait for you to look.
   * </pre>
   *
   * <code>bool broke = 4;</code>
   * @return The broke.
   */
  @java.lang.Override
  public boolean getBroke() {
    return broke_;
  }
  /**
   * <pre>
   * Which direction. Both are worth saying and they are not worth saying the
   * same way — one interrupts, the other can wait for you to look.
   * </pre>
   *
   * <code>bool broke = 4;</code>
   * @param value The broke to set.
   */
  private void setBroke(boolean value) {
    
    broke_ = value;
  }
  /**
   * <pre>
   * Which direction. Both are worth saying and they are not worth saying the
   * same way — one interrupts, the other can wait for you to look.
   * </pre>
   *
   * <code>bool broke = 4;</code>
   */
  private void clearBroke() {
    
    broke_ = false;
  }

  public static final int FROM_FIELD_NUMBER = 5;
  private int from_;
  /**
   * <code>.clarity.v1.Status from = 5;</code>
   * @return The enum numeric value on the wire for from.
   */
  @java.lang.Override
  public int getFromValue() {
    return from_;
  }
  /**
   * <code>.clarity.v1.Status from = 5;</code>
   * @return The from.
   */
  @java.lang.Override
  public dev.ezcd.clarity.proto.Status getFrom() {
    dev.ezcd.clarity.proto.Status result = dev.ezcd.clarity.proto.Status.forNumber(from_);
    return result == null ? dev.ezcd.clarity.proto.Status.UNRECOGNIZED : result;
  }
  /**
   * <code>.clarity.v1.Status from = 5;</code>
   * @param value The enum numeric value on the wire for from to set.
   */
  private void setFromValue(int value) {
      from_ = value;
  }
  /**
   * <code>.clarity.v1.Status from = 5;</code>
   * @param value The from to set.
   */
  private void setFrom(dev.ezcd.clarity.proto.Status value) {
    from_ = value.getNumber();
    
  }
  /**
   * <code>.clarity.v1.Status from = 5;</code>
   */
  private void clearFrom() {
    
    from_ = 0;
  }

  public static final int TO_FIELD_NUMBER = 6;
  private int to_;
  /**
   * <code>.clarity.v1.Status to = 6;</code>
   * @return The enum numeric value on the wire for to.
   */
  @java.lang.Override
  public int getToValue() {
    return to_;
  }
  /**
   * <code>.clarity.v1.Status to = 6;</code>
   * @return The to.
   */
  @java.lang.Override
  public dev.ezcd.clarity.proto.Status getTo() {
    dev.ezcd.clarity.proto.Status result = dev.ezcd.clarity.proto.Status.forNumber(to_);
    return result == null ? dev.ezcd.clarity.proto.Status.UNRECOGNIZED : result;
  }
  /**
   * <code>.clarity.v1.Status to = 6;</code>
   * @param value The enum numeric value on the wire for to to set.
   */
  private void setToValue(int value) {
      to_ = value;
  }
  /**
   * <code>.clarity.v1.Status to = 6;</code>
   * @param value The to to set.
   */
  private void setTo(dev.ezcd.clarity.proto.Status value) {
    to_ = value.getNumber();
    
  }
  /**
   * <code>.clarity.v1.Status to = 6;</code>
   */
  private void clearTo() {
    
    to_ = 0;
  }

  public static dev.ezcd.clarity.proto.Change parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.Change parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.Change parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.Change parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.Change parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.Change parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.Change parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.Change parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.Change parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.Change parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.Change parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.Change parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(dev.ezcd.clarity.proto.Change prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Change is one pipeline crossing between green and red.
   * </pre>
   *
   * Protobuf type {@code clarity.v1.Change}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        dev.ezcd.clarity.proto.Change, Builder> implements
      // @@protoc_insertion_point(builder_implements:clarity.v1.Change)
      dev.ezcd.clarity.proto.ChangeOrBuilder {
    // Construct using dev.ezcd.clarity.proto.Change.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string repo_id = 1;</code>
     * @return The repoId.
     */
    @java.lang.Override
    public java.lang.String getRepoId() {
      return instance.getRepoId();
    }
    /**
     * <code>string repo_id = 1;</code>
     * @return The bytes for repoId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRepoIdBytes() {
      return instance.getRepoIdBytes();
    }
    /**
     * <code>string repo_id = 1;</code>
     * @param value The repoId to set.
     * @return This builder for chaining.
     */
    public Builder setRepoId(
        java.lang.String value) {
      copyOnWrite();
      instance.setRepoId(value);
      return this;
    }
    /**
     * <code>string repo_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRepoId() {
      copyOnWrite();
      instance.clearRepoId();
      return this;
    }
    /**
     * <code>string repo_id = 1;</code>
     * @param value The bytes for repoId to set.
     * @return This builder for chaining.
     */
    public Builder setRepoIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRepoIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * What to call the repository: its rename if it has one, otherwise the name
     * derived from the URL — the same label its row in the switcher carries.
     * </pre>
     *
     * <code>string repo_name = 2;</code>
     * @return The repoName.
     */
    @java.lang.Override
    public java.lang.String getRepoName() {
      return instance.getRepoName();
    }
    /**
     * <pre>
     * What to call the repository: its rename if it has one, otherwise the name
     * derived from the URL — the same label its row in the switcher carries.
     * </pre>
     *
     * <code>string repo_name = 2;</code>
     * @return The bytes for repoName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRepoNameBytes() {
      return instance.getRepoNameBytes();
    }
    /**
     * <pre>
     * What to call the repository: its rename if it has one, otherwise the name
     * derived from the URL — the same label its row in the switcher carries.
     * </pre>
     *
     * <code>string repo_name = 2;</code>
     * @param value The repoName to set.
     * @return This builder for chaining.
     */
    public Builder setRepoName(
        java.lang.String value) {
      copyOnWrite();
      instance.setRepoName(value);
      return this;
    }
    /**
     * <pre>
     * What to call the repository: its rename if it has one, otherwise the name
     * derived from the URL — the same label its row in the switcher carries.
     * </pre>
     *
     * <code>string repo_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRepoName() {
      copyOnWrite();
      instance.clearRepoName();
      return this;
    }
    /**
     * <pre>
     * What to call the repository: its rename if it has one, otherwise the name
     * derived from the URL — the same label its row in the switcher carries.
     * </pre>
     *
     * <code>string repo_name = 2;</code>
     * @param value The bytes for repoName to set.
     * @return This builder for chaining.
     */
    public Builder setRepoNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRepoNameBytes(value);
      return this;
    }

    /**
     * <pre>
     * What moved, in the words a notification uses: "CI", or "deploy to ios".
     * Here rather than in each app so two clients cannot disagree about what to
     * call a deploy target.
     * </pre>
     *
     * <code>string stage = 3;</code>
     * @return The stage.
     */
    @java.lang.Override
    public java.lang.String getStage() {
      return instance.getStage();
    }
    /**
     * <pre>
     * What moved, in the words a notification uses: "CI", or "deploy to ios".
     * Here rather than in each app so two clients cannot disagree about what to
     * call a deploy target.
     * </pre>
     *
     * <code>string stage = 3;</code>
     * @return The bytes for stage.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStageBytes() {
      return instance.getStageBytes();
    }
    /**
     * <pre>
     * What moved, in the words a notification uses: "CI", or "deploy to ios".
     * Here rather than in each app so two clients cannot disagree about what to
     * call a deploy target.
     * </pre>
     *
     * <code>string stage = 3;</code>
     * @param value The stage to set.
     * @return This builder for chaining.
     */
    public Builder setStage(
        java.lang.String value) {
      copyOnWrite();
      instance.setStage(value);
      return this;
    }
    /**
     * <pre>
     * What moved, in the words a notification uses: "CI", or "deploy to ios".
     * Here rather than in each app so two clients cannot disagree about what to
     * call a deploy target.
     * </pre>
     *
     * <code>string stage = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStage() {
      copyOnWrite();
      instance.clearStage();
      return this;
    }
    /**
     * <pre>
     * What moved, in the words a notification uses: "CI", or "deploy to ios".
     * Here rather than in each app so two clients cannot disagree about what to
     * call a deploy target.
     * </pre>
     *
     * <code>string stage = 3;</code>
     * @param value The bytes for stage to set.
     * @return This builder for chaining.
     */
    public Builder setStageBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setStageBytes(value);
      return this;
    }

    /**
     * <pre>
     * Which direction. Both are worth saying and they are not worth saying the
     * same way — one interrupts, the other can wait for you to look.
     * </pre>
     *
     * <code>bool broke = 4;</code>
     * @return The broke.
     */
    @java.lang.Override
    public boolean getBroke() {
      return instance.getBroke();
    }
    /**
     * <pre>
     * Which direction. Both are worth saying and they are not worth saying the
     * same way — one interrupts, the other can wait for you to look.
     * </pre>
     *
     * <code>bool broke = 4;</code>
     * @param value The broke to set.
     * @return This builder for chaining.
     */
    public Builder setBroke(boolean value) {
      copyOnWrite();
      instance.setBroke(value);
      return this;
    }
    /**
     * <pre>
     * Which direction. Both are worth saying and they are not worth saying the
     * same way — one interrupts, the other can wait for you to look.
     * </pre>
     *
     * <code>bool broke = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearBroke() {
      copyOnWrite();
      instance.clearBroke();
      return this;
    }

    /**
     * <code>.clarity.v1.Status from = 5;</code>
     * @return The enum numeric value on the wire for from.
     */
    @java.lang.Override
    public int getFromValue() {
      return instance.getFromValue();
    }
    /**
     * <code>.clarity.v1.Status from = 5;</code>
     * @param value The from to set.
     * @return This builder for chaining.
     */
    public Builder setFromValue(int value) {
      copyOnWrite();
      instance.setFromValue(value);
      return this;
    }
    /**
     * <code>.clarity.v1.Status from = 5;</code>
     * @return The from.
     */
    @java.lang.Override
    public dev.ezcd.clarity.proto.Status getFrom() {
      return instance.getFrom();
    }
    /**
     * <code>.clarity.v1.Status from = 5;</code>
     * @param value The enum numeric value on the wire for from to set.
     * @return This builder for chaining.
     */
    public Builder setFrom(dev.ezcd.clarity.proto.Status value) {
      copyOnWrite();
      instance.setFrom(value);
      return this;
    }
    /**
     * <code>.clarity.v1.Status from = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearFrom() {
      copyOnWrite();
      instance.clearFrom();
      return this;
    }

    /**
     * <code>.clarity.v1.Status to = 6;</code>
     * @return The enum numeric value on the wire for to.
     */
    @java.lang.Override
    public int getToValue() {
      return instance.getToValue();
    }
    /**
     * <code>.clarity.v1.Status to = 6;</code>
     * @param value The to to set.
     * @return This builder for chaining.
     */
    public Builder setToValue(int value) {
      copyOnWrite();
      instance.setToValue(value);
      return this;
    }
    /**
     * <code>.clarity.v1.Status to = 6;</code>
     * @return The to.
     */
    @java.lang.Override
    public dev.ezcd.clarity.proto.Status getTo() {
      return instance.getTo();
    }
    /**
     * <code>.clarity.v1.Status to = 6;</code>
     * @param value The enum numeric value on the wire for to to set.
     * @return This builder for chaining.
     */
    public Builder setTo(dev.ezcd.clarity.proto.Status value) {
      copyOnWrite();
      instance.setTo(value);
      return this;
    }
    /**
     * <code>.clarity.v1.Status to = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTo() {
      copyOnWrite();
      instance.clearTo();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:clarity.v1.Change)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new dev.ezcd.clarity.proto.Change();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "repoId_",
            "repoName_",
            "stage_",
            "broke_",
            "from_",
            "to_",
          };
          java.lang.String info =
              "\u0000\u0006\u0000\u0000\u0001\u0006\u0006\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208\u0004\u0007\u0005\f\u0006\f";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<dev.ezcd.clarity.proto.Change> parser = PARSER;
        if (parser == null) {
          synchronized (dev.ezcd.clarity.proto.Change.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<dev.ezcd.clarity.proto.Change>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:clarity.v1.Change)
  private static final dev.ezcd.clarity.proto.Change DEFAULT_INSTANCE;
  static {
    Change defaultInstance = new Change();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Change.class, defaultInstance);
  }

  public static dev.ezcd.clarity.proto.Change getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Change> PARSER;

  public static com.google.protobuf.Parser<Change> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

