// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clarity/v1/view.proto

package dev.ezcd.clarity.proto;

public interface ChangesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clarity.v1.Changes)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .clarity.v1.Change changes = 1;</code>
   */
  java.util.List<dev.ezcd.clarity.proto.Change> 
      getChangesList();
  /**
   * <code>repeated .clarity.v1.Change changes = 1;</code>
   */
  dev.ezcd.clarity.proto.Change getChanges(int index);
  /**
   * <code>repeated .clarity.v1.Change changes = 1;</code>
   */
  int getChangesCount();

  /**
   * <pre>
   * How many repositories were reached, and how many could not be. A check that
   * quietly failed for every repository looks exactly like a check that found
   * nothing wrong, and the difference is the whole value of the feature.
   * </pre>
   *
   * <code>int32 checked = 2;</code>
   * @return The checked.
   */
  int getChecked();

  /**
   * <code>int32 unreachable = 3;</code>
   * @return The unreachable.
   */
  int getUnreachable();

  /**
   * <pre>
   * Always set, for the reason View.generated_unix_seconds explains.
   * </pre>
   *
   * <code>int64 generated_unix_seconds = 4;</code>
   * @return The generatedUnixSeconds.
   */
  long getGeneratedUnixSeconds();
}
