// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clarity/v1/view.proto

package dev.ezcd.clarity.proto;

public interface ChangeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clarity.v1.Change)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string repo_id = 1;</code>
   * @return The repoId.
   */
  java.lang.String getRepoId();
  /**
   * <code>string repo_id = 1;</code>
   * @return The bytes for repoId.
   */
  com.google.protobuf.ByteString
      getRepoIdBytes();

  /**
   * <pre>
   * What to call the repository: its rename if it has one, otherwise the name
   * derived from the URL — the same label its row in the switcher carries.
   * </pre>
   *
   * <code>string repo_name = 2;</code>
   * @return The repoName.
   */
  java.lang.String getRepoName();
  /**
   * <pre>
   * What to call the repository: its rename if it has one, otherwise the name
   * derived from the URL — the same label its row in the switcher carries.
   * </pre>
   *
   * <code>string repo_name = 2;</code>
   * @return The bytes for repoName.
   */
  com.google.protobuf.ByteString
      getRepoNameBytes();

  /**
   * <pre>
   * What moved, in the words a notification uses: "CI", or "deploy to ios".
   * Here rather than in each app so two clients cannot disagree about what to
   * call a deploy target.
   * </pre>
   *
   * <code>string stage = 3;</code>
   * @return The stage.
   */
  java.lang.String getStage();
  /**
   * <pre>
   * What moved, in the words a notification uses: "CI", or "deploy to ios".
   * Here rather than in each app so two clients cannot disagree about what to
   * call a deploy target.
   * </pre>
   *
   * <code>string stage = 3;</code>
   * @return The bytes for stage.
   */
  com.google.protobuf.ByteString
      getStageBytes();

  /**
   * <pre>
   * Which direction. Both are worth saying and they are not worth saying the
   * same way — one interrupts, the other can wait for you to look.
   * </pre>
   *
   * <code>bool broke = 4;</code>
   * @return The broke.
   */
  boolean getBroke();

  /**
   * <code>.clarity.v1.Status from = 5;</code>
   * @return The enum numeric value on the wire for from.
   */
  int getFromValue();
  /**
   * <code>.clarity.v1.Status from = 5;</code>
   * @return The from.
   */
  dev.ezcd.clarity.proto.Status getFrom();

  /**
   * <code>.clarity.v1.Status to = 6;</code>
   * @return The enum numeric value on the wire for to.
   */
  int getToValue();
  /**
   * <code>.clarity.v1.Status to = 6;</code>
   * @return The to.
   */
  dev.ezcd.clarity.proto.Status getTo();
}
