// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clarity/v1/view.proto

package dev.ezcd.clarity.proto;

public interface CommitOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clarity.v1.Commit)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string sha = 1;</code>
   * @return The sha.
   */
  java.lang.String getSha();
  /**
   * <code>string sha = 1;</code>
   * @return The bytes for sha.
   */
  com.google.protobuf.ByteString
      getShaBytes();

  /**
   * <code>string short_sha = 2;</code>
   * @return The shortSha.
   */
  java.lang.String getShortSha();
  /**
   * <code>string short_sha = 2;</code>
   * @return The bytes for shortSha.
   */
  com.google.protobuf.ByteString
      getShortShaBytes();

  /**
   * <code>string subject = 3;</code>
   * @return The subject.
   */
  java.lang.String getSubject();
  /**
   * <code>string subject = 3;</code>
   * @return The bytes for subject.
   */
  com.google.protobuf.ByteString
      getSubjectBytes();

  /**
   * <code>string author = 4;</code>
   * @return The author.
   */
  java.lang.String getAuthor();
  /**
   * <code>string author = 4;</code>
   * @return The bytes for author.
   */
  com.google.protobuf.ByteString
      getAuthorBytes();

  /**
   * <code>int64 authored_unix_seconds = 5;</code>
   * @return The authoredUnixSeconds.
   */
  long getAuthoredUnixSeconds();

  /**
   * <pre>
   * "3m 29s"
   * </pre>
   *
   * <code>string age = 6;</code>
   * @return The age.
   */
  java.lang.String getAge();
  /**
   * <pre>
   * "3m 29s"
   * </pre>
   *
   * <code>string age = 6;</code>
   * @return The bytes for age.
   */
  com.google.protobuf.ByteString
      getAgeBytes();

  /**
   * <code>.clarity.v1.Status ci = 7;</code>
   * @return The enum numeric value on the wire for ci.
   */
  int getCiValue();
  /**
   * <code>.clarity.v1.Status ci = 7;</code>
   * @return The ci.
   */
  dev.ezcd.clarity.proto.Status getCi();

  /**
   * <code>.clarity.v1.Status deploy = 8;</code>
   * @return The enum numeric value on the wire for deploy.
   */
  int getDeployValue();
  /**
   * <code>.clarity.v1.Status deploy = 8;</code>
   * @return The deploy.
   */
  dev.ezcd.clarity.proto.Status getDeploy();

  /**
   * <pre>
   * Lead time is absent for a commit that has not shipped, and for one the
   * configured mode excludes. Zero seconds with an empty string means absent;
   * it is not the same as a lead time of zero.
   * </pre>
   *
   * <code>bool has_lead_time = 9;</code>
   * @return The hasLeadTime.
   */
  boolean getHasLeadTime();

  /**
   * <code>int64 lead_time_seconds = 10;</code>
   * @return The leadTimeSeconds.
   */
  long getLeadTimeSeconds();

  /**
   * <code>string lead_time = 11;</code>
   * @return The leadTime.
   */
  java.lang.String getLeadTime();
  /**
   * <code>string lead_time = 11;</code>
   * @return The bytes for leadTime.
   */
  com.google.protobuf.ByteString
      getLeadTimeBytes();

  /**
   * <pre>
   * Live marks a lead time still running — the commit is deployed but the
   * clock has not stopped, so a client may want to keep it ticking.
   * </pre>
   *
   * <code>bool lead_time_live = 12;</code>
   * @return The leadTimeLive.
   */
  boolean getLeadTimeLive();
}
