// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clarity/v1/view.proto

package dev.ezcd.clarity.proto;

/**
 * Protobuf type {@code clarity.v1.Commit}
 */
public  final class Commit extends
    com.google.protobuf.GeneratedMessageLite<
        Commit, Commit.Builder> implements
    // @@protoc_insertion_point(message_implements:clarity.v1.Commit)
    CommitOrBuilder {
  private Commit() {
    sha_ = "";
    shortSha_ = "";
    subject_ = "";
    author_ = "";
    age_ = "";
    leadTime_ = "";
  }
  public static final int SHA_FIELD_NUMBER = 1;
  private java.lang.String sha_;
  /**
   * <code>string sha = 1;</code>
   * @return The sha.
   */
  @java.lang.Override
  public java.lang.String getSha() {
    return sha_;
  }
  /**
   * <code>string sha = 1;</code>
   * @return The bytes for sha.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getShaBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(sha_);
  }
  /**
   * <code>string sha = 1;</code>
   * @param value The sha to set.
   */
  private void setSha(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    sha_ = value;
  }
  /**
   * <code>string sha = 1;</code>
   */
  private void clearSha() {
    
    sha_ = getDefaultInstance().getSha();
  }
  /**
   * <code>string sha = 1;</code>
   * @param value The bytes for sha to set.
   */
  private void setShaBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    sha_ = value.toStringUtf8();
    
  }

  public static final int SHORT_SHA_FIELD_NUMBER = 2;
  private java.lang.String shortSha_;
  /**
   * <code>string short_sha = 2;</code>
   * @return The shortSha.
   */
  @java.lang.Override
  public java.lang.String getShortSha() {
    return shortSha_;
  }
  /**
   * <code>string short_sha = 2;</code>
   * @return The bytes for shortSha.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getShortShaBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(shortSha_);
  }
  /**
   * <code>string short_sha = 2;</code>
   * @param value The shortSha to set.
   */
  private void setShortSha(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    shortSha_ = value;
  }
  /**
   * <code>string short_sha = 2;</code>
   */
  private void clearShortSha() {
    
    shortSha_ = getDefaultInstance().getShortSha();
  }
  /**
   * <code>string short_sha = 2;</code>
   * @param value The bytes for shortSha to set.
   */
  private void setShortShaBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    shortSha_ = value.toStringUtf8();
    
  }

  public static final int SUBJECT_FIELD_NUMBER = 3;
  private java.lang.String subject_;
  /**
   * <code>string subject = 3;</code>
   * @return The subject.
   */
  @java.lang.Override
  public java.lang.String getSubject() {
    return subject_;
  }
  /**
   * <code>string subject = 3;</code>
   * @return The bytes for subject.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSubjectBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(subject_);
  }
  /**
   * <code>string subject = 3;</code>
   * @param value The subject to set.
   */
  private void setSubject(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    subject_ = value;
  }
  /**
   * <code>string subject = 3;</code>
   */
  private void clearSubject() {
    
    subject_ = getDefaultInstance().getSubject();
  }
  /**
   * <code>string subject = 3;</code>
   * @param value The bytes for subject to set.
   */
  private void setSubjectBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    subject_ = value.toStringUtf8();
    
  }

  public static final int AUTHOR_FIELD_NUMBER = 4;
  private java.lang.String author_;
  /**
   * <code>string author = 4;</code>
   * @return The author.
   */
  @java.lang.Override
  public java.lang.String getAuthor() {
    return author_;
  }
  /**
   * <code>string author = 4;</code>
   * @return The bytes for author.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAuthorBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(author_);
  }
  /**
   * <code>string author = 4;</code>
   * @param value The author to set.
   */
  private void setAuthor(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    author_ = value;
  }
  /**
   * <code>string author = 4;</code>
   */
  private void clearAuthor() {
    
    author_ = getDefaultInstance().getAuthor();
  }
  /**
   * <code>string author = 4;</code>
   * @param value The bytes for author to set.
   */
  private void setAuthorBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    author_ = value.toStringUtf8();
    
  }

  public static final int AUTHORED_UNIX_SECONDS_FIELD_NUMBER = 5;
  private long authoredUnixSeconds_;
  /**
   * <code>int64 authored_unix_seconds = 5;</code>
   * @return The authoredUnixSeconds.
   */
  @java.lang.Override
  public long getAuthoredUnixSeconds() {
    return authoredUnixSeconds_;
  }
  /**
   * <code>int64 authored_unix_seconds = 5;</code>
   * @param value The authoredUnixSeconds to set.
   */
  private void setAuthoredUnixSeconds(long value) {
    
    authoredUnixSeconds_ = value;
  }
  /**
   * <code>int64 authored_unix_seconds = 5;</code>
   */
  private void clearAuthoredUnixSeconds() {
    
    authoredUnixSeconds_ = 0L;
  }

  public static final int AGE_FIELD_NUMBER = 6;
  private java.lang.String age_;
  /**
   * <pre>
   * "3m 29s"
   * </pre>
   *
   * <code>string age = 6;</code>
   * @return The age.
   */
  @java.lang.Override
  public java.lang.String getAge() {
    return age_;
  }
  /**
   * <pre>
   * "3m 29s"
   * </pre>
   *
   * <code>string age = 6;</code>
   * @return The bytes for age.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAgeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(age_);
  }
  /**
   * <pre>
   * "3m 29s"
   * </pre>
   *
   * <code>string age = 6;</code>
   * @param value The age to set.
   */
  private void setAge(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    age_ = value;
  }
  /**
   * <pre>
   * "3m 29s"
   * </pre>
   *
   * <code>string age = 6;</code>
   */
  private void clearAge() {
    
    age_ = getDefaultInstance().getAge();
  }
  /**
   * <pre>
   * "3m 29s"
   * </pre>
   *
   * <code>string age = 6;</code>
   * @param value The bytes for age to set.
   */
  private void setAgeBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    age_ = value.toStringUtf8();
    
  }

  public static final int CI_FIELD_NUMBER = 7;
  private int ci_;
  /**
   * <code>.clarity.v1.Status ci = 7;</code>
   * @return The enum numeric value on the wire for ci.
   */
  @java.lang.Override
  public int getCiValue() {
    return ci_;
  }
  /**
   * <code>.clarity.v1.Status ci = 7;</code>
   * @return The ci.
   */
  @java.lang.Override
  public dev.ezcd.clarity.proto.Status getCi() {
    dev.ezcd.clarity.proto.Status result = dev.ezcd.clarity.proto.Status.forNumber(ci_);
    return result == null ? dev.ezcd.clarity.proto.Status.UNRECOGNIZED : result;
  }
  /**
   * <code>.clarity.v1.Status ci = 7;</code>
   * @param value The enum numeric value on the wire for ci to set.
   */
  private void setCiValue(int value) {
      ci_ = value;
  }
  /**
   * <code>.clarity.v1.Status ci = 7;</code>
   * @param value The ci to set.
   */
  private void setCi(dev.ezcd.clarity.proto.Status value) {
    ci_ = value.getNumber();
    
  }
  /**
   * <code>.clarity.v1.Status ci = 7;</code>
   */
  private void clearCi() {
    
    ci_ = 0;
  }

  public static final int DEPLOY_FIELD_NUMBER = 8;
  private int deploy_;
  /**
   * <code>.clarity.v1.Status deploy = 8;</code>
   * @return The enum numeric value on the wire for deploy.
   */
  @java.lang.Override
  public int getDeployValue() {
    return deploy_;
  }
  /**
   * <code>.clarity.v1.Status deploy = 8;</code>
   * @return The deploy.
   */
  @java.lang.Override
  public dev.ezcd.clarity.proto.Status getDeploy() {
    dev.ezcd.clarity.proto.Status result = dev.ezcd.clarity.proto.Status.forNumber(deploy_);
    return result == null ? dev.ezcd.clarity.proto.Status.UNRECOGNIZED : result;
  }
  /**
   * <code>.clarity.v1.Status deploy = 8;</code>
   * @param value The enum numeric value on the wire for deploy to set.
   */
  private void setDeployValue(int value) {
      deploy_ = value;
  }
  /**
   * <code>.clarity.v1.Status deploy = 8;</code>
   * @param value The deploy to set.
   */
  private void setDeploy(dev.ezcd.clarity.proto.Status value) {
    deploy_ = value.getNumber();
    
  }
  /**
   * <code>.clarity.v1.Status deploy = 8;</code>
   */
  private void clearDeploy() {
    
    deploy_ = 0;
  }

  public static final int HAS_LEAD_TIME_FIELD_NUMBER = 9;
  private boolean hasLeadTime_;
  /**
   * <pre>
   * Lead time is absent for a commit that has not shipped, and for one the
   * configured mode excludes. Zero seconds with an empty string means absent;
   * it is not the same as a lead time of zero.
   * </pre>
   *
   * <code>bool has_lead_time = 9;</code>
   * @return The hasLeadTime.
   */
  @java.lang.Override
  public boolean getHasLeadTime() {
    return hasLeadTime_;
  }
  /**
   * <pre>
   * Lead time is absent for a commit that has not shipped, and for one the
   * configured mode excludes. Zero seconds with an empty string means absent;
   * it is not the same as a lead time of zero.
   * </pre>
   *
   * <code>bool has_lead_time = 9;</code>
   * @param value The hasLeadTime to set.
   */
  private void setHasLeadTime(boolean value) {
    
    hasLeadTime_ = value;
  }
  /**
   * <pre>
   * Lead time is absent for a commit that has not shipped, and for one the
   * configured mode excludes. Zero seconds with an empty string means absent;
   * it is not the same as a lead time of zero.
   * </pre>
   *
   * <code>bool has_lead_time = 9;</code>
   */
  private void clearHasLeadTime() {
    
    hasLeadTime_ = false;
  }

  public static final int LEAD_TIME_SECONDS_FIELD_NUMBER = 10;
  private long leadTimeSeconds_;
  /**
   * <code>int64 lead_time_seconds = 10;</code>
   * @return The leadTimeSeconds.
   */
  @java.lang.Override
  public long getLeadTimeSeconds() {
    return leadTimeSeconds_;
  }
  /**
   * <code>int64 lead_time_seconds = 10;</code>
   * @param value The leadTimeSeconds to set.
   */
  private void setLeadTimeSeconds(long value) {
    
    leadTimeSeconds_ = value;
  }
  /**
   * <code>int64 lead_time_seconds = 10;</code>
   */
  private void clearLeadTimeSeconds() {
    
    leadTimeSeconds_ = 0L;
  }

  public static final int LEAD_TIME_FIELD_NUMBER = 11;
  private java.lang.String leadTime_;
  /**
   * <code>string lead_time = 11;</code>
   * @return The leadTime.
   */
  @java.lang.Override
  public java.lang.String getLeadTime() {
    return leadTime_;
  }
  /**
   * <code>string lead_time = 11;</code>
   * @return The bytes for leadTime.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLeadTimeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(leadTime_);
  }
  /**
   * <code>string lead_time = 11;</code>
   * @param value The leadTime to set.
   */
  private void setLeadTime(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    leadTime_ = value;
  }
  /**
   * <code>string lead_time = 11;</code>
   */
  private void clearLeadTime() {
    
    leadTime_ = getDefaultInstance().getLeadTime();
  }
  /**
   * <code>string lead_time = 11;</code>
   * @param value The bytes for leadTime to set.
   */
  private void setLeadTimeBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    leadTime_ = value.toStringUtf8();
    
  }

  public static final int LEAD_TIME_LIVE_FIELD_NUMBER = 12;
  private boolean leadTimeLive_;
  /**
   * <pre>
   * Live marks a lead time still running — the commit is deployed but the
   * clock has not stopped, so a client may want to keep it ticking.
   * </pre>
   *
   * <code>bool lead_time_live = 12;</code>
   * @return The leadTimeLive.
   */
  @java.lang.Override
  public boolean getLeadTimeLive() {
    return leadTimeLive_;
  }
  /**
   * <pre>
   * Live marks a lead time still running — the commit is deployed but the
   * clock has not stopped, so a client may want to keep it ticking.
   * </pre>
   *
   * <code>bool lead_time_live = 12;</code>
   * @param value The leadTimeLive to set.
   */
  private void setLeadTimeLive(boolean value) {
    
    leadTimeLive_ = value;
  }
  /**
   * <pre>
   * Live marks a lead time still running — the commit is deployed but the
   * clock has not stopped, so a client may want to keep it ticking.
   * </pre>
   *
   * <code>bool lead_time_live = 12;</code>
   */
  private void clearLeadTimeLive() {
    
    leadTimeLive_ = false;
  }

  public static dev.ezcd.clarity.proto.Commit parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.Commit parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.Commit parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.Commit parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.Commit parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.Commit parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.Commit parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.Commit parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.Commit parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.Commit parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.Commit parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.Commit parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(dev.ezcd.clarity.proto.Commit prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code clarity.v1.Commit}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        dev.ezcd.clarity.proto.Commit, Builder> implements
      // @@protoc_insertion_point(builder_implements:clarity.v1.Commit)
      dev.ezcd.clarity.proto.CommitOrBuilder {
    // Construct using dev.ezcd.clarity.proto.Commit.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string sha = 1;</code>
     * @return The sha.
     */
    @java.lang.Override
    public java.lang.String getSha() {
      return instance.getSha();
    }
    /**
     * <code>string sha = 1;</code>
     * @return The bytes for sha.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getShaBytes() {
      return instance.getShaBytes();
    }
    /**
     * <code>string sha = 1;</code>
     * @param value The sha to set.
     * @return This builder for chaining.
     */
    public Builder setSha(
        java.lang.String value) {
      copyOnWrite();
      instance.setSha(value);
      return this;
    }
    /**
     * <code>string sha = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSha() {
      copyOnWrite();
      instance.clearSha();
      return this;
    }
    /**
     * <code>string sha = 1;</code>
     * @param value The bytes for sha to set.
     * @return This builder for chaining.
     */
    public Builder setShaBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setShaBytes(value);
      return this;
    }

    /**
     * <code>string short_sha = 2;</code>
     * @return The shortSha.
     */
    @java.lang.Override
    public java.lang.String getShortSha() {
      return instance.getShortSha();
    }
    /**
     * <code>string short_sha = 2;</code>
     * @return The bytes for shortSha.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getShortShaBytes() {
      return instance.getShortShaBytes();
    }
    /**
     * <code>string short_sha = 2;</code>
     * @param value The shortSha to set.
     * @return This builder for chaining.
     */
    public Builder setShortSha(
        java.lang.String value) {
      copyOnWrite();
      instance.setShortSha(value);
      return this;
    }
    /**
     * <code>string short_sha = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearShortSha() {
      copyOnWrite();
      instance.clearShortSha();
      return this;
    }
    /**
     * <code>string short_sha = 2;</code>
     * @param value The bytes for shortSha to set.
     * @return This builder for chaining.
     */
    public Builder setShortShaBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setShortShaBytes(value);
      return this;
    }

    /**
     * <code>string subject = 3;</code>
     * @return The subject.
     */
    @java.lang.Override
    public java.lang.String getSubject() {
      return instance.getSubject();
    }
    /**
     * <code>string subject = 3;</code>
     * @return The bytes for subject.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSubjectBytes() {
      return instance.getSubjectBytes();
    }
    /**
     * <code>string subject = 3;</code>
     * @param value The subject to set.
     * @return This builder for chaining.
     */
    public Builder setSubject(
        java.lang.String value) {
      copyOnWrite();
      instance.setSubject(value);
      return this;
    }
    /**
     * <code>string subject = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSubject() {
      copyOnWrite();
      instance.clearSubject();
      return this;
    }
    /**
     * <code>string subject = 3;</code>
     * @param value The bytes for subject to set.
     * @return This builder for chaining.
     */
    public Builder setSubjectBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSubjectBytes(value);
      return this;
    }

    /**
     * <code>string author = 4;</code>
     * @return The author.
     */
    @java.lang.Override
    public java.lang.String getAuthor() {
      return instance.getAuthor();
    }
    /**
     * <code>string author = 4;</code>
     * @return The bytes for author.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAuthorBytes() {
      return instance.getAuthorBytes();
    }
    /**
     * <code>string author = 4;</code>
     * @param value The author to set.
     * @return This builder for chaining.
     */
    public Builder setAuthor(
        java.lang.String value) {
      copyOnWrite();
      instance.setAuthor(value);
      return this;
    }
    /**
     * <code>string author = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAuthor() {
      copyOnWrite();
      instance.clearAuthor();
      return this;
    }
    /**
     * <code>string author = 4;</code>
     * @param value The bytes for author to set.
     * @return This builder for chaining.
     */
    public Builder setAuthorBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAuthorBytes(value);
      return this;
    }

    /**
     * <code>int64 authored_unix_seconds = 5;</code>
     * @return The authoredUnixSeconds.
     */
    @java.lang.Override
    public long getAuthoredUnixSeconds() {
      return instance.getAuthoredUnixSeconds();
    }
    /**
     * <code>int64 authored_unix_seconds = 5;</code>
     * @param value The authoredUnixSeconds to set.
     * @return This builder for chaining.
     */
    public Builder setAuthoredUnixSeconds(long value) {
      copyOnWrite();
      instance.setAuthoredUnixSeconds(value);
      return this;
    }
    /**
     * <code>int64 authored_unix_seconds = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAuthoredUnixSeconds() {
      copyOnWrite();
      instance.clearAuthoredUnixSeconds();
      return this;
    }

    /**
     * <pre>
     * "3m 29s"
     * </pre>
     *
     * <code>string age = 6;</code>
     * @return The age.
     */
    @java.lang.Override
    public java.lang.String getAge() {
      return instance.getAge();
    }
    /**
     * <pre>
     * "3m 29s"
     * </pre>
     *
     * <code>string age = 6;</code>
     * @return The bytes for age.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAgeBytes() {
      return instance.getAgeBytes();
    }
    /**
     * <pre>
     * "3m 29s"
     * </pre>
     *
     * <code>string age = 6;</code>
     * @param value The age to set.
     * @return This builder for chaining.
     */
    public Builder setAge(
        java.lang.String value) {
      copyOnWrite();
      instance.setAge(value);
      return this;
    }
    /**
     * <pre>
     * "3m 29s"
     * </pre>
     *
     * <code>string age = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearAge() {
      copyOnWrite();
      instance.clearAge();
      return this;
    }
    /**
     * <pre>
     * "3m 29s"
     * </pre>
     *
     * <code>string age = 6;</code>
     * @param value The bytes for age to set.
     * @return This builder for chaining.
     */
    public Builder setAgeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAgeBytes(value);
      return this;
    }

    /**
     * <code>.clarity.v1.Status ci = 7;</code>
     * @return The enum numeric value on the wire for ci.
     */
    @java.lang.Override
    public int getCiValue() {
      return instance.getCiValue();
    }
    /**
     * <code>.clarity.v1.Status ci = 7;</code>
     * @param value The ci to set.
     * @return This builder for chaining.
     */
    public Builder setCiValue(int value) {
      copyOnWrite();
      instance.setCiValue(value);
      return this;
    }
    /**
     * <code>.clarity.v1.Status ci = 7;</code>
     * @return The ci.
     */
    @java.lang.Override
    public dev.ezcd.clarity.proto.Status getCi() {
      return instance.getCi();
    }
    /**
     * <code>.clarity.v1.Status ci = 7;</code>
     * @param value The enum numeric value on the wire for ci to set.
     * @return This builder for chaining.
     */
    public Builder setCi(dev.ezcd.clarity.proto.Status value) {
      copyOnWrite();
      instance.setCi(value);
      return this;
    }
    /**
     * <code>.clarity.v1.Status ci = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearCi() {
      copyOnWrite();
      instance.clearCi();
      return this;
    }

    /**
     * <code>.clarity.v1.Status deploy = 8;</code>
     * @return The enum numeric value on the wire for deploy.
     */
    @java.lang.Override
    public int getDeployValue() {
      return instance.getDeployValue();
    }
    /**
     * <code>.clarity.v1.Status deploy = 8;</code>
     * @param value The deploy to set.
     * @return This builder for chaining.
     */
    public Builder setDeployValue(int value) {
      copyOnWrite();
      instance.setDeployValue(value);
      return this;
    }
    /**
     * <code>.clarity.v1.Status deploy = 8;</code>
     * @return The deploy.
     */
    @java.lang.Override
    public dev.ezcd.clarity.proto.Status getDeploy() {
      return instance.getDeploy();
    }
    /**
     * <code>.clarity.v1.Status deploy = 8;</code>
     * @param value The enum numeric value on the wire for deploy to set.
     * @return This builder for chaining.
     */
    public Builder setDeploy(dev.ezcd.clarity.proto.Status value) {
      copyOnWrite();
      instance.setDeploy(value);
      return this;
    }
    /**
     * <code>.clarity.v1.Status deploy = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeploy() {
      copyOnWrite();
      instance.clearDeploy();
      return this;
    }

    /**
     * <pre>
     * Lead time is absent for a commit that has not shipped, and for one the
     * configured mode excludes. Zero seconds with an empty string means absent;
     * it is not the same as a lead time of zero.
     * </pre>
     *
     * <code>bool has_lead_time = 9;</code>
     * @return The hasLeadTime.
     */
    @java.lang.Override
    public boolean getHasLeadTime() {
      return instance.getHasLeadTime();
    }
    /**
     * <pre>
     * Lead time is absent for a commit that has not shipped, and for one the
     * configured mode excludes. Zero seconds with an empty string means absent;
     * it is not the same as a lead time of zero.
     * </pre>
     *
     * <code>bool has_lead_time = 9;</code>
     * @param value The hasLeadTime to set.
     * @return This builder for chaining.
     */
    public Builder setHasLeadTime(boolean value) {
      copyOnWrite();
      instance.setHasLeadTime(value);
      return this;
    }
    /**
     * <pre>
     * Lead time is absent for a commit that has not shipped, and for one the
     * configured mode excludes. Zero seconds with an empty string means absent;
     * it is not the same as a lead time of zero.
     * </pre>
     *
     * <code>bool has_lead_time = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearHasLeadTime() {
      copyOnWrite();
      instance.clearHasLeadTime();
      return this;
    }

    /**
     * <code>int64 lead_time_seconds = 10;</code>
     * @return The leadTimeSeconds.
     */
    @java.lang.Override
    public long getLeadTimeSeconds() {
      return instance.getLeadTimeSeconds();
    }
    /**
     * <code>int64 lead_time_seconds = 10;</code>
     * @param value The leadTimeSeconds to set.
     * @return This builder for chaining.
     */
    public Builder setLeadTimeSeconds(long value) {
      copyOnWrite();
      instance.setLeadTimeSeconds(value);
      return this;
    }
    /**
     * <code>int64 lead_time_seconds = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearLeadTimeSeconds() {
      copyOnWrite();
      instance.clearLeadTimeSeconds();
      return this;
    }

    /**
     * <code>string lead_time = 11;</code>
     * @return The leadTime.
     */
    @java.lang.Override
    public java.lang.String getLeadTime() {
      return instance.getLeadTime();
    }
    /**
     * <code>string lead_time = 11;</code>
     * @return The bytes for leadTime.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLeadTimeBytes() {
      return instance.getLeadTimeBytes();
    }
    /**
     * <code>string lead_time = 11;</code>
     * @param value The leadTime to set.
     * @return This builder for chaining.
     */
    public Builder setLeadTime(
        java.lang.String value) {
      copyOnWrite();
      instance.setLeadTime(value);
      return this;
    }
    /**
     * <code>string lead_time = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearLeadTime() {
      copyOnWrite();
      instance.clearLeadTime();
      return this;
    }
    /**
     * <code>string lead_time = 11;</code>
     * @param value The bytes for leadTime to set.
     * @return This builder for chaining.
     */
    public Builder setLeadTimeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setLeadTimeBytes(value);
      return this;
    }

    /**
     * <pre>
     * Live marks a lead time still running — the commit is deployed but the
     * clock has not stopped, so a client may want to keep it ticking.
     * </pre>
     *
     * <code>bool lead_time_live = 12;</code>
     * @return The leadTimeLive.
     */
    @java.lang.Override
    public boolean getLeadTimeLive() {
      return instance.getLeadTimeLive();
    }
    /**
     * <pre>
     * Live marks a lead time still running — the commit is deployed but the
     * clock has not stopped, so a client may want to keep it ticking.
     * </pre>
     *
     * <code>bool lead_time_live = 12;</code>
     * @param value The leadTimeLive to set.
     * @return This builder for chaining.
     */
    public Builder setLeadTimeLive(boolean value) {
      copyOnWrite();
      instance.setLeadTimeLive(value);
      return this;
    }
    /**
     * <pre>
     * Live marks a lead time still running — the commit is deployed but the
     * clock has not stopped, so a client may want to keep it ticking.
     * </pre>
     *
     * <code>bool lead_time_live = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearLeadTimeLive() {
      copyOnWrite();
      instance.clearLeadTimeLive();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:clarity.v1.Commit)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new dev.ezcd.clarity.proto.Commit();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "sha_",
            "shortSha_",
            "subject_",
            "author_",
            "authoredUnixSeconds_",
            "age_",
            "ci_",
            "deploy_",
            "hasLeadTime_",
            "leadTimeSeconds_",
            "leadTime_",
            "leadTimeLive_",
          };
          java.lang.String info =
              "\u0000\f\u0000\u0000\u0001\f\f\u0000\u0000\u0000\u0001\u0208\u0002\u0208\u0003\u0208" +
              "\u0004\u0208\u0005\u0002\u0006\u0208\u0007\f\b\f\t\u0007\n\u0002\u000b\u0208\f\u0007" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<dev.ezcd.clarity.proto.Commit> parser = PARSER;
        if (parser == null) {
          synchronized (dev.ezcd.clarity.proto.Commit.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<dev.ezcd.clarity.proto.Commit>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:clarity.v1.Commit)
  private static final dev.ezcd.clarity.proto.Commit DEFAULT_INSTANCE;
  static {
    Commit defaultInstance = new Commit();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Commit.class, defaultInstance);
  }

  public static dev.ezcd.clarity.proto.Commit getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Commit> PARSER;

  public static com.google.protobuf.Parser<Commit> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

