// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clarity/v1/view.proto

package dev.ezcd.clarity.proto;

public interface FlowSummaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clarity.v1.FlowSummary)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.clarity.v1.Status deploy = 2;</code>
   * @return The enum numeric value on the wire for deploy.
   */
  int getDeployValue();
  /**
   * <code>.clarity.v1.Status deploy = 2;</code>
   * @return The deploy.
   */
  dev.ezcd.clarity.proto.Status getDeploy();
}
