// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clarity/v1/view.proto

package dev.ezcd.clarity.proto;

/**
 * Protobuf type {@code clarity.v1.Flow}
 */
public  final class Flow extends
    com.google.protobuf.GeneratedMessageLite<
        Flow, Flow.Builder> implements
    // @@protoc_insertion_point(message_implements:clarity.v1.Flow)
    FlowOrBuilder {
  private Flow() {
    name_ = "";
    sections_ = emptyProtobufList();
  }
  public static final int NAME_FIELD_NUMBER = 1;
  private java.lang.String name_;
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    return name_;
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(name_);
  }
  /**
   * <code>string name = 1;</code>
   * @param value The name to set.
   */
  private void setName(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    name_ = value;
  }
  /**
   * <code>string name = 1;</code>
   */
  private void clearName() {
    
    name_ = getDefaultInstance().getName();
  }
  /**
   * <code>string name = 1;</code>
   * @param value The bytes for name to set.
   */
  private void setNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    name_ = value.toStringUtf8();
    
  }

  public static final int DEPLOY_FIELD_NUMBER = 2;
  private int deploy_;
  /**
   * <code>.clarity.v1.Status deploy = 2;</code>
   * @return The enum numeric value on the wire for deploy.
   */
  @java.lang.Override
  public int getDeployValue() {
    return deploy_;
  }
  /**
   * <code>.clarity.v1.Status deploy = 2;</code>
   * @return The deploy.
   */
  @java.lang.Override
  public dev.ezcd.clarity.proto.Status getDeploy() {
    dev.ezcd.clarity.proto.Status result = dev.ezcd.clarity.proto.Status.forNumber(deploy_);
    return result == null ? dev.ezcd.clarity.proto.Status.UNRECOGNIZED : result;
  }
  /**
   * <code>.clarity.v1.Status deploy = 2;</code>
   * @param value The enum numeric value on the wire for deploy to set.
   */
  private void setDeployValue(int value) {
      deploy_ = value;
  }
  /**
   * <code>.clarity.v1.Status deploy = 2;</code>
   * @param value The deploy to set.
   */
  private void setDeploy(dev.ezcd.clarity.proto.Status value) {
    deploy_ = value.getNumber();
    
  }
  /**
   * <code>.clarity.v1.Status deploy = 2;</code>
   */
  private void clearDeploy() {
    
    deploy_ = 0;
  }

  public static final int UNDECLARED_FIELD_NUMBER = 3;
  private boolean undeclared_;
  /**
   * <pre>
   * Undeclared marks a target seen in the events but absent from
   * .ezcd.json — a typo, or something added without updating config.
   * Surfaced rather than dropped: a silently discarded deploy is worse than
   * an unexpected tab.
   * </pre>
   *
   * <code>bool undeclared = 3;</code>
   * @return The undeclared.
   */
  @java.lang.Override
  public boolean getUndeclared() {
    return undeclared_;
  }
  /**
   * <pre>
   * Undeclared marks a target seen in the events but absent from
   * .ezcd.json — a typo, or something added without updating config.
   * Surfaced rather than dropped: a silently discarded deploy is worse than
   * an unexpected tab.
   * </pre>
   *
   * <code>bool undeclared = 3;</code>
   * @param value The undeclared to set.
   */
  private void setUndeclared(boolean value) {
    
    undeclared_ = value;
  }
  /**
   * <pre>
   * Undeclared marks a target seen in the events but absent from
   * .ezcd.json — a typo, or something added without updating config.
   * Surfaced rather than dropped: a silently discarded deploy is worse than
   * an unexpected tab.
   * </pre>
   *
   * <code>bool undeclared = 3;</code>
   */
  private void clearUndeclared() {
    
    undeclared_ = false;
  }

  public static final int SECTIONS_FIELD_NUMBER = 4;
  private com.google.protobuf.Internal.ProtobufList<dev.ezcd.clarity.proto.Section> sections_;
  /**
   * <code>repeated .clarity.v1.Section sections = 4;</code>
   */
  @java.lang.Override
  public java.util.List<dev.ezcd.clarity.proto.Section> getSectionsList() {
    return sections_;
  }
  /**
   * <code>repeated .clarity.v1.Section sections = 4;</code>
   */
  public java.util.List<? extends dev.ezcd.clarity.proto.SectionOrBuilder> 
      getSectionsOrBuilderList() {
    return sections_;
  }
  /**
   * <code>repeated .clarity.v1.Section sections = 4;</code>
   */
  @java.lang.Override
  public int getSectionsCount() {
    return sections_.size();
  }
  /**
   * <code>repeated .clarity.v1.Section sections = 4;</code>
   */
  @java.lang.Override
  public dev.ezcd.clarity.proto.Section getSections(int index) {
    return sections_.get(index);
  }
  /**
   * <code>repeated .clarity.v1.Section sections = 4;</code>
   */
  public dev.ezcd.clarity.proto.SectionOrBuilder getSectionsOrBuilder(
      int index) {
    return sections_.get(index);
  }
  private void ensureSectionsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<dev.ezcd.clarity.proto.Section> tmp = sections_;
    if (!tmp.isModifiable()) {
      sections_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .clarity.v1.Section sections = 4;</code>
   */
  private void setSections(
      int index, dev.ezcd.clarity.proto.Section value) {
    value.getClass();
  ensureSectionsIsMutable();
    sections_.set(index, value);
  }
  /**
   * <code>repeated .clarity.v1.Section sections = 4;</code>
   */
  private void addSections(dev.ezcd.clarity.proto.Section value) {
    value.getClass();
  ensureSectionsIsMutable();
    sections_.add(value);
  }
  /**
   * <code>repeated .clarity.v1.Section sections = 4;</code>
   */
  private void addSections(
      int index, dev.ezcd.clarity.proto.Section value) {
    value.getClass();
  ensureSectionsIsMutable();
    sections_.add(index, value);
  }
  /**
   * <code>repeated .clarity.v1.Section sections = 4;</code>
   */
  private void addAllSections(
      java.lang.Iterable<? extends dev.ezcd.clarity.proto.Section> values) {
    ensureSectionsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, sections_);
  }
  /**
   * <code>repeated .clarity.v1.Section sections = 4;</code>
   */
  private void clearSections() {
    sections_ = emptyProtobufList();
  }
  /**
   * <code>repeated .clarity.v1.Section sections = 4;</code>
   */
  private void removeSections(int index) {
    ensureSectionsIsMutable();
    sections_.remove(index);
  }

  public static dev.ezcd.clarity.proto.Flow parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.Flow parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.Flow parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.Flow parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.Flow parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.Flow parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.Flow parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.Flow parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.Flow parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.Flow parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.Flow parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.Flow parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(dev.ezcd.clarity.proto.Flow prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code clarity.v1.Flow}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        dev.ezcd.clarity.proto.Flow, Builder> implements
      // @@protoc_insertion_point(builder_implements:clarity.v1.Flow)
      dev.ezcd.clarity.proto.FlowOrBuilder {
    // Construct using dev.ezcd.clarity.proto.Flow.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      return instance.getName();
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return instance.getNameBytes();
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      copyOnWrite();
      instance.setName(value);
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      copyOnWrite();
      instance.clearName();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameBytes(value);
      return this;
    }

    /**
     * <code>.clarity.v1.Status deploy = 2;</code>
     * @return The enum numeric value on the wire for deploy.
     */
    @java.lang.Override
    public int getDeployValue() {
      return instance.getDeployValue();
    }
    /**
     * <code>.clarity.v1.Status deploy = 2;</code>
     * @param value The deploy to set.
     * @return This builder for chaining.
     */
    public Builder setDeployValue(int value) {
      copyOnWrite();
      instance.setDeployValue(value);
      return this;
    }
    /**
     * <code>.clarity.v1.Status deploy = 2;</code>
     * @return The deploy.
     */
    @java.lang.Override
    public dev.ezcd.clarity.proto.Status getDeploy() {
      return instance.getDeploy();
    }
    /**
     * <code>.clarity.v1.Status deploy = 2;</code>
     * @param value The enum numeric value on the wire for deploy to set.
     * @return This builder for chaining.
     */
    public Builder setDeploy(dev.ezcd.clarity.proto.Status value) {
      copyOnWrite();
      instance.setDeploy(value);
      return this;
    }
    /**
     * <code>.clarity.v1.Status deploy = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeploy() {
      copyOnWrite();
      instance.clearDeploy();
      return this;
    }

    /**
     * <pre>
     * Undeclared marks a target seen in the events but absent from
     * .ezcd.json — a typo, or something added without updating config.
     * Surfaced rather than dropped: a silently discarded deploy is worse than
     * an unexpected tab.
     * </pre>
     *
     * <code>bool undeclared = 3;</code>
     * @return The undeclared.
     */
    @java.lang.Override
    public boolean getUndeclared() {
      return instance.getUndeclared();
    }
    /**
     * <pre>
     * Undeclared marks a target seen in the events but absent from
     * .ezcd.json — a typo, or something added without updating config.
     * Surfaced rather than dropped: a silently discarded deploy is worse than
     * an unexpected tab.
     * </pre>
     *
     * <code>bool undeclared = 3;</code>
     * @param value The undeclared to set.
     * @return This builder for chaining.
     */
    public Builder setUndeclared(boolean value) {
      copyOnWrite();
      instance.setUndeclared(value);
      return this;
    }
    /**
     * <pre>
     * Undeclared marks a target seen in the events but absent from
     * .ezcd.json — a typo, or something added without updating config.
     * Surfaced rather than dropped: a silently discarded deploy is worse than
     * an unexpected tab.
     * </pre>
     *
     * <code>bool undeclared = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUndeclared() {
      copyOnWrite();
      instance.clearUndeclared();
      return this;
    }

    /**
     * <code>repeated .clarity.v1.Section sections = 4;</code>
     */
    @java.lang.Override
    public java.util.List<dev.ezcd.clarity.proto.Section> getSectionsList() {
      return java.util.Collections.unmodifiableList(
          instance.getSectionsList());
    }
    /**
     * <code>repeated .clarity.v1.Section sections = 4;</code>
     */
    @java.lang.Override
    public int getSectionsCount() {
      return instance.getSectionsCount();
    }/**
     * <code>repeated .clarity.v1.Section sections = 4;</code>
     */
    @java.lang.Override
    public dev.ezcd.clarity.proto.Section getSections(int index) {
      return instance.getSections(index);
    }
    /**
     * <code>repeated .clarity.v1.Section sections = 4;</code>
     */
    public Builder setSections(
        int index, dev.ezcd.clarity.proto.Section value) {
      copyOnWrite();
      instance.setSections(index, value);
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Section sections = 4;</code>
     */
    public Builder setSections(
        int index, dev.ezcd.clarity.proto.Section.Builder builderForValue) {
      copyOnWrite();
      instance.setSections(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Section sections = 4;</code>
     */
    public Builder addSections(dev.ezcd.clarity.proto.Section value) {
      copyOnWrite();
      instance.addSections(value);
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Section sections = 4;</code>
     */
    public Builder addSections(
        int index, dev.ezcd.clarity.proto.Section value) {
      copyOnWrite();
      instance.addSections(index, value);
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Section sections = 4;</code>
     */
    public Builder addSections(
        dev.ezcd.clarity.proto.Section.Builder builderForValue) {
      copyOnWrite();
      instance.addSections(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Section sections = 4;</code>
     */
    public Builder addSections(
        int index, dev.ezcd.clarity.proto.Section.Builder builderForValue) {
      copyOnWrite();
      instance.addSections(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Section sections = 4;</code>
     */
    public Builder addAllSections(
        java.lang.Iterable<? extends dev.ezcd.clarity.proto.Section> values) {
      copyOnWrite();
      instance.addAllSections(values);
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Section sections = 4;</code>
     */
    public Builder clearSections() {
      copyOnWrite();
      instance.clearSections();
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Section sections = 4;</code>
     */
    public Builder removeSections(int index) {
      copyOnWrite();
      instance.removeSections(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:clarity.v1.Flow)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new dev.ezcd.clarity.proto.Flow();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "name_",
            "deploy_",
            "undeclared_",
            "sections_",
            dev.ezcd.clarity.proto.Section.class,
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0001\u0000\u0001\u0208\u0002\f" +
              "\u0003\u0007\u0004\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<dev.ezcd.clarity.proto.Flow> parser = PARSER;
        if (parser == null) {
          synchronized (dev.ezcd.clarity.proto.Flow.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<dev.ezcd.clarity.proto.Flow>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:clarity.v1.Flow)
  private static final dev.ezcd.clarity.proto.Flow DEFAULT_INSTANCE;
  static {
    Flow defaultInstance = new Flow();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Flow.class, defaultInstance);
  }

  public static dev.ezcd.clarity.proto.Flow getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Flow> PARSER;

  public static com.google.protobuf.Parser<Flow> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

