// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clarity/v1/view.proto

package dev.ezcd.clarity.proto;

public interface FlowOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clarity.v1.Flow)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.clarity.v1.Status deploy = 2;</code>
   * @return The enum numeric value on the wire for deploy.
   */
  int getDeployValue();
  /**
   * <code>.clarity.v1.Status deploy = 2;</code>
   * @return The deploy.
   */
  dev.ezcd.clarity.proto.Status getDeploy();

  /**
   * <pre>
   * Undeclared marks a target seen in the events but absent from
   * .ezcd.json — a typo, or something added without updating config.
   * Surfaced rather than dropped: a silently discarded deploy is worse than
   * an unexpected tab.
   * </pre>
   *
   * <code>bool undeclared = 3;</code>
   * @return The undeclared.
   */
  boolean getUndeclared();

  /**
   * <code>repeated .clarity.v1.Group groups = 4;</code>
   */
  java.util.List<dev.ezcd.clarity.proto.Group> 
      getGroupsList();
  /**
   * <code>repeated .clarity.v1.Group groups = 4;</code>
   */
  dev.ezcd.clarity.proto.Group getGroups(int index);
  /**
   * <code>repeated .clarity.v1.Group groups = 4;</code>
   */
  int getGroupsCount();
}
