// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clarity/v1/view.proto

package dev.ezcd.clarity.proto;

/**
 * <pre>
 * GroupKind is a commit's position in the lifecycle.
 * </pre>
 *
 * Protobuf enum {@code clarity.v1.GroupKind}
 */
public enum GroupKind
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>GROUP_KIND_UNSPECIFIED = 0;</code>
   */
  GROUP_KIND_UNSPECIFIED(0),
  /**
   * <pre>
   * landed, CI not green yet
   * </pre>
   *
   * <code>GROUP_KIND_HEAD = 1;</code>
   */
  GROUP_KIND_HEAD(1),
  /**
   * <pre>
   * green, waiting for a deploy
   * </pre>
   *
   * <code>GROUP_KIND_CI_PASSED = 2;</code>
   */
  GROUP_KIND_CI_PASSED(2),
  /**
   * <pre>
   * a deploy attempt that has not landed
   * </pre>
   *
   * <code>GROUP_KIND_IN_FLIGHT = 3;</code>
   */
  GROUP_KIND_IN_FLIGHT(3),
  /**
   * <pre>
   * one successful deploy, with what it shipped
   * </pre>
   *
   * <code>GROUP_KIND_DEPLOYED = 4;</code>
   */
  GROUP_KIND_DEPLOYED(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>GROUP_KIND_UNSPECIFIED = 0;</code>
   */
  public static final int GROUP_KIND_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * landed, CI not green yet
   * </pre>
   *
   * <code>GROUP_KIND_HEAD = 1;</code>
   */
  public static final int GROUP_KIND_HEAD_VALUE = 1;
  /**
   * <pre>
   * green, waiting for a deploy
   * </pre>
   *
   * <code>GROUP_KIND_CI_PASSED = 2;</code>
   */
  public static final int GROUP_KIND_CI_PASSED_VALUE = 2;
  /**
   * <pre>
   * a deploy attempt that has not landed
   * </pre>
   *
   * <code>GROUP_KIND_IN_FLIGHT = 3;</code>
   */
  public static final int GROUP_KIND_IN_FLIGHT_VALUE = 3;
  /**
   * <pre>
   * one successful deploy, with what it shipped
   * </pre>
   *
   * <code>GROUP_KIND_DEPLOYED = 4;</code>
   */
  public static final int GROUP_KIND_DEPLOYED_VALUE = 4;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static GroupKind valueOf(int value) {
    return forNumber(value);
  }

  public static GroupKind forNumber(int value) {
    switch (value) {
      case 0: return GROUP_KIND_UNSPECIFIED;
      case 1: return GROUP_KIND_HEAD;
      case 2: return GROUP_KIND_CI_PASSED;
      case 3: return GROUP_KIND_IN_FLIGHT;
      case 4: return GROUP_KIND_DEPLOYED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<GroupKind>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      GroupKind> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<GroupKind>() {
          @java.lang.Override
          public GroupKind findValueByNumber(int number) {
            return GroupKind.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return GroupKindVerifier.INSTANCE;
  }

  private static final class GroupKindVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new GroupKindVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return GroupKind.forNumber(number) != null;
          }
        };

  private final int value;

  private GroupKind(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:clarity.v1.GroupKind)
}

