// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clarity/v1/view.proto

package dev.ezcd.clarity.proto;

public interface GroupOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clarity.v1.Group)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.clarity.v1.GroupKind kind = 1;</code>
   * @return The enum numeric value on the wire for kind.
   */
  int getKindValue();
  /**
   * <code>.clarity.v1.GroupKind kind = 1;</code>
   * @return The kind.
   */
  dev.ezcd.clarity.proto.GroupKind getKind();

  /**
   * <pre>
   * Label names the section: "HEAD", "CI Passed", "Deployed". Here rather
   * than on the client so three UIs cannot disagree about what to call it.
   * </pre>
   *
   * <code>string label = 2;</code>
   * @return The label.
   */
  java.lang.String getLabel();
  /**
   * <pre>
   * Label names the section: "HEAD", "CI Passed", "Deployed". Here rather
   * than on the client so three UIs cannot disagree about what to call it.
   * </pre>
   *
   * <code>string label = 2;</code>
   * @return The bytes for label.
   */
  com.google.protobuf.ByteString
      getLabelBytes();

  /**
   * <pre>
   * Status and timing of the deploy this group represents. Only meaningful
   * for IN_FLIGHT and DEPLOYED, where each group is one deploy attempt.
   * </pre>
   *
   * <code>.clarity.v1.Status status = 3;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <pre>
   * Status and timing of the deploy this group represents. Only meaningful
   * for IN_FLIGHT and DEPLOYED, where each group is one deploy attempt.
   * </pre>
   *
   * <code>.clarity.v1.Status status = 3;</code>
   * @return The status.
   */
  dev.ezcd.clarity.proto.Status getStatus();

  /**
   * <code>int64 deployed_unix_seconds = 4;</code>
   * @return The deployedUnixSeconds.
   */
  long getDeployedUnixSeconds();

  /**
   * <pre>
   * "4m 43s ago"
   * </pre>
   *
   * <code>string deployed_ago = 5;</code>
   * @return The deployedAgo.
   */
  java.lang.String getDeployedAgo();
  /**
   * <pre>
   * "4m 43s ago"
   * </pre>
   *
   * <code>string deployed_ago = 5;</code>
   * @return The bytes for deployedAgo.
   */
  com.google.protobuf.ByteString
      getDeployedAgoBytes();

  /**
   * <code>repeated .clarity.v1.Commit commits = 6;</code>
   */
  java.util.List<dev.ezcd.clarity.proto.Commit> 
      getCommitsList();
  /**
   * <code>repeated .clarity.v1.Commit commits = 6;</code>
   */
  dev.ezcd.clarity.proto.Commit getCommits(int index);
  /**
   * <code>repeated .clarity.v1.Commit commits = 6;</code>
   */
  int getCommitsCount();
}
