// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clarity/v1/view.proto

package dev.ezcd.clarity.proto;

/**
 * <pre>
 * LeadAxis is the one x-axis every week in a flow is drawn against.
 * One axis rather than one per row, because per-row scaling would make the
 * rows incomparable and comparing them is the only reason the view exists.
 * </pre>
 *
 * Protobuf type {@code clarity.v1.LeadAxis}
 */
public  final class LeadAxis extends
    com.google.protobuf.GeneratedMessageLite<
        LeadAxis, LeadAxis.Builder> implements
    // @@protoc_insertion_point(message_implements:clarity.v1.LeadAxis)
    LeadAxisOrBuilder {
  private LeadAxis() {
    ticks_ = emptyProtobufList();
  }
  public static final int MAX_SECONDS_FIELD_NUMBER = 1;
  private long maxSeconds_;
  /**
   * <code>int64 max_seconds = 1;</code>
   * @return The maxSeconds.
   */
  @java.lang.Override
  public long getMaxSeconds() {
    return maxSeconds_;
  }
  /**
   * <code>int64 max_seconds = 1;</code>
   * @param value The maxSeconds to set.
   */
  private void setMaxSeconds(long value) {
    
    maxSeconds_ = value;
  }
  /**
   * <code>int64 max_seconds = 1;</code>
   */
  private void clearMaxSeconds() {
    
    maxSeconds_ = 0L;
  }

  public static final int CLAMPED_FIELD_NUMBER = 2;
  private boolean clamped_;
  /**
   * <pre>
   * Clamped reports that some lead time sits beyond the scale, so a client can
   * mark the axis as incomplete rather than clipping in silence.
   * </pre>
   *
   * <code>bool clamped = 2;</code>
   * @return The clamped.
   */
  @java.lang.Override
  public boolean getClamped() {
    return clamped_;
  }
  /**
   * <pre>
   * Clamped reports that some lead time sits beyond the scale, so a client can
   * mark the axis as incomplete rather than clipping in silence.
   * </pre>
   *
   * <code>bool clamped = 2;</code>
   * @param value The clamped to set.
   */
  private void setClamped(boolean value) {
    
    clamped_ = value;
  }
  /**
   * <pre>
   * Clamped reports that some lead time sits beyond the scale, so a client can
   * mark the axis as incomplete rather than clipping in silence.
   * </pre>
   *
   * <code>bool clamped = 2;</code>
   */
  private void clearClamped() {
    
    clamped_ = false;
  }

  public static final int TICKS_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.ProtobufList<dev.ezcd.clarity.proto.AxisTick> ticks_;
  /**
   * <pre>
   * The labels, at the fractions of the axis they belong to. A client draws as
   * many as it has room for and drops the rest — how many fit is geometry, but
   * what a tick is called is not: the format keeps the five fractions distinct,
   * which is why a half hour reads "1.5h" rather than rounding onto its
   * neighbour.
   * </pre>
   *
   * <code>repeated .clarity.v1.AxisTick ticks = 3;</code>
   */
  @java.lang.Override
  public java.util.List<dev.ezcd.clarity.proto.AxisTick> getTicksList() {
    return ticks_;
  }
  /**
   * <pre>
   * The labels, at the fractions of the axis they belong to. A client draws as
   * many as it has room for and drops the rest — how many fit is geometry, but
   * what a tick is called is not: the format keeps the five fractions distinct,
   * which is why a half hour reads "1.5h" rather than rounding onto its
   * neighbour.
   * </pre>
   *
   * <code>repeated .clarity.v1.AxisTick ticks = 3;</code>
   */
  public java.util.List<? extends dev.ezcd.clarity.proto.AxisTickOrBuilder> 
      getTicksOrBuilderList() {
    return ticks_;
  }
  /**
   * <pre>
   * The labels, at the fractions of the axis they belong to. A client draws as
   * many as it has room for and drops the rest — how many fit is geometry, but
   * what a tick is called is not: the format keeps the five fractions distinct,
   * which is why a half hour reads "1.5h" rather than rounding onto its
   * neighbour.
   * </pre>
   *
   * <code>repeated .clarity.v1.AxisTick ticks = 3;</code>
   */
  @java.lang.Override
  public int getTicksCount() {
    return ticks_.size();
  }
  /**
   * <pre>
   * The labels, at the fractions of the axis they belong to. A client draws as
   * many as it has room for and drops the rest — how many fit is geometry, but
   * what a tick is called is not: the format keeps the five fractions distinct,
   * which is why a half hour reads "1.5h" rather than rounding onto its
   * neighbour.
   * </pre>
   *
   * <code>repeated .clarity.v1.AxisTick ticks = 3;</code>
   */
  @java.lang.Override
  public dev.ezcd.clarity.proto.AxisTick getTicks(int index) {
    return ticks_.get(index);
  }
  /**
   * <pre>
   * The labels, at the fractions of the axis they belong to. A client draws as
   * many as it has room for and drops the rest — how many fit is geometry, but
   * what a tick is called is not: the format keeps the five fractions distinct,
   * which is why a half hour reads "1.5h" rather than rounding onto its
   * neighbour.
   * </pre>
   *
   * <code>repeated .clarity.v1.AxisTick ticks = 3;</code>
   */
  public dev.ezcd.clarity.proto.AxisTickOrBuilder getTicksOrBuilder(
      int index) {
    return ticks_.get(index);
  }
  private void ensureTicksIsMutable() {
    com.google.protobuf.Internal.ProtobufList<dev.ezcd.clarity.proto.AxisTick> tmp = ticks_;
    if (!tmp.isModifiable()) {
      ticks_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <pre>
   * The labels, at the fractions of the axis they belong to. A client draws as
   * many as it has room for and drops the rest — how many fit is geometry, but
   * what a tick is called is not: the format keeps the five fractions distinct,
   * which is why a half hour reads "1.5h" rather than rounding onto its
   * neighbour.
   * </pre>
   *
   * <code>repeated .clarity.v1.AxisTick ticks = 3;</code>
   */
  private void setTicks(
      int index, dev.ezcd.clarity.proto.AxisTick value) {
    value.getClass();
  ensureTicksIsMutable();
    ticks_.set(index, value);
  }
  /**
   * <pre>
   * The labels, at the fractions of the axis they belong to. A client draws as
   * many as it has room for and drops the rest — how many fit is geometry, but
   * what a tick is called is not: the format keeps the five fractions distinct,
   * which is why a half hour reads "1.5h" rather than rounding onto its
   * neighbour.
   * </pre>
   *
   * <code>repeated .clarity.v1.AxisTick ticks = 3;</code>
   */
  private void addTicks(dev.ezcd.clarity.proto.AxisTick value) {
    value.getClass();
  ensureTicksIsMutable();
    ticks_.add(value);
  }
  /**
   * <pre>
   * The labels, at the fractions of the axis they belong to. A client draws as
   * many as it has room for and drops the rest — how many fit is geometry, but
   * what a tick is called is not: the format keeps the five fractions distinct,
   * which is why a half hour reads "1.5h" rather than rounding onto its
   * neighbour.
   * </pre>
   *
   * <code>repeated .clarity.v1.AxisTick ticks = 3;</code>
   */
  private void addTicks(
      int index, dev.ezcd.clarity.proto.AxisTick value) {
    value.getClass();
  ensureTicksIsMutable();
    ticks_.add(index, value);
  }
  /**
   * <pre>
   * The labels, at the fractions of the axis they belong to. A client draws as
   * many as it has room for and drops the rest — how many fit is geometry, but
   * what a tick is called is not: the format keeps the five fractions distinct,
   * which is why a half hour reads "1.5h" rather than rounding onto its
   * neighbour.
   * </pre>
   *
   * <code>repeated .clarity.v1.AxisTick ticks = 3;</code>
   */
  private void addAllTicks(
      java.lang.Iterable<? extends dev.ezcd.clarity.proto.AxisTick> values) {
    ensureTicksIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, ticks_);
  }
  /**
   * <pre>
   * The labels, at the fractions of the axis they belong to. A client draws as
   * many as it has room for and drops the rest — how many fit is geometry, but
   * what a tick is called is not: the format keeps the five fractions distinct,
   * which is why a half hour reads "1.5h" rather than rounding onto its
   * neighbour.
   * </pre>
   *
   * <code>repeated .clarity.v1.AxisTick ticks = 3;</code>
   */
  private void clearTicks() {
    ticks_ = emptyProtobufList();
  }
  /**
   * <pre>
   * The labels, at the fractions of the axis they belong to. A client draws as
   * many as it has room for and drops the rest — how many fit is geometry, but
   * what a tick is called is not: the format keeps the five fractions distinct,
   * which is why a half hour reads "1.5h" rather than rounding onto its
   * neighbour.
   * </pre>
   *
   * <code>repeated .clarity.v1.AxisTick ticks = 3;</code>
   */
  private void removeTicks(int index) {
    ensureTicksIsMutable();
    ticks_.remove(index);
  }

  public static dev.ezcd.clarity.proto.LeadAxis parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.LeadAxis parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.LeadAxis parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.LeadAxis parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.LeadAxis parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.LeadAxis parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.LeadAxis parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.LeadAxis parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.LeadAxis parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.LeadAxis parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.LeadAxis parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.LeadAxis parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(dev.ezcd.clarity.proto.LeadAxis prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * LeadAxis is the one x-axis every week in a flow is drawn against.
   * One axis rather than one per row, because per-row scaling would make the
   * rows incomparable and comparing them is the only reason the view exists.
   * </pre>
   *
   * Protobuf type {@code clarity.v1.LeadAxis}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        dev.ezcd.clarity.proto.LeadAxis, Builder> implements
      // @@protoc_insertion_point(builder_implements:clarity.v1.LeadAxis)
      dev.ezcd.clarity.proto.LeadAxisOrBuilder {
    // Construct using dev.ezcd.clarity.proto.LeadAxis.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>int64 max_seconds = 1;</code>
     * @return The maxSeconds.
     */
    @java.lang.Override
    public long getMaxSeconds() {
      return instance.getMaxSeconds();
    }
    /**
     * <code>int64 max_seconds = 1;</code>
     * @param value The maxSeconds to set.
     * @return This builder for chaining.
     */
    public Builder setMaxSeconds(long value) {
      copyOnWrite();
      instance.setMaxSeconds(value);
      return this;
    }
    /**
     * <code>int64 max_seconds = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxSeconds() {
      copyOnWrite();
      instance.clearMaxSeconds();
      return this;
    }

    /**
     * <pre>
     * Clamped reports that some lead time sits beyond the scale, so a client can
     * mark the axis as incomplete rather than clipping in silence.
     * </pre>
     *
     * <code>bool clamped = 2;</code>
     * @return The clamped.
     */
    @java.lang.Override
    public boolean getClamped() {
      return instance.getClamped();
    }
    /**
     * <pre>
     * Clamped reports that some lead time sits beyond the scale, so a client can
     * mark the axis as incomplete rather than clipping in silence.
     * </pre>
     *
     * <code>bool clamped = 2;</code>
     * @param value The clamped to set.
     * @return This builder for chaining.
     */
    public Builder setClamped(boolean value) {
      copyOnWrite();
      instance.setClamped(value);
      return this;
    }
    /**
     * <pre>
     * Clamped reports that some lead time sits beyond the scale, so a client can
     * mark the axis as incomplete rather than clipping in silence.
     * </pre>
     *
     * <code>bool clamped = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearClamped() {
      copyOnWrite();
      instance.clearClamped();
      return this;
    }

    /**
     * <pre>
     * The labels, at the fractions of the axis they belong to. A client draws as
     * many as it has room for and drops the rest — how many fit is geometry, but
     * what a tick is called is not: the format keeps the five fractions distinct,
     * which is why a half hour reads "1.5h" rather than rounding onto its
     * neighbour.
     * </pre>
     *
     * <code>repeated .clarity.v1.AxisTick ticks = 3;</code>
     */
    @java.lang.Override
    public java.util.List<dev.ezcd.clarity.proto.AxisTick> getTicksList() {
      return java.util.Collections.unmodifiableList(
          instance.getTicksList());
    }
    /**
     * <pre>
     * The labels, at the fractions of the axis they belong to. A client draws as
     * many as it has room for and drops the rest — how many fit is geometry, but
     * what a tick is called is not: the format keeps the five fractions distinct,
     * which is why a half hour reads "1.5h" rather than rounding onto its
     * neighbour.
     * </pre>
     *
     * <code>repeated .clarity.v1.AxisTick ticks = 3;</code>
     */
    @java.lang.Override
    public int getTicksCount() {
      return instance.getTicksCount();
    }/**
     * <pre>
     * The labels, at the fractions of the axis they belong to. A client draws as
     * many as it has room for and drops the rest — how many fit is geometry, but
     * what a tick is called is not: the format keeps the five fractions distinct,
     * which is why a half hour reads "1.5h" rather than rounding onto its
     * neighbour.
     * </pre>
     *
     * <code>repeated .clarity.v1.AxisTick ticks = 3;</code>
     */
    @java.lang.Override
    public dev.ezcd.clarity.proto.AxisTick getTicks(int index) {
      return instance.getTicks(index);
    }
    /**
     * <pre>
     * The labels, at the fractions of the axis they belong to. A client draws as
     * many as it has room for and drops the rest — how many fit is geometry, but
     * what a tick is called is not: the format keeps the five fractions distinct,
     * which is why a half hour reads "1.5h" rather than rounding onto its
     * neighbour.
     * </pre>
     *
     * <code>repeated .clarity.v1.AxisTick ticks = 3;</code>
     */
    public Builder setTicks(
        int index, dev.ezcd.clarity.proto.AxisTick value) {
      copyOnWrite();
      instance.setTicks(index, value);
      return this;
    }
    /**
     * <pre>
     * The labels, at the fractions of the axis they belong to. A client draws as
     * many as it has room for and drops the rest — how many fit is geometry, but
     * what a tick is called is not: the format keeps the five fractions distinct,
     * which is why a half hour reads "1.5h" rather than rounding onto its
     * neighbour.
     * </pre>
     *
     * <code>repeated .clarity.v1.AxisTick ticks = 3;</code>
     */
    public Builder setTicks(
        int index, dev.ezcd.clarity.proto.AxisTick.Builder builderForValue) {
      copyOnWrite();
      instance.setTicks(index,
          builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * The labels, at the fractions of the axis they belong to. A client draws as
     * many as it has room for and drops the rest — how many fit is geometry, but
     * what a tick is called is not: the format keeps the five fractions distinct,
     * which is why a half hour reads "1.5h" rather than rounding onto its
     * neighbour.
     * </pre>
     *
     * <code>repeated .clarity.v1.AxisTick ticks = 3;</code>
     */
    public Builder addTicks(dev.ezcd.clarity.proto.AxisTick value) {
      copyOnWrite();
      instance.addTicks(value);
      return this;
    }
    /**
     * <pre>
     * The labels, at the fractions of the axis they belong to. A client draws as
     * many as it has room for and drops the rest — how many fit is geometry, but
     * what a tick is called is not: the format keeps the five fractions distinct,
     * which is why a half hour reads "1.5h" rather than rounding onto its
     * neighbour.
     * </pre>
     *
     * <code>repeated .clarity.v1.AxisTick ticks = 3;</code>
     */
    public Builder addTicks(
        int index, dev.ezcd.clarity.proto.AxisTick value) {
      copyOnWrite();
      instance.addTicks(index, value);
      return this;
    }
    /**
     * <pre>
     * The labels, at the fractions of the axis they belong to. A client draws as
     * many as it has room for and drops the rest — how many fit is geometry, but
     * what a tick is called is not: the format keeps the five fractions distinct,
     * which is why a half hour reads "1.5h" rather than rounding onto its
     * neighbour.
     * </pre>
     *
     * <code>repeated .clarity.v1.AxisTick ticks = 3;</code>
     */
    public Builder addTicks(
        dev.ezcd.clarity.proto.AxisTick.Builder builderForValue) {
      copyOnWrite();
      instance.addTicks(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * The labels, at the fractions of the axis they belong to. A client draws as
     * many as it has room for and drops the rest — how many fit is geometry, but
     * what a tick is called is not: the format keeps the five fractions distinct,
     * which is why a half hour reads "1.5h" rather than rounding onto its
     * neighbour.
     * </pre>
     *
     * <code>repeated .clarity.v1.AxisTick ticks = 3;</code>
     */
    public Builder addTicks(
        int index, dev.ezcd.clarity.proto.AxisTick.Builder builderForValue) {
      copyOnWrite();
      instance.addTicks(index,
          builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * The labels, at the fractions of the axis they belong to. A client draws as
     * many as it has room for and drops the rest — how many fit is geometry, but
     * what a tick is called is not: the format keeps the five fractions distinct,
     * which is why a half hour reads "1.5h" rather than rounding onto its
     * neighbour.
     * </pre>
     *
     * <code>repeated .clarity.v1.AxisTick ticks = 3;</code>
     */
    public Builder addAllTicks(
        java.lang.Iterable<? extends dev.ezcd.clarity.proto.AxisTick> values) {
      copyOnWrite();
      instance.addAllTicks(values);
      return this;
    }
    /**
     * <pre>
     * The labels, at the fractions of the axis they belong to. A client draws as
     * many as it has room for and drops the rest — how many fit is geometry, but
     * what a tick is called is not: the format keeps the five fractions distinct,
     * which is why a half hour reads "1.5h" rather than rounding onto its
     * neighbour.
     * </pre>
     *
     * <code>repeated .clarity.v1.AxisTick ticks = 3;</code>
     */
    public Builder clearTicks() {
      copyOnWrite();
      instance.clearTicks();
      return this;
    }
    /**
     * <pre>
     * The labels, at the fractions of the axis they belong to. A client draws as
     * many as it has room for and drops the rest — how many fit is geometry, but
     * what a tick is called is not: the format keeps the five fractions distinct,
     * which is why a half hour reads "1.5h" rather than rounding onto its
     * neighbour.
     * </pre>
     *
     * <code>repeated .clarity.v1.AxisTick ticks = 3;</code>
     */
    public Builder removeTicks(int index) {
      copyOnWrite();
      instance.removeTicks(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:clarity.v1.LeadAxis)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new dev.ezcd.clarity.proto.LeadAxis();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "maxSeconds_",
            "clamped_",
            "ticks_",
            dev.ezcd.clarity.proto.AxisTick.class,
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0001\u0000\u0001\u0002\u0002\u0007" +
              "\u0003\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<dev.ezcd.clarity.proto.LeadAxis> parser = PARSER;
        if (parser == null) {
          synchronized (dev.ezcd.clarity.proto.LeadAxis.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<dev.ezcd.clarity.proto.LeadAxis>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:clarity.v1.LeadAxis)
  private static final dev.ezcd.clarity.proto.LeadAxis DEFAULT_INSTANCE;
  static {
    LeadAxis defaultInstance = new LeadAxis();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      LeadAxis.class, defaultInstance);
  }

  public static dev.ezcd.clarity.proto.LeadAxis getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<LeadAxis> PARSER;

  public static com.google.protobuf.Parser<LeadAxis> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

