// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clarity/v1/view.proto

package dev.ezcd.clarity.proto;

/**
 * <pre>
 * MetricsFlow is one deploy target's weeks, newest first.
 * </pre>
 *
 * Protobuf type {@code clarity.v1.MetricsFlow}
 */
public  final class MetricsFlow extends
    com.google.protobuf.GeneratedMessageLite<
        MetricsFlow, MetricsFlow.Builder> implements
    // @@protoc_insertion_point(message_implements:clarity.v1.MetricsFlow)
    MetricsFlowOrBuilder {
  private MetricsFlow() {
    name_ = "";
    weeks_ = emptyProtobufList();
  }
  public static final int NAME_FIELD_NUMBER = 1;
  private java.lang.String name_;
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    return name_;
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(name_);
  }
  /**
   * <code>string name = 1;</code>
   * @param value The name to set.
   */
  private void setName(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    name_ = value;
  }
  /**
   * <code>string name = 1;</code>
   */
  private void clearName() {
    
    name_ = getDefaultInstance().getName();
  }
  /**
   * <code>string name = 1;</code>
   * @param value The bytes for name to set.
   */
  private void setNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    name_ = value.toStringUtf8();
    
  }

  public static final int UNDECLARED_FIELD_NUMBER = 2;
  private boolean undeclared_;
  /**
   * <code>bool undeclared = 2;</code>
   * @return The undeclared.
   */
  @java.lang.Override
  public boolean getUndeclared() {
    return undeclared_;
  }
  /**
   * <code>bool undeclared = 2;</code>
   * @param value The undeclared to set.
   */
  private void setUndeclared(boolean value) {
    
    undeclared_ = value;
  }
  /**
   * <code>bool undeclared = 2;</code>
   */
  private void clearUndeclared() {
    
    undeclared_ = false;
  }

  public static final int AXIS_FIELD_NUMBER = 3;
  private dev.ezcd.clarity.proto.LeadAxis axis_;
  /**
   * <code>.clarity.v1.LeadAxis axis = 3;</code>
   */
  @java.lang.Override
  public boolean hasAxis() {
    return axis_ != null;
  }
  /**
   * <code>.clarity.v1.LeadAxis axis = 3;</code>
   */
  @java.lang.Override
  public dev.ezcd.clarity.proto.LeadAxis getAxis() {
    return axis_ == null ? dev.ezcd.clarity.proto.LeadAxis.getDefaultInstance() : axis_;
  }
  /**
   * <code>.clarity.v1.LeadAxis axis = 3;</code>
   */
  private void setAxis(dev.ezcd.clarity.proto.LeadAxis value) {
    value.getClass();
  axis_ = value;
    
    }
  /**
   * <code>.clarity.v1.LeadAxis axis = 3;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeAxis(dev.ezcd.clarity.proto.LeadAxis value) {
    value.getClass();
  if (axis_ != null &&
        axis_ != dev.ezcd.clarity.proto.LeadAxis.getDefaultInstance()) {
      axis_ =
        dev.ezcd.clarity.proto.LeadAxis.newBuilder(axis_).mergeFrom(value).buildPartial();
    } else {
      axis_ = value;
    }
    
  }
  /**
   * <code>.clarity.v1.LeadAxis axis = 3;</code>
   */
  private void clearAxis() {  axis_ = null;
    
  }

  public static final int MAX_DEPLOYS_FIELD_NUMBER = 4;
  private int maxDeploys_;
  /**
   * <pre>
   * The busiest week on show, which is what every deploy bar is drawn
   * relative to. A decision rather than geometry: bars could be scaled
   * against a fixed ceiling or against the repository's all-time best, and
   * "the busiest week you can see" is the one that makes the rows on screen
   * comparable to each other.
   * </pre>
   *
   * <code>int32 max_deploys = 4;</code>
   * @return The maxDeploys.
   */
  @java.lang.Override
  public int getMaxDeploys() {
    return maxDeploys_;
  }
  /**
   * <pre>
   * The busiest week on show, which is what every deploy bar is drawn
   * relative to. A decision rather than geometry: bars could be scaled
   * against a fixed ceiling or against the repository's all-time best, and
   * "the busiest week you can see" is the one that makes the rows on screen
   * comparable to each other.
   * </pre>
   *
   * <code>int32 max_deploys = 4;</code>
   * @param value The maxDeploys to set.
   */
  private void setMaxDeploys(int value) {
    
    maxDeploys_ = value;
  }
  /**
   * <pre>
   * The busiest week on show, which is what every deploy bar is drawn
   * relative to. A decision rather than geometry: bars could be scaled
   * against a fixed ceiling or against the repository's all-time best, and
   * "the busiest week you can see" is the one that makes the rows on screen
   * comparable to each other.
   * </pre>
   *
   * <code>int32 max_deploys = 4;</code>
   */
  private void clearMaxDeploys() {
    
    maxDeploys_ = 0;
  }

  public static final int WEEKS_FIELD_NUMBER = 5;
  private com.google.protobuf.Internal.ProtobufList<dev.ezcd.clarity.proto.Week> weeks_;
  /**
   * <code>repeated .clarity.v1.Week weeks = 5;</code>
   */
  @java.lang.Override
  public java.util.List<dev.ezcd.clarity.proto.Week> getWeeksList() {
    return weeks_;
  }
  /**
   * <code>repeated .clarity.v1.Week weeks = 5;</code>
   */
  public java.util.List<? extends dev.ezcd.clarity.proto.WeekOrBuilder> 
      getWeeksOrBuilderList() {
    return weeks_;
  }
  /**
   * <code>repeated .clarity.v1.Week weeks = 5;</code>
   */
  @java.lang.Override
  public int getWeeksCount() {
    return weeks_.size();
  }
  /**
   * <code>repeated .clarity.v1.Week weeks = 5;</code>
   */
  @java.lang.Override
  public dev.ezcd.clarity.proto.Week getWeeks(int index) {
    return weeks_.get(index);
  }
  /**
   * <code>repeated .clarity.v1.Week weeks = 5;</code>
   */
  public dev.ezcd.clarity.proto.WeekOrBuilder getWeeksOrBuilder(
      int index) {
    return weeks_.get(index);
  }
  private void ensureWeeksIsMutable() {
    com.google.protobuf.Internal.ProtobufList<dev.ezcd.clarity.proto.Week> tmp = weeks_;
    if (!tmp.isModifiable()) {
      weeks_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .clarity.v1.Week weeks = 5;</code>
   */
  private void setWeeks(
      int index, dev.ezcd.clarity.proto.Week value) {
    value.getClass();
  ensureWeeksIsMutable();
    weeks_.set(index, value);
  }
  /**
   * <code>repeated .clarity.v1.Week weeks = 5;</code>
   */
  private void addWeeks(dev.ezcd.clarity.proto.Week value) {
    value.getClass();
  ensureWeeksIsMutable();
    weeks_.add(value);
  }
  /**
   * <code>repeated .clarity.v1.Week weeks = 5;</code>
   */
  private void addWeeks(
      int index, dev.ezcd.clarity.proto.Week value) {
    value.getClass();
  ensureWeeksIsMutable();
    weeks_.add(index, value);
  }
  /**
   * <code>repeated .clarity.v1.Week weeks = 5;</code>
   */
  private void addAllWeeks(
      java.lang.Iterable<? extends dev.ezcd.clarity.proto.Week> values) {
    ensureWeeksIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, weeks_);
  }
  /**
   * <code>repeated .clarity.v1.Week weeks = 5;</code>
   */
  private void clearWeeks() {
    weeks_ = emptyProtobufList();
  }
  /**
   * <code>repeated .clarity.v1.Week weeks = 5;</code>
   */
  private void removeWeeks(int index) {
    ensureWeeksIsMutable();
    weeks_.remove(index);
  }

  public static dev.ezcd.clarity.proto.MetricsFlow parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.MetricsFlow parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.MetricsFlow parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.MetricsFlow parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.MetricsFlow parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.MetricsFlow parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.MetricsFlow parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.MetricsFlow parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.MetricsFlow parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.MetricsFlow parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.MetricsFlow parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.MetricsFlow parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(dev.ezcd.clarity.proto.MetricsFlow prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * MetricsFlow is one deploy target's weeks, newest first.
   * </pre>
   *
   * Protobuf type {@code clarity.v1.MetricsFlow}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        dev.ezcd.clarity.proto.MetricsFlow, Builder> implements
      // @@protoc_insertion_point(builder_implements:clarity.v1.MetricsFlow)
      dev.ezcd.clarity.proto.MetricsFlowOrBuilder {
    // Construct using dev.ezcd.clarity.proto.MetricsFlow.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      return instance.getName();
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return instance.getNameBytes();
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      copyOnWrite();
      instance.setName(value);
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      copyOnWrite();
      instance.clearName();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameBytes(value);
      return this;
    }

    /**
     * <code>bool undeclared = 2;</code>
     * @return The undeclared.
     */
    @java.lang.Override
    public boolean getUndeclared() {
      return instance.getUndeclared();
    }
    /**
     * <code>bool undeclared = 2;</code>
     * @param value The undeclared to set.
     * @return This builder for chaining.
     */
    public Builder setUndeclared(boolean value) {
      copyOnWrite();
      instance.setUndeclared(value);
      return this;
    }
    /**
     * <code>bool undeclared = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUndeclared() {
      copyOnWrite();
      instance.clearUndeclared();
      return this;
    }

    /**
     * <code>.clarity.v1.LeadAxis axis = 3;</code>
     */
    @java.lang.Override
    public boolean hasAxis() {
      return instance.hasAxis();
    }
    /**
     * <code>.clarity.v1.LeadAxis axis = 3;</code>
     */
    @java.lang.Override
    public dev.ezcd.clarity.proto.LeadAxis getAxis() {
      return instance.getAxis();
    }
    /**
     * <code>.clarity.v1.LeadAxis axis = 3;</code>
     */
    public Builder setAxis(dev.ezcd.clarity.proto.LeadAxis value) {
      copyOnWrite();
      instance.setAxis(value);
      return this;
      }
    /**
     * <code>.clarity.v1.LeadAxis axis = 3;</code>
     */
    public Builder setAxis(
        dev.ezcd.clarity.proto.LeadAxis.Builder builderForValue) {
      copyOnWrite();
      instance.setAxis(builderForValue.build());
      return this;
    }
    /**
     * <code>.clarity.v1.LeadAxis axis = 3;</code>
     */
    public Builder mergeAxis(dev.ezcd.clarity.proto.LeadAxis value) {
      copyOnWrite();
      instance.mergeAxis(value);
      return this;
    }
    /**
     * <code>.clarity.v1.LeadAxis axis = 3;</code>
     */
    public Builder clearAxis() {  copyOnWrite();
      instance.clearAxis();
      return this;
    }

    /**
     * <pre>
     * The busiest week on show, which is what every deploy bar is drawn
     * relative to. A decision rather than geometry: bars could be scaled
     * against a fixed ceiling or against the repository's all-time best, and
     * "the busiest week you can see" is the one that makes the rows on screen
     * comparable to each other.
     * </pre>
     *
     * <code>int32 max_deploys = 4;</code>
     * @return The maxDeploys.
     */
    @java.lang.Override
    public int getMaxDeploys() {
      return instance.getMaxDeploys();
    }
    /**
     * <pre>
     * The busiest week on show, which is what every deploy bar is drawn
     * relative to. A decision rather than geometry: bars could be scaled
     * against a fixed ceiling or against the repository's all-time best, and
     * "the busiest week you can see" is the one that makes the rows on screen
     * comparable to each other.
     * </pre>
     *
     * <code>int32 max_deploys = 4;</code>
     * @param value The maxDeploys to set.
     * @return This builder for chaining.
     */
    public Builder setMaxDeploys(int value) {
      copyOnWrite();
      instance.setMaxDeploys(value);
      return this;
    }
    /**
     * <pre>
     * The busiest week on show, which is what every deploy bar is drawn
     * relative to. A decision rather than geometry: bars could be scaled
     * against a fixed ceiling or against the repository's all-time best, and
     * "the busiest week you can see" is the one that makes the rows on screen
     * comparable to each other.
     * </pre>
     *
     * <code>int32 max_deploys = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxDeploys() {
      copyOnWrite();
      instance.clearMaxDeploys();
      return this;
    }

    /**
     * <code>repeated .clarity.v1.Week weeks = 5;</code>
     */
    @java.lang.Override
    public java.util.List<dev.ezcd.clarity.proto.Week> getWeeksList() {
      return java.util.Collections.unmodifiableList(
          instance.getWeeksList());
    }
    /**
     * <code>repeated .clarity.v1.Week weeks = 5;</code>
     */
    @java.lang.Override
    public int getWeeksCount() {
      return instance.getWeeksCount();
    }/**
     * <code>repeated .clarity.v1.Week weeks = 5;</code>
     */
    @java.lang.Override
    public dev.ezcd.clarity.proto.Week getWeeks(int index) {
      return instance.getWeeks(index);
    }
    /**
     * <code>repeated .clarity.v1.Week weeks = 5;</code>
     */
    public Builder setWeeks(
        int index, dev.ezcd.clarity.proto.Week value) {
      copyOnWrite();
      instance.setWeeks(index, value);
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Week weeks = 5;</code>
     */
    public Builder setWeeks(
        int index, dev.ezcd.clarity.proto.Week.Builder builderForValue) {
      copyOnWrite();
      instance.setWeeks(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Week weeks = 5;</code>
     */
    public Builder addWeeks(dev.ezcd.clarity.proto.Week value) {
      copyOnWrite();
      instance.addWeeks(value);
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Week weeks = 5;</code>
     */
    public Builder addWeeks(
        int index, dev.ezcd.clarity.proto.Week value) {
      copyOnWrite();
      instance.addWeeks(index, value);
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Week weeks = 5;</code>
     */
    public Builder addWeeks(
        dev.ezcd.clarity.proto.Week.Builder builderForValue) {
      copyOnWrite();
      instance.addWeeks(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Week weeks = 5;</code>
     */
    public Builder addWeeks(
        int index, dev.ezcd.clarity.proto.Week.Builder builderForValue) {
      copyOnWrite();
      instance.addWeeks(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Week weeks = 5;</code>
     */
    public Builder addAllWeeks(
        java.lang.Iterable<? extends dev.ezcd.clarity.proto.Week> values) {
      copyOnWrite();
      instance.addAllWeeks(values);
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Week weeks = 5;</code>
     */
    public Builder clearWeeks() {
      copyOnWrite();
      instance.clearWeeks();
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Week weeks = 5;</code>
     */
    public Builder removeWeeks(int index) {
      copyOnWrite();
      instance.removeWeeks(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:clarity.v1.MetricsFlow)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new dev.ezcd.clarity.proto.MetricsFlow();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "name_",
            "undeclared_",
            "axis_",
            "maxDeploys_",
            "weeks_",
            dev.ezcd.clarity.proto.Week.class,
          };
          java.lang.String info =
              "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0000\u0001\u0000\u0001\u0208\u0002\u0007" +
              "\u0003\t\u0004\u0004\u0005\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<dev.ezcd.clarity.proto.MetricsFlow> parser = PARSER;
        if (parser == null) {
          synchronized (dev.ezcd.clarity.proto.MetricsFlow.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<dev.ezcd.clarity.proto.MetricsFlow>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:clarity.v1.MetricsFlow)
  private static final dev.ezcd.clarity.proto.MetricsFlow DEFAULT_INSTANCE;
  static {
    MetricsFlow defaultInstance = new MetricsFlow();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      MetricsFlow.class, defaultInstance);
  }

  public static dev.ezcd.clarity.proto.MetricsFlow getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<MetricsFlow> PARSER;

  public static com.google.protobuf.Parser<MetricsFlow> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

