// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clarity/v1/view.proto

package dev.ezcd.clarity.proto;

/**
 * <pre>
 * Metrics is the weekly aggregates view — the phone's counterpart of
 * `git clarity metrics`.
 * A separate message and a separate read from View, for the reason that
 * command gives for never polling: `git clarity` answers "is main green right
 * now?", this answers "are we getting better?", and trend is a question about
 * history rather than about the last few seconds. It is also read over a much
 * larger commit window, which no five-second refresh should be carrying.
 * The split of labour is the same as everywhere else here. What crosses is the
 * numbers and the words: the quantiles, the counts, the shared axis, the tick
 * labels. What does not is how wide a box is in pixels, how many ticks fit, or
 * which columns a bar occupies — the terminal's answers to those exist only
 * because it quantises to character cells, and none of them mean anything at
 * pixel resolution.
 * </pre>
 *
 * Protobuf type {@code clarity.v1.Metrics}
 */
public  final class Metrics extends
    com.google.protobuf.GeneratedMessageLite<
        Metrics, Metrics.Builder> implements
    // @@protoc_insertion_point(message_implements:clarity.v1.Metrics)
    MetricsOrBuilder {
  private Metrics() {
    flows_ = emptyProtobufList();
  }
  public static final int FLOWS_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<dev.ezcd.clarity.proto.MetricsFlow> flows_;
  /**
   * <code>repeated .clarity.v1.MetricsFlow flows = 1;</code>
   */
  @java.lang.Override
  public java.util.List<dev.ezcd.clarity.proto.MetricsFlow> getFlowsList() {
    return flows_;
  }
  /**
   * <code>repeated .clarity.v1.MetricsFlow flows = 1;</code>
   */
  public java.util.List<? extends dev.ezcd.clarity.proto.MetricsFlowOrBuilder> 
      getFlowsOrBuilderList() {
    return flows_;
  }
  /**
   * <code>repeated .clarity.v1.MetricsFlow flows = 1;</code>
   */
  @java.lang.Override
  public int getFlowsCount() {
    return flows_.size();
  }
  /**
   * <code>repeated .clarity.v1.MetricsFlow flows = 1;</code>
   */
  @java.lang.Override
  public dev.ezcd.clarity.proto.MetricsFlow getFlows(int index) {
    return flows_.get(index);
  }
  /**
   * <code>repeated .clarity.v1.MetricsFlow flows = 1;</code>
   */
  public dev.ezcd.clarity.proto.MetricsFlowOrBuilder getFlowsOrBuilder(
      int index) {
    return flows_.get(index);
  }
  private void ensureFlowsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<dev.ezcd.clarity.proto.MetricsFlow> tmp = flows_;
    if (!tmp.isModifiable()) {
      flows_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .clarity.v1.MetricsFlow flows = 1;</code>
   */
  private void setFlows(
      int index, dev.ezcd.clarity.proto.MetricsFlow value) {
    value.getClass();
  ensureFlowsIsMutable();
    flows_.set(index, value);
  }
  /**
   * <code>repeated .clarity.v1.MetricsFlow flows = 1;</code>
   */
  private void addFlows(dev.ezcd.clarity.proto.MetricsFlow value) {
    value.getClass();
  ensureFlowsIsMutable();
    flows_.add(value);
  }
  /**
   * <code>repeated .clarity.v1.MetricsFlow flows = 1;</code>
   */
  private void addFlows(
      int index, dev.ezcd.clarity.proto.MetricsFlow value) {
    value.getClass();
  ensureFlowsIsMutable();
    flows_.add(index, value);
  }
  /**
   * <code>repeated .clarity.v1.MetricsFlow flows = 1;</code>
   */
  private void addAllFlows(
      java.lang.Iterable<? extends dev.ezcd.clarity.proto.MetricsFlow> values) {
    ensureFlowsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, flows_);
  }
  /**
   * <code>repeated .clarity.v1.MetricsFlow flows = 1;</code>
   */
  private void clearFlows() {
    flows_ = emptyProtobufList();
  }
  /**
   * <code>repeated .clarity.v1.MetricsFlow flows = 1;</code>
   */
  private void removeFlows(int index) {
    ensureFlowsIsMutable();
    flows_.remove(index);
  }

  public static final int TRUNCATED_FIELD_NUMBER = 2;
  private boolean truncated_;
  /**
   * <pre>
   * Truncated reports that the commit window, rather than the repository's
   * age, is what ended the history — so an aggregate built from it is not the
   * whole story. Worth more here than in a commit list: a reader can see the
   * bottom of a scroll, but nothing on a chart says it is short a few deploys.
   * </pre>
   *
   * <code>bool truncated = 2;</code>
   * @return The truncated.
   */
  @java.lang.Override
  public boolean getTruncated() {
    return truncated_;
  }
  /**
   * <pre>
   * Truncated reports that the commit window, rather than the repository's
   * age, is what ended the history — so an aggregate built from it is not the
   * whole story. Worth more here than in a commit list: a reader can see the
   * bottom of a scroll, but nothing on a chart says it is short a few deploys.
   * </pre>
   *
   * <code>bool truncated = 2;</code>
   * @param value The truncated to set.
   */
  private void setTruncated(boolean value) {
    
    truncated_ = value;
  }
  /**
   * <pre>
   * Truncated reports that the commit window, rather than the repository's
   * age, is what ended the history — so an aggregate built from it is not the
   * whole story. Worth more here than in a commit list: a reader can see the
   * bottom of a scroll, but nothing on a chart says it is short a few deploys.
   * </pre>
   *
   * <code>bool truncated = 2;</code>
   */
  private void clearTruncated() {
    
    truncated_ = false;
  }

  public static final int LIMIT_FIELD_NUMBER = 3;
  private int limit_;
  /**
   * <code>int32 limit = 3;</code>
   * @return The limit.
   */
  @java.lang.Override
  public int getLimit() {
    return limit_;
  }
  /**
   * <code>int32 limit = 3;</code>
   * @param value The limit to set.
   */
  private void setLimit(int value) {
    
    limit_ = value;
  }
  /**
   * <code>int32 limit = 3;</code>
   */
  private void clearLimit() {
    
    limit_ = 0;
  }

  public static final int GENERATED_UNIX_SECONDS_FIELD_NUMBER = 4;
  private long generatedUnixSeconds_;
  /**
   * <pre>
   * Always set, for the reason View.generated_unix_seconds explains.
   * </pre>
   *
   * <code>int64 generated_unix_seconds = 4;</code>
   * @return The generatedUnixSeconds.
   */
  @java.lang.Override
  public long getGeneratedUnixSeconds() {
    return generatedUnixSeconds_;
  }
  /**
   * <pre>
   * Always set, for the reason View.generated_unix_seconds explains.
   * </pre>
   *
   * <code>int64 generated_unix_seconds = 4;</code>
   * @param value The generatedUnixSeconds to set.
   */
  private void setGeneratedUnixSeconds(long value) {
    
    generatedUnixSeconds_ = value;
  }
  /**
   * <pre>
   * Always set, for the reason View.generated_unix_seconds explains.
   * </pre>
   *
   * <code>int64 generated_unix_seconds = 4;</code>
   */
  private void clearGeneratedUnixSeconds() {
    
    generatedUnixSeconds_ = 0L;
  }

  public static dev.ezcd.clarity.proto.Metrics parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.Metrics parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.Metrics parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.Metrics parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.Metrics parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.Metrics parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.Metrics parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.Metrics parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.Metrics parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.Metrics parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.Metrics parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.Metrics parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(dev.ezcd.clarity.proto.Metrics prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Metrics is the weekly aggregates view — the phone's counterpart of
   * `git clarity metrics`.
   * A separate message and a separate read from View, for the reason that
   * command gives for never polling: `git clarity` answers "is main green right
   * now?", this answers "are we getting better?", and trend is a question about
   * history rather than about the last few seconds. It is also read over a much
   * larger commit window, which no five-second refresh should be carrying.
   * The split of labour is the same as everywhere else here. What crosses is the
   * numbers and the words: the quantiles, the counts, the shared axis, the tick
   * labels. What does not is how wide a box is in pixels, how many ticks fit, or
   * which columns a bar occupies — the terminal's answers to those exist only
   * because it quantises to character cells, and none of them mean anything at
   * pixel resolution.
   * </pre>
   *
   * Protobuf type {@code clarity.v1.Metrics}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        dev.ezcd.clarity.proto.Metrics, Builder> implements
      // @@protoc_insertion_point(builder_implements:clarity.v1.Metrics)
      dev.ezcd.clarity.proto.MetricsOrBuilder {
    // Construct using dev.ezcd.clarity.proto.Metrics.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .clarity.v1.MetricsFlow flows = 1;</code>
     */
    @java.lang.Override
    public java.util.List<dev.ezcd.clarity.proto.MetricsFlow> getFlowsList() {
      return java.util.Collections.unmodifiableList(
          instance.getFlowsList());
    }
    /**
     * <code>repeated .clarity.v1.MetricsFlow flows = 1;</code>
     */
    @java.lang.Override
    public int getFlowsCount() {
      return instance.getFlowsCount();
    }/**
     * <code>repeated .clarity.v1.MetricsFlow flows = 1;</code>
     */
    @java.lang.Override
    public dev.ezcd.clarity.proto.MetricsFlow getFlows(int index) {
      return instance.getFlows(index);
    }
    /**
     * <code>repeated .clarity.v1.MetricsFlow flows = 1;</code>
     */
    public Builder setFlows(
        int index, dev.ezcd.clarity.proto.MetricsFlow value) {
      copyOnWrite();
      instance.setFlows(index, value);
      return this;
    }
    /**
     * <code>repeated .clarity.v1.MetricsFlow flows = 1;</code>
     */
    public Builder setFlows(
        int index, dev.ezcd.clarity.proto.MetricsFlow.Builder builderForValue) {
      copyOnWrite();
      instance.setFlows(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .clarity.v1.MetricsFlow flows = 1;</code>
     */
    public Builder addFlows(dev.ezcd.clarity.proto.MetricsFlow value) {
      copyOnWrite();
      instance.addFlows(value);
      return this;
    }
    /**
     * <code>repeated .clarity.v1.MetricsFlow flows = 1;</code>
     */
    public Builder addFlows(
        int index, dev.ezcd.clarity.proto.MetricsFlow value) {
      copyOnWrite();
      instance.addFlows(index, value);
      return this;
    }
    /**
     * <code>repeated .clarity.v1.MetricsFlow flows = 1;</code>
     */
    public Builder addFlows(
        dev.ezcd.clarity.proto.MetricsFlow.Builder builderForValue) {
      copyOnWrite();
      instance.addFlows(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .clarity.v1.MetricsFlow flows = 1;</code>
     */
    public Builder addFlows(
        int index, dev.ezcd.clarity.proto.MetricsFlow.Builder builderForValue) {
      copyOnWrite();
      instance.addFlows(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .clarity.v1.MetricsFlow flows = 1;</code>
     */
    public Builder addAllFlows(
        java.lang.Iterable<? extends dev.ezcd.clarity.proto.MetricsFlow> values) {
      copyOnWrite();
      instance.addAllFlows(values);
      return this;
    }
    /**
     * <code>repeated .clarity.v1.MetricsFlow flows = 1;</code>
     */
    public Builder clearFlows() {
      copyOnWrite();
      instance.clearFlows();
      return this;
    }
    /**
     * <code>repeated .clarity.v1.MetricsFlow flows = 1;</code>
     */
    public Builder removeFlows(int index) {
      copyOnWrite();
      instance.removeFlows(index);
      return this;
    }

    /**
     * <pre>
     * Truncated reports that the commit window, rather than the repository's
     * age, is what ended the history — so an aggregate built from it is not the
     * whole story. Worth more here than in a commit list: a reader can see the
     * bottom of a scroll, but nothing on a chart says it is short a few deploys.
     * </pre>
     *
     * <code>bool truncated = 2;</code>
     * @return The truncated.
     */
    @java.lang.Override
    public boolean getTruncated() {
      return instance.getTruncated();
    }
    /**
     * <pre>
     * Truncated reports that the commit window, rather than the repository's
     * age, is what ended the history — so an aggregate built from it is not the
     * whole story. Worth more here than in a commit list: a reader can see the
     * bottom of a scroll, but nothing on a chart says it is short a few deploys.
     * </pre>
     *
     * <code>bool truncated = 2;</code>
     * @param value The truncated to set.
     * @return This builder for chaining.
     */
    public Builder setTruncated(boolean value) {
      copyOnWrite();
      instance.setTruncated(value);
      return this;
    }
    /**
     * <pre>
     * Truncated reports that the commit window, rather than the repository's
     * age, is what ended the history — so an aggregate built from it is not the
     * whole story. Worth more here than in a commit list: a reader can see the
     * bottom of a scroll, but nothing on a chart says it is short a few deploys.
     * </pre>
     *
     * <code>bool truncated = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTruncated() {
      copyOnWrite();
      instance.clearTruncated();
      return this;
    }

    /**
     * <code>int32 limit = 3;</code>
     * @return The limit.
     */
    @java.lang.Override
    public int getLimit() {
      return instance.getLimit();
    }
    /**
     * <code>int32 limit = 3;</code>
     * @param value The limit to set.
     * @return This builder for chaining.
     */
    public Builder setLimit(int value) {
      copyOnWrite();
      instance.setLimit(value);
      return this;
    }
    /**
     * <code>int32 limit = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLimit() {
      copyOnWrite();
      instance.clearLimit();
      return this;
    }

    /**
     * <pre>
     * Always set, for the reason View.generated_unix_seconds explains.
     * </pre>
     *
     * <code>int64 generated_unix_seconds = 4;</code>
     * @return The generatedUnixSeconds.
     */
    @java.lang.Override
    public long getGeneratedUnixSeconds() {
      return instance.getGeneratedUnixSeconds();
    }
    /**
     * <pre>
     * Always set, for the reason View.generated_unix_seconds explains.
     * </pre>
     *
     * <code>int64 generated_unix_seconds = 4;</code>
     * @param value The generatedUnixSeconds to set.
     * @return This builder for chaining.
     */
    public Builder setGeneratedUnixSeconds(long value) {
      copyOnWrite();
      instance.setGeneratedUnixSeconds(value);
      return this;
    }
    /**
     * <pre>
     * Always set, for the reason View.generated_unix_seconds explains.
     * </pre>
     *
     * <code>int64 generated_unix_seconds = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearGeneratedUnixSeconds() {
      copyOnWrite();
      instance.clearGeneratedUnixSeconds();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:clarity.v1.Metrics)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new dev.ezcd.clarity.proto.Metrics();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "flows_",
            dev.ezcd.clarity.proto.MetricsFlow.class,
            "truncated_",
            "limit_",
            "generatedUnixSeconds_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0001\u0000\u0001\u001b\u0002\u0007" +
              "\u0003\u0004\u0004\u0002";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<dev.ezcd.clarity.proto.Metrics> parser = PARSER;
        if (parser == null) {
          synchronized (dev.ezcd.clarity.proto.Metrics.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<dev.ezcd.clarity.proto.Metrics>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:clarity.v1.Metrics)
  private static final dev.ezcd.clarity.proto.Metrics DEFAULT_INSTANCE;
  static {
    Metrics defaultInstance = new Metrics();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Metrics.class, defaultInstance);
  }

  public static dev.ezcd.clarity.proto.Metrics getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Metrics> PARSER;

  public static com.google.protobuf.Parser<Metrics> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

