// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clarity/v1/view.proto

package dev.ezcd.clarity.proto;

public interface MetricsFlowOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clarity.v1.MetricsFlow)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>bool undeclared = 2;</code>
   * @return The undeclared.
   */
  boolean getUndeclared();

  /**
   * <code>.clarity.v1.LeadAxis axis = 3;</code>
   * @return Whether the axis field is set.
   */
  boolean hasAxis();
  /**
   * <code>.clarity.v1.LeadAxis axis = 3;</code>
   * @return The axis.
   */
  dev.ezcd.clarity.proto.LeadAxis getAxis();

  /**
   * <pre>
   * The busiest week on show, which is what every deploy bar is drawn
   * relative to. A decision rather than geometry: bars could be scaled
   * against a fixed ceiling or against the repository's all-time best, and
   * "the busiest week you can see" is the one that makes the rows on screen
   * comparable to each other.
   * </pre>
   *
   * <code>int32 max_deploys = 4;</code>
   * @return The maxDeploys.
   */
  int getMaxDeploys();

  /**
   * <code>repeated .clarity.v1.Week weeks = 5;</code>
   */
  java.util.List<dev.ezcd.clarity.proto.Week> 
      getWeeksList();
  /**
   * <code>repeated .clarity.v1.Week weeks = 5;</code>
   */
  dev.ezcd.clarity.proto.Week getWeeks(int index);
  /**
   * <code>repeated .clarity.v1.Week weeks = 5;</code>
   */
  int getWeeksCount();
}
