// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clarity/v1/view.proto

package dev.ezcd.clarity.proto;

/**
 * Protobuf enum {@code clarity.v1.Outcome}
 */
public enum Outcome
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>OUTCOME_UNSPECIFIED = 0;</code>
   */
  OUTCOME_UNSPECIFIED(0),
  /**
   * <code>OUTCOME_OK = 1;</code>
   */
  OUTCOME_OK(1),
  /**
   * <pre>
   * The host is not in this device's known_hosts. Ask, then TrustHost.
   * </pre>
   *
   * <code>OUTCOME_HOST_KEY_UNKNOWN = 2;</code>
   */
  OUTCOME_HOST_KEY_UNKNOWN(2),
  /**
   * <pre>
   * It is, and it is presenting something else. Ask louder.
   * </pre>
   *
   * <code>OUTCOME_HOST_KEY_CHANGED = 3;</code>
   */
  OUTCOME_HOST_KEY_CHANGED(3),
  /**
   * <pre>
   * The host refused this device's key. The key needs adding on the host.
   * </pre>
   *
   * <code>OUTCOME_AUTH_DENIED = 4;</code>
   */
  OUTCOME_AUTH_DENIED(4),
  /**
   * <code>OUTCOME_FAILED = 5;</code>
   */
  OUTCOME_FAILED(5),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>OUTCOME_UNSPECIFIED = 0;</code>
   */
  public static final int OUTCOME_UNSPECIFIED_VALUE = 0;
  /**
   * <code>OUTCOME_OK = 1;</code>
   */
  public static final int OUTCOME_OK_VALUE = 1;
  /**
   * <pre>
   * The host is not in this device's known_hosts. Ask, then TrustHost.
   * </pre>
   *
   * <code>OUTCOME_HOST_KEY_UNKNOWN = 2;</code>
   */
  public static final int OUTCOME_HOST_KEY_UNKNOWN_VALUE = 2;
  /**
   * <pre>
   * It is, and it is presenting something else. Ask louder.
   * </pre>
   *
   * <code>OUTCOME_HOST_KEY_CHANGED = 3;</code>
   */
  public static final int OUTCOME_HOST_KEY_CHANGED_VALUE = 3;
  /**
   * <pre>
   * The host refused this device's key. The key needs adding on the host.
   * </pre>
   *
   * <code>OUTCOME_AUTH_DENIED = 4;</code>
   */
  public static final int OUTCOME_AUTH_DENIED_VALUE = 4;
  /**
   * <code>OUTCOME_FAILED = 5;</code>
   */
  public static final int OUTCOME_FAILED_VALUE = 5;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Outcome valueOf(int value) {
    return forNumber(value);
  }

  public static Outcome forNumber(int value) {
    switch (value) {
      case 0: return OUTCOME_UNSPECIFIED;
      case 1: return OUTCOME_OK;
      case 2: return OUTCOME_HOST_KEY_UNKNOWN;
      case 3: return OUTCOME_HOST_KEY_CHANGED;
      case 4: return OUTCOME_AUTH_DENIED;
      case 5: return OUTCOME_FAILED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Outcome>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Outcome> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Outcome>() {
          @java.lang.Override
          public Outcome findValueByNumber(int number) {
            return Outcome.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return OutcomeVerifier.INSTANCE;
  }

  private static final class OutcomeVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new OutcomeVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return Outcome.forNumber(number) != null;
          }
        };

  private final int value;

  private Outcome(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:clarity.v1.Outcome)
}

