// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clarity/v1/view.proto

package dev.ezcd.clarity.proto;

/**
 * <pre>
 * Plot says how a week's lead times should be drawn.
 * The choice, not the drawing. Below a handful of deploys the quantiles are
 * interpolations between two or three real values, so a box plot would put a
 * smear on screen where there were only two deploys — the individual samples
 * are the honest rendering, and the threshold is the core's to decide.
 * </pre>
 *
 * Protobuf enum {@code clarity.v1.Plot}
 */
public enum Plot
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>PLOT_UNSPECIFIED = 0;</code>
   */
  PLOT_UNSPECIFIED(0),
  /**
   * <pre>
   * nothing deployed; there is no distribution
   * </pre>
   *
   * <code>PLOT_NONE = 1;</code>
   */
  PLOT_NONE(1),
  /**
   * <pre>
   * too few for quartiles — draw sample_seconds
   * </pre>
   *
   * <code>PLOT_POINTS = 2;</code>
   */
  PLOT_POINTS(2),
  /**
   * <pre>
   * whiskers, box, median
   * </pre>
   *
   * <code>PLOT_BOX = 3;</code>
   */
  PLOT_BOX(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>PLOT_UNSPECIFIED = 0;</code>
   */
  public static final int PLOT_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * nothing deployed; there is no distribution
   * </pre>
   *
   * <code>PLOT_NONE = 1;</code>
   */
  public static final int PLOT_NONE_VALUE = 1;
  /**
   * <pre>
   * too few for quartiles — draw sample_seconds
   * </pre>
   *
   * <code>PLOT_POINTS = 2;</code>
   */
  public static final int PLOT_POINTS_VALUE = 2;
  /**
   * <pre>
   * whiskers, box, median
   * </pre>
   *
   * <code>PLOT_BOX = 3;</code>
   */
  public static final int PLOT_BOX_VALUE = 3;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Plot valueOf(int value) {
    return forNumber(value);
  }

  public static Plot forNumber(int value) {
    switch (value) {
      case 0: return PLOT_UNSPECIFIED;
      case 1: return PLOT_NONE;
      case 2: return PLOT_POINTS;
      case 3: return PLOT_BOX;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Plot>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Plot> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Plot>() {
          @java.lang.Override
          public Plot findValueByNumber(int number) {
            return Plot.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return PlotVerifier.INSTANCE;
  }

  private static final class PlotVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new PlotVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return Plot.forNumber(number) != null;
          }
        };

  private final int value;

  private Plot(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:clarity.v1.Plot)
}

