// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clarity/v1/view.proto

package dev.ezcd.clarity.proto;

public interface RepoSummaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clarity.v1.RepoSummary)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * ID is derived from the URL, so the same repository is the same entry
   * across launches and devices.
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * ID is derived from the URL, so the same repository is the same entry
   * across launches and devices.
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string url = 3;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 3;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>string branch = 4;</code>
   * @return The branch.
   */
  java.lang.String getBranch();
  /**
   * <code>string branch = 4;</code>
   * @return The bytes for branch.
   */
  com.google.protobuf.ByteString
      getBranchBytes();
}
