// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clarity/v1/view.proto

package dev.ezcd.clarity.proto;

/**
 * <pre>
 * RepoList is the menu of tracked repositories.
 * </pre>
 *
 * Protobuf type {@code clarity.v1.RepoList}
 */
public  final class RepoList extends
    com.google.protobuf.GeneratedMessageLite<
        RepoList, RepoList.Builder> implements
    // @@protoc_insertion_point(message_implements:clarity.v1.RepoList)
    RepoListOrBuilder {
  private RepoList() {
    repos_ = emptyProtobufList();
  }
  public static final int REPOS_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<dev.ezcd.clarity.proto.RepoSummary> repos_;
  /**
   * <code>repeated .clarity.v1.RepoSummary repos = 1;</code>
   */
  @java.lang.Override
  public java.util.List<dev.ezcd.clarity.proto.RepoSummary> getReposList() {
    return repos_;
  }
  /**
   * <code>repeated .clarity.v1.RepoSummary repos = 1;</code>
   */
  public java.util.List<? extends dev.ezcd.clarity.proto.RepoSummaryOrBuilder> 
      getReposOrBuilderList() {
    return repos_;
  }
  /**
   * <code>repeated .clarity.v1.RepoSummary repos = 1;</code>
   */
  @java.lang.Override
  public int getReposCount() {
    return repos_.size();
  }
  /**
   * <code>repeated .clarity.v1.RepoSummary repos = 1;</code>
   */
  @java.lang.Override
  public dev.ezcd.clarity.proto.RepoSummary getRepos(int index) {
    return repos_.get(index);
  }
  /**
   * <code>repeated .clarity.v1.RepoSummary repos = 1;</code>
   */
  public dev.ezcd.clarity.proto.RepoSummaryOrBuilder getReposOrBuilder(
      int index) {
    return repos_.get(index);
  }
  private void ensureReposIsMutable() {
    com.google.protobuf.Internal.ProtobufList<dev.ezcd.clarity.proto.RepoSummary> tmp = repos_;
    if (!tmp.isModifiable()) {
      repos_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .clarity.v1.RepoSummary repos = 1;</code>
   */
  private void setRepos(
      int index, dev.ezcd.clarity.proto.RepoSummary value) {
    value.getClass();
  ensureReposIsMutable();
    repos_.set(index, value);
  }
  /**
   * <code>repeated .clarity.v1.RepoSummary repos = 1;</code>
   */
  private void addRepos(dev.ezcd.clarity.proto.RepoSummary value) {
    value.getClass();
  ensureReposIsMutable();
    repos_.add(value);
  }
  /**
   * <code>repeated .clarity.v1.RepoSummary repos = 1;</code>
   */
  private void addRepos(
      int index, dev.ezcd.clarity.proto.RepoSummary value) {
    value.getClass();
  ensureReposIsMutable();
    repos_.add(index, value);
  }
  /**
   * <code>repeated .clarity.v1.RepoSummary repos = 1;</code>
   */
  private void addAllRepos(
      java.lang.Iterable<? extends dev.ezcd.clarity.proto.RepoSummary> values) {
    ensureReposIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, repos_);
  }
  /**
   * <code>repeated .clarity.v1.RepoSummary repos = 1;</code>
   */
  private void clearRepos() {
    repos_ = emptyProtobufList();
  }
  /**
   * <code>repeated .clarity.v1.RepoSummary repos = 1;</code>
   */
  private void removeRepos(int index) {
    ensureReposIsMutable();
    repos_.remove(index);
  }

  public static final int GENERATED_UNIX_SECONDS_FIELD_NUMBER = 2;
  private long generatedUnixSeconds_;
  /**
   * <pre>
   * Always set, for the reason View.generated_unix_seconds explains: an empty
   * list would otherwise encode to zero bytes and cross as null.
   * </pre>
   *
   * <code>int64 generated_unix_seconds = 2;</code>
   * @return The generatedUnixSeconds.
   */
  @java.lang.Override
  public long getGeneratedUnixSeconds() {
    return generatedUnixSeconds_;
  }
  /**
   * <pre>
   * Always set, for the reason View.generated_unix_seconds explains: an empty
   * list would otherwise encode to zero bytes and cross as null.
   * </pre>
   *
   * <code>int64 generated_unix_seconds = 2;</code>
   * @param value The generatedUnixSeconds to set.
   */
  private void setGeneratedUnixSeconds(long value) {
    
    generatedUnixSeconds_ = value;
  }
  /**
   * <pre>
   * Always set, for the reason View.generated_unix_seconds explains: an empty
   * list would otherwise encode to zero bytes and cross as null.
   * </pre>
   *
   * <code>int64 generated_unix_seconds = 2;</code>
   */
  private void clearGeneratedUnixSeconds() {
    
    generatedUnixSeconds_ = 0L;
  }

  public static dev.ezcd.clarity.proto.RepoList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.RepoList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.RepoList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.RepoList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.RepoList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.RepoList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.RepoList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.RepoList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.RepoList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.RepoList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.RepoList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.RepoList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(dev.ezcd.clarity.proto.RepoList prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * RepoList is the menu of tracked repositories.
   * </pre>
   *
   * Protobuf type {@code clarity.v1.RepoList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        dev.ezcd.clarity.proto.RepoList, Builder> implements
      // @@protoc_insertion_point(builder_implements:clarity.v1.RepoList)
      dev.ezcd.clarity.proto.RepoListOrBuilder {
    // Construct using dev.ezcd.clarity.proto.RepoList.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .clarity.v1.RepoSummary repos = 1;</code>
     */
    @java.lang.Override
    public java.util.List<dev.ezcd.clarity.proto.RepoSummary> getReposList() {
      return java.util.Collections.unmodifiableList(
          instance.getReposList());
    }
    /**
     * <code>repeated .clarity.v1.RepoSummary repos = 1;</code>
     */
    @java.lang.Override
    public int getReposCount() {
      return instance.getReposCount();
    }/**
     * <code>repeated .clarity.v1.RepoSummary repos = 1;</code>
     */
    @java.lang.Override
    public dev.ezcd.clarity.proto.RepoSummary getRepos(int index) {
      return instance.getRepos(index);
    }
    /**
     * <code>repeated .clarity.v1.RepoSummary repos = 1;</code>
     */
    public Builder setRepos(
        int index, dev.ezcd.clarity.proto.RepoSummary value) {
      copyOnWrite();
      instance.setRepos(index, value);
      return this;
    }
    /**
     * <code>repeated .clarity.v1.RepoSummary repos = 1;</code>
     */
    public Builder setRepos(
        int index, dev.ezcd.clarity.proto.RepoSummary.Builder builderForValue) {
      copyOnWrite();
      instance.setRepos(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .clarity.v1.RepoSummary repos = 1;</code>
     */
    public Builder addRepos(dev.ezcd.clarity.proto.RepoSummary value) {
      copyOnWrite();
      instance.addRepos(value);
      return this;
    }
    /**
     * <code>repeated .clarity.v1.RepoSummary repos = 1;</code>
     */
    public Builder addRepos(
        int index, dev.ezcd.clarity.proto.RepoSummary value) {
      copyOnWrite();
      instance.addRepos(index, value);
      return this;
    }
    /**
     * <code>repeated .clarity.v1.RepoSummary repos = 1;</code>
     */
    public Builder addRepos(
        dev.ezcd.clarity.proto.RepoSummary.Builder builderForValue) {
      copyOnWrite();
      instance.addRepos(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .clarity.v1.RepoSummary repos = 1;</code>
     */
    public Builder addRepos(
        int index, dev.ezcd.clarity.proto.RepoSummary.Builder builderForValue) {
      copyOnWrite();
      instance.addRepos(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .clarity.v1.RepoSummary repos = 1;</code>
     */
    public Builder addAllRepos(
        java.lang.Iterable<? extends dev.ezcd.clarity.proto.RepoSummary> values) {
      copyOnWrite();
      instance.addAllRepos(values);
      return this;
    }
    /**
     * <code>repeated .clarity.v1.RepoSummary repos = 1;</code>
     */
    public Builder clearRepos() {
      copyOnWrite();
      instance.clearRepos();
      return this;
    }
    /**
     * <code>repeated .clarity.v1.RepoSummary repos = 1;</code>
     */
    public Builder removeRepos(int index) {
      copyOnWrite();
      instance.removeRepos(index);
      return this;
    }

    /**
     * <pre>
     * Always set, for the reason View.generated_unix_seconds explains: an empty
     * list would otherwise encode to zero bytes and cross as null.
     * </pre>
     *
     * <code>int64 generated_unix_seconds = 2;</code>
     * @return The generatedUnixSeconds.
     */
    @java.lang.Override
    public long getGeneratedUnixSeconds() {
      return instance.getGeneratedUnixSeconds();
    }
    /**
     * <pre>
     * Always set, for the reason View.generated_unix_seconds explains: an empty
     * list would otherwise encode to zero bytes and cross as null.
     * </pre>
     *
     * <code>int64 generated_unix_seconds = 2;</code>
     * @param value The generatedUnixSeconds to set.
     * @return This builder for chaining.
     */
    public Builder setGeneratedUnixSeconds(long value) {
      copyOnWrite();
      instance.setGeneratedUnixSeconds(value);
      return this;
    }
    /**
     * <pre>
     * Always set, for the reason View.generated_unix_seconds explains: an empty
     * list would otherwise encode to zero bytes and cross as null.
     * </pre>
     *
     * <code>int64 generated_unix_seconds = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearGeneratedUnixSeconds() {
      copyOnWrite();
      instance.clearGeneratedUnixSeconds();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:clarity.v1.RepoList)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new dev.ezcd.clarity.proto.RepoList();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "repos_",
            dev.ezcd.clarity.proto.RepoSummary.class,
            "generatedUnixSeconds_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0001\u0000\u0001\u001b\u0002\u0002" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<dev.ezcd.clarity.proto.RepoList> parser = PARSER;
        if (parser == null) {
          synchronized (dev.ezcd.clarity.proto.RepoList.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<dev.ezcd.clarity.proto.RepoList>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:clarity.v1.RepoList)
  private static final dev.ezcd.clarity.proto.RepoList DEFAULT_INSTANCE;
  static {
    RepoList defaultInstance = new RepoList();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      RepoList.class, defaultInstance);
  }

  public static dev.ezcd.clarity.proto.RepoList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<RepoList> PARSER;

  public static com.google.protobuf.Parser<RepoList> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

