// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clarity/v1/view.proto

package dev.ezcd.clarity.proto;

public interface RepoListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clarity.v1.RepoList)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .clarity.v1.RepoSummary repos = 1;</code>
   */
  java.util.List<dev.ezcd.clarity.proto.RepoSummary> 
      getReposList();
  /**
   * <code>repeated .clarity.v1.RepoSummary repos = 1;</code>
   */
  dev.ezcd.clarity.proto.RepoSummary getRepos(int index);
  /**
   * <code>repeated .clarity.v1.RepoSummary repos = 1;</code>
   */
  int getReposCount();

  /**
   * <pre>
   * Always set, for the reason View.generated_unix_seconds explains: an empty
   * list would otherwise encode to zero bytes and cross as null.
   * </pre>
   *
   * <code>int64 generated_unix_seconds = 2;</code>
   * @return The generatedUnixSeconds.
   */
  long getGeneratedUnixSeconds();
}
