// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clarity/v1/view.proto

package dev.ezcd.clarity.proto;

/**
 * Protobuf type {@code clarity.v1.RepoSummary}
 */
public  final class RepoSummary extends
    com.google.protobuf.GeneratedMessageLite<
        RepoSummary, RepoSummary.Builder> implements
    // @@protoc_insertion_point(message_implements:clarity.v1.RepoSummary)
    RepoSummaryOrBuilder {
  private RepoSummary() {
    id_ = "";
    name_ = "";
    namespace_ = "";
    host_ = "";
    alias_ = "";
    url_ = "";
    branch_ = "";
    flows_ = emptyProtobufList();
  }
  public static final int ID_FIELD_NUMBER = 1;
  private java.lang.String id_;
  /**
   * <pre>
   * ID is derived from the URL, so the same repository is the same entry
   * across launches and devices.
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    return id_;
  }
  /**
   * <pre>
   * ID is derived from the URL, so the same repository is the same entry
   * across launches and devices.
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(id_);
  }
  /**
   * <pre>
   * ID is derived from the URL, so the same repository is the same entry
   * across launches and devices.
   * </pre>
   *
   * <code>string id = 1;</code>
   * @param value The id to set.
   */
  private void setId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    id_ = value;
  }
  /**
   * <pre>
   * ID is derived from the URL, so the same repository is the same entry
   * across launches and devices.
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  private void clearId() {
    
    id_ = getDefaultInstance().getId();
  }
  /**
   * <pre>
   * ID is derived from the URL, so the same repository is the same entry
   * across launches and devices.
   * </pre>
   *
   * <code>string id = 1;</code>
   * @param value The bytes for id to set.
   */
  private void setIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    id_ = value.toStringUtf8();
    
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private java.lang.String name_;
  /**
   * <pre>
   * Name is the last path segment, and the one part of a label that is never
   * abbreviated away. Namespace is everything before it, shown dimmed in
   * front; empty when the path is a single segment. Host is for the subtitle
   * and is never part of the name.
   * Derived here rather than in each app so that Android and iOS call the same
   * repository by the same name. The rule is pure git with no host detection:
   * clarity does not know what GitHub is, and a rule that did would be wrong
   * on a box in a cupboard.
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    return name_;
  }
  /**
   * <pre>
   * Name is the last path segment, and the one part of a label that is never
   * abbreviated away. Namespace is everything before it, shown dimmed in
   * front; empty when the path is a single segment. Host is for the subtitle
   * and is never part of the name.
   * Derived here rather than in each app so that Android and iOS call the same
   * repository by the same name. The rule is pure git with no host detection:
   * clarity does not know what GitHub is, and a rule that did would be wrong
   * on a box in a cupboard.
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(name_);
  }
  /**
   * <pre>
   * Name is the last path segment, and the one part of a label that is never
   * abbreviated away. Namespace is everything before it, shown dimmed in
   * front; empty when the path is a single segment. Host is for the subtitle
   * and is never part of the name.
   * Derived here rather than in each app so that Android and iOS call the same
   * repository by the same name. The rule is pure git with no host detection:
   * clarity does not know what GitHub is, and a rule that did would be wrong
   * on a box in a cupboard.
   * </pre>
   *
   * <code>string name = 2;</code>
   * @param value The name to set.
   */
  private void setName(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    name_ = value;
  }
  /**
   * <pre>
   * Name is the last path segment, and the one part of a label that is never
   * abbreviated away. Namespace is everything before it, shown dimmed in
   * front; empty when the path is a single segment. Host is for the subtitle
   * and is never part of the name.
   * Derived here rather than in each app so that Android and iOS call the same
   * repository by the same name. The rule is pure git with no host detection:
   * clarity does not know what GitHub is, and a rule that did would be wrong
   * on a box in a cupboard.
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  private void clearName() {
    
    name_ = getDefaultInstance().getName();
  }
  /**
   * <pre>
   * Name is the last path segment, and the one part of a label that is never
   * abbreviated away. Namespace is everything before it, shown dimmed in
   * front; empty when the path is a single segment. Host is for the subtitle
   * and is never part of the name.
   * Derived here rather than in each app so that Android and iOS call the same
   * repository by the same name. The rule is pure git with no host detection:
   * clarity does not know what GitHub is, and a rule that did would be wrong
   * on a box in a cupboard.
   * </pre>
   *
   * <code>string name = 2;</code>
   * @param value The bytes for name to set.
   */
  private void setNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    name_ = value.toStringUtf8();
    
  }

  public static final int NAMESPACE_FIELD_NUMBER = 6;
  private java.lang.String namespace_;
  /**
   * <code>string namespace = 6;</code>
   * @return The namespace.
   */
  @java.lang.Override
  public java.lang.String getNamespace() {
    return namespace_;
  }
  /**
   * <code>string namespace = 6;</code>
   * @return The bytes for namespace.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNamespaceBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(namespace_);
  }
  /**
   * <code>string namespace = 6;</code>
   * @param value The namespace to set.
   */
  private void setNamespace(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    namespace_ = value;
  }
  /**
   * <code>string namespace = 6;</code>
   */
  private void clearNamespace() {
    
    namespace_ = getDefaultInstance().getNamespace();
  }
  /**
   * <code>string namespace = 6;</code>
   * @param value The bytes for namespace to set.
   */
  private void setNamespaceBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    namespace_ = value.toStringUtf8();
    
  }

  public static final int HOST_FIELD_NUMBER = 7;
  private java.lang.String host_;
  /**
   * <code>string host = 7;</code>
   * @return The host.
   */
  @java.lang.Override
  public java.lang.String getHost() {
    return host_;
  }
  /**
   * <code>string host = 7;</code>
   * @return The bytes for host.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHostBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(host_);
  }
  /**
   * <code>string host = 7;</code>
   * @param value The host to set.
   */
  private void setHost(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    host_ = value;
  }
  /**
   * <code>string host = 7;</code>
   */
  private void clearHost() {
    
    host_ = getDefaultInstance().getHost();
  }
  /**
   * <code>string host = 7;</code>
   * @param value The bytes for host to set.
   */
  private void setHostBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    host_ = value.toStringUtf8();
    
  }

  public static final int ALIAS_FIELD_NUMBER = 8;
  private java.lang.String alias_;
  /**
   * <pre>
   * Alias is what the user renamed this to, on this device only. When set it
   * replaces the title and the derived namespace/name moves to the subtitle.
   * </pre>
   *
   * <code>string alias = 8;</code>
   * @return The alias.
   */
  @java.lang.Override
  public java.lang.String getAlias() {
    return alias_;
  }
  /**
   * <pre>
   * Alias is what the user renamed this to, on this device only. When set it
   * replaces the title and the derived namespace/name moves to the subtitle.
   * </pre>
   *
   * <code>string alias = 8;</code>
   * @return The bytes for alias.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAliasBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(alias_);
  }
  /**
   * <pre>
   * Alias is what the user renamed this to, on this device only. When set it
   * replaces the title and the derived namespace/name moves to the subtitle.
   * </pre>
   *
   * <code>string alias = 8;</code>
   * @param value The alias to set.
   */
  private void setAlias(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    alias_ = value;
  }
  /**
   * <pre>
   * Alias is what the user renamed this to, on this device only. When set it
   * replaces the title and the derived namespace/name moves to the subtitle.
   * </pre>
   *
   * <code>string alias = 8;</code>
   */
  private void clearAlias() {
    
    alias_ = getDefaultInstance().getAlias();
  }
  /**
   * <pre>
   * Alias is what the user renamed this to, on this device only. When set it
   * replaces the title and the derived namespace/name moves to the subtitle.
   * </pre>
   *
   * <code>string alias = 8;</code>
   * @param value The bytes for alias to set.
   */
  private void setAliasBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    alias_ = value.toStringUtf8();
    
  }

  public static final int URL_FIELD_NUMBER = 3;
  private java.lang.String url_;
  /**
   * <code>string url = 3;</code>
   * @return The url.
   */
  @java.lang.Override
  public java.lang.String getUrl() {
    return url_;
  }
  /**
   * <code>string url = 3;</code>
   * @return The bytes for url.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUrlBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(url_);
  }
  /**
   * <code>string url = 3;</code>
   * @param value The url to set.
   */
  private void setUrl(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    url_ = value;
  }
  /**
   * <code>string url = 3;</code>
   */
  private void clearUrl() {
    
    url_ = getDefaultInstance().getUrl();
  }
  /**
   * <code>string url = 3;</code>
   * @param value The bytes for url to set.
   */
  private void setUrlBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    url_ = value.toStringUtf8();
    
  }

  public static final int BRANCH_FIELD_NUMBER = 4;
  private java.lang.String branch_;
  /**
   * <code>string branch = 4;</code>
   * @return The branch.
   */
  @java.lang.Override
  public java.lang.String getBranch() {
    return branch_;
  }
  /**
   * <code>string branch = 4;</code>
   * @return The bytes for branch.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBranchBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(branch_);
  }
  /**
   * <code>string branch = 4;</code>
   * @param value The branch to set.
   */
  private void setBranch(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    branch_ = value;
  }
  /**
   * <code>string branch = 4;</code>
   */
  private void clearBranch() {
    
    branch_ = getDefaultInstance().getBranch();
  }
  /**
   * <code>string branch = 4;</code>
   * @param value The bytes for branch to set.
   */
  private void setBranchBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    branch_ = value.toStringUtf8();
    
  }

  public static final int CI_FIELD_NUMBER = 9;
  private int ci_;
  /**
   * <pre>
   * The last view's verdicts, so a switcher can show how each repository is
   * doing without opening it. Absent until a repository has been read once —
   * which is why these are statuses and not booleans: "not known yet" is a
   * different thing from "nothing reported".
   * </pre>
   *
   * <code>.clarity.v1.Status ci = 9;</code>
   * @return The enum numeric value on the wire for ci.
   */
  @java.lang.Override
  public int getCiValue() {
    return ci_;
  }
  /**
   * <pre>
   * The last view's verdicts, so a switcher can show how each repository is
   * doing without opening it. Absent until a repository has been read once —
   * which is why these are statuses and not booleans: "not known yet" is a
   * different thing from "nothing reported".
   * </pre>
   *
   * <code>.clarity.v1.Status ci = 9;</code>
   * @return The ci.
   */
  @java.lang.Override
  public dev.ezcd.clarity.proto.Status getCi() {
    dev.ezcd.clarity.proto.Status result = dev.ezcd.clarity.proto.Status.forNumber(ci_);
    return result == null ? dev.ezcd.clarity.proto.Status.UNRECOGNIZED : result;
  }
  /**
   * <pre>
   * The last view's verdicts, so a switcher can show how each repository is
   * doing without opening it. Absent until a repository has been read once —
   * which is why these are statuses and not booleans: "not known yet" is a
   * different thing from "nothing reported".
   * </pre>
   *
   * <code>.clarity.v1.Status ci = 9;</code>
   * @param value The enum numeric value on the wire for ci to set.
   */
  private void setCiValue(int value) {
      ci_ = value;
  }
  /**
   * <pre>
   * The last view's verdicts, so a switcher can show how each repository is
   * doing without opening it. Absent until a repository has been read once —
   * which is why these are statuses and not booleans: "not known yet" is a
   * different thing from "nothing reported".
   * </pre>
   *
   * <code>.clarity.v1.Status ci = 9;</code>
   * @param value The ci to set.
   */
  private void setCi(dev.ezcd.clarity.proto.Status value) {
    ci_ = value.getNumber();
    
  }
  /**
   * <pre>
   * The last view's verdicts, so a switcher can show how each repository is
   * doing without opening it. Absent until a repository has been read once —
   * which is why these are statuses and not booleans: "not known yet" is a
   * different thing from "nothing reported".
   * </pre>
   *
   * <code>.clarity.v1.Status ci = 9;</code>
   */
  private void clearCi() {
    
    ci_ = 0;
  }

  public static final int DEPLOY_FIELD_NUMBER = 10;
  private int deploy_;
  /**
   * <code>.clarity.v1.Status deploy = 10;</code>
   * @return The enum numeric value on the wire for deploy.
   */
  @java.lang.Override
  public int getDeployValue() {
    return deploy_;
  }
  /**
   * <code>.clarity.v1.Status deploy = 10;</code>
   * @return The deploy.
   */
  @java.lang.Override
  public dev.ezcd.clarity.proto.Status getDeploy() {
    dev.ezcd.clarity.proto.Status result = dev.ezcd.clarity.proto.Status.forNumber(deploy_);
    return result == null ? dev.ezcd.clarity.proto.Status.UNRECOGNIZED : result;
  }
  /**
   * <code>.clarity.v1.Status deploy = 10;</code>
   * @param value The enum numeric value on the wire for deploy to set.
   */
  private void setDeployValue(int value) {
      deploy_ = value;
  }
  /**
   * <code>.clarity.v1.Status deploy = 10;</code>
   * @param value The deploy to set.
   */
  private void setDeploy(dev.ezcd.clarity.proto.Status value) {
    deploy_ = value.getNumber();
    
  }
  /**
   * <code>.clarity.v1.Status deploy = 10;</code>
   */
  private void clearDeploy() {
    
    deploy_ = 0;
  }

  public static final int FLOWS_FIELD_NUMBER = 11;
  private com.google.protobuf.Internal.ProtobufList<dev.ezcd.clarity.proto.FlowSummary> flows_;
  /**
   * <pre>
   * One entry per deploy target, in the order the tabs show them. A switcher
   * row draws one glyph each, with no names, and never hides one.
   * </pre>
   *
   * <code>repeated .clarity.v1.FlowSummary flows = 11;</code>
   */
  @java.lang.Override
  public java.util.List<dev.ezcd.clarity.proto.FlowSummary> getFlowsList() {
    return flows_;
  }
  /**
   * <pre>
   * One entry per deploy target, in the order the tabs show them. A switcher
   * row draws one glyph each, with no names, and never hides one.
   * </pre>
   *
   * <code>repeated .clarity.v1.FlowSummary flows = 11;</code>
   */
  public java.util.List<? extends dev.ezcd.clarity.proto.FlowSummaryOrBuilder> 
      getFlowsOrBuilderList() {
    return flows_;
  }
  /**
   * <pre>
   * One entry per deploy target, in the order the tabs show them. A switcher
   * row draws one glyph each, with no names, and never hides one.
   * </pre>
   *
   * <code>repeated .clarity.v1.FlowSummary flows = 11;</code>
   */
  @java.lang.Override
  public int getFlowsCount() {
    return flows_.size();
  }
  /**
   * <pre>
   * One entry per deploy target, in the order the tabs show them. A switcher
   * row draws one glyph each, with no names, and never hides one.
   * </pre>
   *
   * <code>repeated .clarity.v1.FlowSummary flows = 11;</code>
   */
  @java.lang.Override
  public dev.ezcd.clarity.proto.FlowSummary getFlows(int index) {
    return flows_.get(index);
  }
  /**
   * <pre>
   * One entry per deploy target, in the order the tabs show them. A switcher
   * row draws one glyph each, with no names, and never hides one.
   * </pre>
   *
   * <code>repeated .clarity.v1.FlowSummary flows = 11;</code>
   */
  public dev.ezcd.clarity.proto.FlowSummaryOrBuilder getFlowsOrBuilder(
      int index) {
    return flows_.get(index);
  }
  private void ensureFlowsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<dev.ezcd.clarity.proto.FlowSummary> tmp = flows_;
    if (!tmp.isModifiable()) {
      flows_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <pre>
   * One entry per deploy target, in the order the tabs show them. A switcher
   * row draws one glyph each, with no names, and never hides one.
   * </pre>
   *
   * <code>repeated .clarity.v1.FlowSummary flows = 11;</code>
   */
  private void setFlows(
      int index, dev.ezcd.clarity.proto.FlowSummary value) {
    value.getClass();
  ensureFlowsIsMutable();
    flows_.set(index, value);
  }
  /**
   * <pre>
   * One entry per deploy target, in the order the tabs show them. A switcher
   * row draws one glyph each, with no names, and never hides one.
   * </pre>
   *
   * <code>repeated .clarity.v1.FlowSummary flows = 11;</code>
   */
  private void addFlows(dev.ezcd.clarity.proto.FlowSummary value) {
    value.getClass();
  ensureFlowsIsMutable();
    flows_.add(value);
  }
  /**
   * <pre>
   * One entry per deploy target, in the order the tabs show them. A switcher
   * row draws one glyph each, with no names, and never hides one.
   * </pre>
   *
   * <code>repeated .clarity.v1.FlowSummary flows = 11;</code>
   */
  private void addFlows(
      int index, dev.ezcd.clarity.proto.FlowSummary value) {
    value.getClass();
  ensureFlowsIsMutable();
    flows_.add(index, value);
  }
  /**
   * <pre>
   * One entry per deploy target, in the order the tabs show them. A switcher
   * row draws one glyph each, with no names, and never hides one.
   * </pre>
   *
   * <code>repeated .clarity.v1.FlowSummary flows = 11;</code>
   */
  private void addAllFlows(
      java.lang.Iterable<? extends dev.ezcd.clarity.proto.FlowSummary> values) {
    ensureFlowsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, flows_);
  }
  /**
   * <pre>
   * One entry per deploy target, in the order the tabs show them. A switcher
   * row draws one glyph each, with no names, and never hides one.
   * </pre>
   *
   * <code>repeated .clarity.v1.FlowSummary flows = 11;</code>
   */
  private void clearFlows() {
    flows_ = emptyProtobufList();
  }
  /**
   * <pre>
   * One entry per deploy target, in the order the tabs show them. A switcher
   * row draws one glyph each, with no names, and never hides one.
   * </pre>
   *
   * <code>repeated .clarity.v1.FlowSummary flows = 11;</code>
   */
  private void removeFlows(int index) {
    ensureFlowsIsMutable();
    flows_.remove(index);
  }

  public static dev.ezcd.clarity.proto.RepoSummary parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.RepoSummary parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.RepoSummary parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.RepoSummary parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.RepoSummary parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.RepoSummary parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.RepoSummary parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.RepoSummary parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.RepoSummary parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.RepoSummary parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.RepoSummary parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.RepoSummary parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(dev.ezcd.clarity.proto.RepoSummary prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code clarity.v1.RepoSummary}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        dev.ezcd.clarity.proto.RepoSummary, Builder> implements
      // @@protoc_insertion_point(builder_implements:clarity.v1.RepoSummary)
      dev.ezcd.clarity.proto.RepoSummaryOrBuilder {
    // Construct using dev.ezcd.clarity.proto.RepoSummary.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * ID is derived from the URL, so the same repository is the same entry
     * across launches and devices.
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      return instance.getId();
    }
    /**
     * <pre>
     * ID is derived from the URL, so the same repository is the same entry
     * across launches and devices.
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      return instance.getIdBytes();
    }
    /**
     * <pre>
     * ID is derived from the URL, so the same repository is the same entry
     * across launches and devices.
     * </pre>
     *
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      copyOnWrite();
      instance.setId(value);
      return this;
    }
    /**
     * <pre>
     * ID is derived from the URL, so the same repository is the same entry
     * across launches and devices.
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      copyOnWrite();
      instance.clearId();
      return this;
    }
    /**
     * <pre>
     * ID is derived from the URL, so the same repository is the same entry
     * across launches and devices.
     * </pre>
     *
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * Name is the last path segment, and the one part of a label that is never
     * abbreviated away. Namespace is everything before it, shown dimmed in
     * front; empty when the path is a single segment. Host is for the subtitle
     * and is never part of the name.
     * Derived here rather than in each app so that Android and iOS call the same
     * repository by the same name. The rule is pure git with no host detection:
     * clarity does not know what GitHub is, and a rule that did would be wrong
     * on a box in a cupboard.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      return instance.getName();
    }
    /**
     * <pre>
     * Name is the last path segment, and the one part of a label that is never
     * abbreviated away. Namespace is everything before it, shown dimmed in
     * front; empty when the path is a single segment. Host is for the subtitle
     * and is never part of the name.
     * Derived here rather than in each app so that Android and iOS call the same
     * repository by the same name. The rule is pure git with no host detection:
     * clarity does not know what GitHub is, and a rule that did would be wrong
     * on a box in a cupboard.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return instance.getNameBytes();
    }
    /**
     * <pre>
     * Name is the last path segment, and the one part of a label that is never
     * abbreviated away. Namespace is everything before it, shown dimmed in
     * front; empty when the path is a single segment. Host is for the subtitle
     * and is never part of the name.
     * Derived here rather than in each app so that Android and iOS call the same
     * repository by the same name. The rule is pure git with no host detection:
     * clarity does not know what GitHub is, and a rule that did would be wrong
     * on a box in a cupboard.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      copyOnWrite();
      instance.setName(value);
      return this;
    }
    /**
     * <pre>
     * Name is the last path segment, and the one part of a label that is never
     * abbreviated away. Namespace is everything before it, shown dimmed in
     * front; empty when the path is a single segment. Host is for the subtitle
     * and is never part of the name.
     * Derived here rather than in each app so that Android and iOS call the same
     * repository by the same name. The rule is pure git with no host detection:
     * clarity does not know what GitHub is, and a rule that did would be wrong
     * on a box in a cupboard.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      copyOnWrite();
      instance.clearName();
      return this;
    }
    /**
     * <pre>
     * Name is the last path segment, and the one part of a label that is never
     * abbreviated away. Namespace is everything before it, shown dimmed in
     * front; empty when the path is a single segment. Host is for the subtitle
     * and is never part of the name.
     * Derived here rather than in each app so that Android and iOS call the same
     * repository by the same name. The rule is pure git with no host detection:
     * clarity does not know what GitHub is, and a rule that did would be wrong
     * on a box in a cupboard.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameBytes(value);
      return this;
    }

    /**
     * <code>string namespace = 6;</code>
     * @return The namespace.
     */
    @java.lang.Override
    public java.lang.String getNamespace() {
      return instance.getNamespace();
    }
    /**
     * <code>string namespace = 6;</code>
     * @return The bytes for namespace.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNamespaceBytes() {
      return instance.getNamespaceBytes();
    }
    /**
     * <code>string namespace = 6;</code>
     * @param value The namespace to set.
     * @return This builder for chaining.
     */
    public Builder setNamespace(
        java.lang.String value) {
      copyOnWrite();
      instance.setNamespace(value);
      return this;
    }
    /**
     * <code>string namespace = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearNamespace() {
      copyOnWrite();
      instance.clearNamespace();
      return this;
    }
    /**
     * <code>string namespace = 6;</code>
     * @param value The bytes for namespace to set.
     * @return This builder for chaining.
     */
    public Builder setNamespaceBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNamespaceBytes(value);
      return this;
    }

    /**
     * <code>string host = 7;</code>
     * @return The host.
     */
    @java.lang.Override
    public java.lang.String getHost() {
      return instance.getHost();
    }
    /**
     * <code>string host = 7;</code>
     * @return The bytes for host.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHostBytes() {
      return instance.getHostBytes();
    }
    /**
     * <code>string host = 7;</code>
     * @param value The host to set.
     * @return This builder for chaining.
     */
    public Builder setHost(
        java.lang.String value) {
      copyOnWrite();
      instance.setHost(value);
      return this;
    }
    /**
     * <code>string host = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearHost() {
      copyOnWrite();
      instance.clearHost();
      return this;
    }
    /**
     * <code>string host = 7;</code>
     * @param value The bytes for host to set.
     * @return This builder for chaining.
     */
    public Builder setHostBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setHostBytes(value);
      return this;
    }

    /**
     * <pre>
     * Alias is what the user renamed this to, on this device only. When set it
     * replaces the title and the derived namespace/name moves to the subtitle.
     * </pre>
     *
     * <code>string alias = 8;</code>
     * @return The alias.
     */
    @java.lang.Override
    public java.lang.String getAlias() {
      return instance.getAlias();
    }
    /**
     * <pre>
     * Alias is what the user renamed this to, on this device only. When set it
     * replaces the title and the derived namespace/name moves to the subtitle.
     * </pre>
     *
     * <code>string alias = 8;</code>
     * @return The bytes for alias.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAliasBytes() {
      return instance.getAliasBytes();
    }
    /**
     * <pre>
     * Alias is what the user renamed this to, on this device only. When set it
     * replaces the title and the derived namespace/name moves to the subtitle.
     * </pre>
     *
     * <code>string alias = 8;</code>
     * @param value The alias to set.
     * @return This builder for chaining.
     */
    public Builder setAlias(
        java.lang.String value) {
      copyOnWrite();
      instance.setAlias(value);
      return this;
    }
    /**
     * <pre>
     * Alias is what the user renamed this to, on this device only. When set it
     * replaces the title and the derived namespace/name moves to the subtitle.
     * </pre>
     *
     * <code>string alias = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearAlias() {
      copyOnWrite();
      instance.clearAlias();
      return this;
    }
    /**
     * <pre>
     * Alias is what the user renamed this to, on this device only. When set it
     * replaces the title and the derived namespace/name moves to the subtitle.
     * </pre>
     *
     * <code>string alias = 8;</code>
     * @param value The bytes for alias to set.
     * @return This builder for chaining.
     */
    public Builder setAliasBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAliasBytes(value);
      return this;
    }

    /**
     * <code>string url = 3;</code>
     * @return The url.
     */
    @java.lang.Override
    public java.lang.String getUrl() {
      return instance.getUrl();
    }
    /**
     * <code>string url = 3;</code>
     * @return The bytes for url.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUrlBytes() {
      return instance.getUrlBytes();
    }
    /**
     * <code>string url = 3;</code>
     * @param value The url to set.
     * @return This builder for chaining.
     */
    public Builder setUrl(
        java.lang.String value) {
      copyOnWrite();
      instance.setUrl(value);
      return this;
    }
    /**
     * <code>string url = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUrl() {
      copyOnWrite();
      instance.clearUrl();
      return this;
    }
    /**
     * <code>string url = 3;</code>
     * @param value The bytes for url to set.
     * @return This builder for chaining.
     */
    public Builder setUrlBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUrlBytes(value);
      return this;
    }

    /**
     * <code>string branch = 4;</code>
     * @return The branch.
     */
    @java.lang.Override
    public java.lang.String getBranch() {
      return instance.getBranch();
    }
    /**
     * <code>string branch = 4;</code>
     * @return The bytes for branch.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBranchBytes() {
      return instance.getBranchBytes();
    }
    /**
     * <code>string branch = 4;</code>
     * @param value The branch to set.
     * @return This builder for chaining.
     */
    public Builder setBranch(
        java.lang.String value) {
      copyOnWrite();
      instance.setBranch(value);
      return this;
    }
    /**
     * <code>string branch = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearBranch() {
      copyOnWrite();
      instance.clearBranch();
      return this;
    }
    /**
     * <code>string branch = 4;</code>
     * @param value The bytes for branch to set.
     * @return This builder for chaining.
     */
    public Builder setBranchBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setBranchBytes(value);
      return this;
    }

    /**
     * <pre>
     * The last view's verdicts, so a switcher can show how each repository is
     * doing without opening it. Absent until a repository has been read once —
     * which is why these are statuses and not booleans: "not known yet" is a
     * different thing from "nothing reported".
     * </pre>
     *
     * <code>.clarity.v1.Status ci = 9;</code>
     * @return The enum numeric value on the wire for ci.
     */
    @java.lang.Override
    public int getCiValue() {
      return instance.getCiValue();
    }
    /**
     * <pre>
     * The last view's verdicts, so a switcher can show how each repository is
     * doing without opening it. Absent until a repository has been read once —
     * which is why these are statuses and not booleans: "not known yet" is a
     * different thing from "nothing reported".
     * </pre>
     *
     * <code>.clarity.v1.Status ci = 9;</code>
     * @param value The ci to set.
     * @return This builder for chaining.
     */
    public Builder setCiValue(int value) {
      copyOnWrite();
      instance.setCiValue(value);
      return this;
    }
    /**
     * <pre>
     * The last view's verdicts, so a switcher can show how each repository is
     * doing without opening it. Absent until a repository has been read once —
     * which is why these are statuses and not booleans: "not known yet" is a
     * different thing from "nothing reported".
     * </pre>
     *
     * <code>.clarity.v1.Status ci = 9;</code>
     * @return The ci.
     */
    @java.lang.Override
    public dev.ezcd.clarity.proto.Status getCi() {
      return instance.getCi();
    }
    /**
     * <pre>
     * The last view's verdicts, so a switcher can show how each repository is
     * doing without opening it. Absent until a repository has been read once —
     * which is why these are statuses and not booleans: "not known yet" is a
     * different thing from "nothing reported".
     * </pre>
     *
     * <code>.clarity.v1.Status ci = 9;</code>
     * @param value The enum numeric value on the wire for ci to set.
     * @return This builder for chaining.
     */
    public Builder setCi(dev.ezcd.clarity.proto.Status value) {
      copyOnWrite();
      instance.setCi(value);
      return this;
    }
    /**
     * <pre>
     * The last view's verdicts, so a switcher can show how each repository is
     * doing without opening it. Absent until a repository has been read once —
     * which is why these are statuses and not booleans: "not known yet" is a
     * different thing from "nothing reported".
     * </pre>
     *
     * <code>.clarity.v1.Status ci = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearCi() {
      copyOnWrite();
      instance.clearCi();
      return this;
    }

    /**
     * <code>.clarity.v1.Status deploy = 10;</code>
     * @return The enum numeric value on the wire for deploy.
     */
    @java.lang.Override
    public int getDeployValue() {
      return instance.getDeployValue();
    }
    /**
     * <code>.clarity.v1.Status deploy = 10;</code>
     * @param value The deploy to set.
     * @return This builder for chaining.
     */
    public Builder setDeployValue(int value) {
      copyOnWrite();
      instance.setDeployValue(value);
      return this;
    }
    /**
     * <code>.clarity.v1.Status deploy = 10;</code>
     * @return The deploy.
     */
    @java.lang.Override
    public dev.ezcd.clarity.proto.Status getDeploy() {
      return instance.getDeploy();
    }
    /**
     * <code>.clarity.v1.Status deploy = 10;</code>
     * @param value The enum numeric value on the wire for deploy to set.
     * @return This builder for chaining.
     */
    public Builder setDeploy(dev.ezcd.clarity.proto.Status value) {
      copyOnWrite();
      instance.setDeploy(value);
      return this;
    }
    /**
     * <code>.clarity.v1.Status deploy = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeploy() {
      copyOnWrite();
      instance.clearDeploy();
      return this;
    }

    /**
     * <pre>
     * One entry per deploy target, in the order the tabs show them. A switcher
     * row draws one glyph each, with no names, and never hides one.
     * </pre>
     *
     * <code>repeated .clarity.v1.FlowSummary flows = 11;</code>
     */
    @java.lang.Override
    public java.util.List<dev.ezcd.clarity.proto.FlowSummary> getFlowsList() {
      return java.util.Collections.unmodifiableList(
          instance.getFlowsList());
    }
    /**
     * <pre>
     * One entry per deploy target, in the order the tabs show them. A switcher
     * row draws one glyph each, with no names, and never hides one.
     * </pre>
     *
     * <code>repeated .clarity.v1.FlowSummary flows = 11;</code>
     */
    @java.lang.Override
    public int getFlowsCount() {
      return instance.getFlowsCount();
    }/**
     * <pre>
     * One entry per deploy target, in the order the tabs show them. A switcher
     * row draws one glyph each, with no names, and never hides one.
     * </pre>
     *
     * <code>repeated .clarity.v1.FlowSummary flows = 11;</code>
     */
    @java.lang.Override
    public dev.ezcd.clarity.proto.FlowSummary getFlows(int index) {
      return instance.getFlows(index);
    }
    /**
     * <pre>
     * One entry per deploy target, in the order the tabs show them. A switcher
     * row draws one glyph each, with no names, and never hides one.
     * </pre>
     *
     * <code>repeated .clarity.v1.FlowSummary flows = 11;</code>
     */
    public Builder setFlows(
        int index, dev.ezcd.clarity.proto.FlowSummary value) {
      copyOnWrite();
      instance.setFlows(index, value);
      return this;
    }
    /**
     * <pre>
     * One entry per deploy target, in the order the tabs show them. A switcher
     * row draws one glyph each, with no names, and never hides one.
     * </pre>
     *
     * <code>repeated .clarity.v1.FlowSummary flows = 11;</code>
     */
    public Builder setFlows(
        int index, dev.ezcd.clarity.proto.FlowSummary.Builder builderForValue) {
      copyOnWrite();
      instance.setFlows(index,
          builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * One entry per deploy target, in the order the tabs show them. A switcher
     * row draws one glyph each, with no names, and never hides one.
     * </pre>
     *
     * <code>repeated .clarity.v1.FlowSummary flows = 11;</code>
     */
    public Builder addFlows(dev.ezcd.clarity.proto.FlowSummary value) {
      copyOnWrite();
      instance.addFlows(value);
      return this;
    }
    /**
     * <pre>
     * One entry per deploy target, in the order the tabs show them. A switcher
     * row draws one glyph each, with no names, and never hides one.
     * </pre>
     *
     * <code>repeated .clarity.v1.FlowSummary flows = 11;</code>
     */
    public Builder addFlows(
        int index, dev.ezcd.clarity.proto.FlowSummary value) {
      copyOnWrite();
      instance.addFlows(index, value);
      return this;
    }
    /**
     * <pre>
     * One entry per deploy target, in the order the tabs show them. A switcher
     * row draws one glyph each, with no names, and never hides one.
     * </pre>
     *
     * <code>repeated .clarity.v1.FlowSummary flows = 11;</code>
     */
    public Builder addFlows(
        dev.ezcd.clarity.proto.FlowSummary.Builder builderForValue) {
      copyOnWrite();
      instance.addFlows(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * One entry per deploy target, in the order the tabs show them. A switcher
     * row draws one glyph each, with no names, and never hides one.
     * </pre>
     *
     * <code>repeated .clarity.v1.FlowSummary flows = 11;</code>
     */
    public Builder addFlows(
        int index, dev.ezcd.clarity.proto.FlowSummary.Builder builderForValue) {
      copyOnWrite();
      instance.addFlows(index,
          builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * One entry per deploy target, in the order the tabs show them. A switcher
     * row draws one glyph each, with no names, and never hides one.
     * </pre>
     *
     * <code>repeated .clarity.v1.FlowSummary flows = 11;</code>
     */
    public Builder addAllFlows(
        java.lang.Iterable<? extends dev.ezcd.clarity.proto.FlowSummary> values) {
      copyOnWrite();
      instance.addAllFlows(values);
      return this;
    }
    /**
     * <pre>
     * One entry per deploy target, in the order the tabs show them. A switcher
     * row draws one glyph each, with no names, and never hides one.
     * </pre>
     *
     * <code>repeated .clarity.v1.FlowSummary flows = 11;</code>
     */
    public Builder clearFlows() {
      copyOnWrite();
      instance.clearFlows();
      return this;
    }
    /**
     * <pre>
     * One entry per deploy target, in the order the tabs show them. A switcher
     * row draws one glyph each, with no names, and never hides one.
     * </pre>
     *
     * <code>repeated .clarity.v1.FlowSummary flows = 11;</code>
     */
    public Builder removeFlows(int index) {
      copyOnWrite();
      instance.removeFlows(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:clarity.v1.RepoSummary)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new dev.ezcd.clarity.proto.RepoSummary();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "id_",
            "name_",
            "url_",
            "branch_",
            "namespace_",
            "host_",
            "alias_",
            "ci_",
            "deploy_",
            "flows_",
            dev.ezcd.clarity.proto.FlowSummary.class,
          };
          java.lang.String info =
              "\u0000\n\u0000\u0000\u0001\u000b\n\u0000\u0001\u0000\u0001\u0208\u0002\u0208\u0003" +
              "\u0208\u0004\u0208\u0006\u0208\u0007\u0208\b\u0208\t\f\n\f\u000b\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<dev.ezcd.clarity.proto.RepoSummary> parser = PARSER;
        if (parser == null) {
          synchronized (dev.ezcd.clarity.proto.RepoSummary.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<dev.ezcd.clarity.proto.RepoSummary>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:clarity.v1.RepoSummary)
  private static final dev.ezcd.clarity.proto.RepoSummary DEFAULT_INSTANCE;
  static {
    RepoSummary defaultInstance = new RepoSummary();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      RepoSummary.class, defaultInstance);
  }

  public static dev.ezcd.clarity.proto.RepoSummary getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<RepoSummary> PARSER;

  public static com.google.protobuf.Parser<RepoSummary> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

