// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clarity/v1/view.proto

package dev.ezcd.clarity.proto;

/**
 * <pre>
 * SectionKind is one of the three lifecycle sections. They are a structural
 * frame rather than a list of what happens to be active: all three are always
 * present and always in this order, so a repository with nothing deployed
 * still reads as "nothing has been deployed" rather than as a missing section.
 * </pre>
 *
 * Protobuf enum {@code clarity.v1.SectionKind}
 */
public enum SectionKind
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>SECTION_KIND_UNSPECIFIED = 0;</code>
   */
  SECTION_KIND_UNSPECIFIED(0),
  /**
   * <pre>
   * landed, CI not green yet
   * </pre>
   *
   * <code>SECTION_KIND_HEAD = 1;</code>
   */
  SECTION_KIND_HEAD(1),
  /**
   * <pre>
   * green, waiting for a deploy
   * </pre>
   *
   * <code>SECTION_KIND_CI_PASSED = 2;</code>
   */
  SECTION_KIND_CI_PASSED(2),
  /**
   * <pre>
   * shipped
   * </pre>
   *
   * <code>SECTION_KIND_DEPLOYED = 3;</code>
   */
  SECTION_KIND_DEPLOYED(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>SECTION_KIND_UNSPECIFIED = 0;</code>
   */
  public static final int SECTION_KIND_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * landed, CI not green yet
   * </pre>
   *
   * <code>SECTION_KIND_HEAD = 1;</code>
   */
  public static final int SECTION_KIND_HEAD_VALUE = 1;
  /**
   * <pre>
   * green, waiting for a deploy
   * </pre>
   *
   * <code>SECTION_KIND_CI_PASSED = 2;</code>
   */
  public static final int SECTION_KIND_CI_PASSED_VALUE = 2;
  /**
   * <pre>
   * shipped
   * </pre>
   *
   * <code>SECTION_KIND_DEPLOYED = 3;</code>
   */
  public static final int SECTION_KIND_DEPLOYED_VALUE = 3;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static SectionKind valueOf(int value) {
    return forNumber(value);
  }

  public static SectionKind forNumber(int value) {
    switch (value) {
      case 0: return SECTION_KIND_UNSPECIFIED;
      case 1: return SECTION_KIND_HEAD;
      case 2: return SECTION_KIND_CI_PASSED;
      case 3: return SECTION_KIND_DEPLOYED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<SectionKind>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      SectionKind> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<SectionKind>() {
          @java.lang.Override
          public SectionKind findValueByNumber(int number) {
            return SectionKind.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return SectionKindVerifier.INSTANCE;
  }

  private static final class SectionKindVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new SectionKindVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return SectionKind.forNumber(number) != null;
          }
        };

  private final int value;

  private SectionKind(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:clarity.v1.SectionKind)
}

