// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clarity/v1/view.proto

package dev.ezcd.clarity.proto;

public interface SectionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clarity.v1.Section)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.clarity.v1.SectionKind kind = 1;</code>
   * @return The enum numeric value on the wire for kind.
   */
  int getKindValue();
  /**
   * <code>.clarity.v1.SectionKind kind = 1;</code>
   * @return The kind.
   */
  dev.ezcd.clarity.proto.SectionKind getKind();

  /**
   * <pre>
   * Label names the band: "HEAD", "CI Passed", "Deployed". Here rather than on
   * the client so three UIs cannot disagree about what to call it.
   * </pre>
   *
   * <code>string label = 2;</code>
   * @return The label.
   */
  java.lang.String getLabel();
  /**
   * <pre>
   * Label names the band: "HEAD", "CI Passed", "Deployed". Here rather than on
   * the client so three UIs cannot disagree about what to call it.
   * </pre>
   *
   * <code>string label = 2;</code>
   * @return The bytes for label.
   */
  com.google.protobuf.ByteString
      getLabelBytes();

  /**
   * <code>repeated .clarity.v1.Commit commits = 3;</code>
   */
  java.util.List<dev.ezcd.clarity.proto.Commit> 
      getCommitsList();
  /**
   * <code>repeated .clarity.v1.Commit commits = 3;</code>
   */
  dev.ezcd.clarity.proto.Commit getCommits(int index);
  /**
   * <code>repeated .clarity.v1.Commit commits = 3;</code>
   */
  int getCommitsCount();

  /**
   * <code>repeated .clarity.v1.Batch batches = 4;</code>
   */
  java.util.List<dev.ezcd.clarity.proto.Batch> 
      getBatchesList();
  /**
   * <code>repeated .clarity.v1.Batch batches = 4;</code>
   */
  dev.ezcd.clarity.proto.Batch getBatches(int index);
  /**
   * <code>repeated .clarity.v1.Batch batches = 4;</code>
   */
  int getBatchesCount();
}
