// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clarity/v1/view.proto

package dev.ezcd.clarity.proto;

public interface SectionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clarity.v1.Section)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.clarity.v1.SectionKind kind = 1;</code>
   * @return The enum numeric value on the wire for kind.
   */
  int getKindValue();
  /**
   * <code>.clarity.v1.SectionKind kind = 1;</code>
   * @return The kind.
   */
  dev.ezcd.clarity.proto.SectionKind getKind();

  /**
   * <pre>
   * Label names the band: "HEAD", "CI Passed", "Deployed". Here rather than on
   * the client so three UIs cannot disagree about what to call it.
   * </pre>
   *
   * <code>string label = 2;</code>
   * @return The label.
   */
  java.lang.String getLabel();
  /**
   * <pre>
   * Label names the band: "HEAD", "CI Passed", "Deployed". Here rather than on
   * the client so three UIs cannot disagree about what to call it.
   * </pre>
   *
   * <code>string label = 2;</code>
   * @return The bytes for label.
   */
  com.google.protobuf.ByteString
      getLabelBytes();

  /**
   * <code>repeated .clarity.v1.Commit commits = 3;</code>
   */
  java.util.List<dev.ezcd.clarity.proto.Commit> 
      getCommitsList();
  /**
   * <code>repeated .clarity.v1.Commit commits = 3;</code>
   */
  dev.ezcd.clarity.proto.Commit getCommits(int index);
  /**
   * <code>repeated .clarity.v1.Commit commits = 3;</code>
   */
  int getCommitsCount();

  /**
   * <code>repeated .clarity.v1.Batch batches = 4;</code>
   */
  java.util.List<dev.ezcd.clarity.proto.Batch> 
      getBatchesList();
  /**
   * <code>repeated .clarity.v1.Batch batches = 4;</code>
   */
  dev.ezcd.clarity.proto.Batch getBatches(int index);
  /**
   * <code>repeated .clarity.v1.Batch batches = 4;</code>
   */
  int getBatchesCount();

  /**
   * <pre>
   * Only on Deployed: this week's throughput, as the terminal puts it on the
   * right of the section rule — "W2026-40  3 deploys  2h 14m avg".
   * Empty when the window was truncated through this week's bucket, where the
   * count is unknown rather than zero: printing "0 deploys" above the very
   * deploys it denies is worse than printing nothing.
   * </pre>
   *
   * <code>string summary = 5;</code>
   * @return The summary.
   */
  java.lang.String getSummary();
  /**
   * <pre>
   * Only on Deployed: this week's throughput, as the terminal puts it on the
   * right of the section rule — "W2026-40  3 deploys  2h 14m avg".
   * Empty when the window was truncated through this week's bucket, where the
   * count is unknown rather than zero: printing "0 deploys" above the very
   * deploys it denies is worse than printing nothing.
   * </pre>
   *
   * <code>string summary = 5;</code>
   * @return The bytes for summary.
   */
  com.google.protobuf.ByteString
      getSummaryBytes();
}
