// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clarity/v1/view.proto

package dev.ezcd.clarity.proto;

/**
 * <pre>
 * Section is one of the three lifecycle bands.
 * A section holds loose commits, batches, or both: HEAD is only loose commits,
 * Deployed is only batches, and CI Passed is the one that has both — commits
 * queued for the next deploy, then any attempt that has not landed yet.
 * </pre>
 *
 * Protobuf type {@code clarity.v1.Section}
 */
public  final class Section extends
    com.google.protobuf.GeneratedMessageLite<
        Section, Section.Builder> implements
    // @@protoc_insertion_point(message_implements:clarity.v1.Section)
    SectionOrBuilder {
  private Section() {
    label_ = "";
    commits_ = emptyProtobufList();
    batches_ = emptyProtobufList();
    summary_ = "";
  }
  public static final int KIND_FIELD_NUMBER = 1;
  private int kind_;
  /**
   * <code>.clarity.v1.SectionKind kind = 1;</code>
   * @return The enum numeric value on the wire for kind.
   */
  @java.lang.Override
  public int getKindValue() {
    return kind_;
  }
  /**
   * <code>.clarity.v1.SectionKind kind = 1;</code>
   * @return The kind.
   */
  @java.lang.Override
  public dev.ezcd.clarity.proto.SectionKind getKind() {
    dev.ezcd.clarity.proto.SectionKind result = dev.ezcd.clarity.proto.SectionKind.forNumber(kind_);
    return result == null ? dev.ezcd.clarity.proto.SectionKind.UNRECOGNIZED : result;
  }
  /**
   * <code>.clarity.v1.SectionKind kind = 1;</code>
   * @param value The enum numeric value on the wire for kind to set.
   */
  private void setKindValue(int value) {
      kind_ = value;
  }
  /**
   * <code>.clarity.v1.SectionKind kind = 1;</code>
   * @param value The kind to set.
   */
  private void setKind(dev.ezcd.clarity.proto.SectionKind value) {
    kind_ = value.getNumber();
    
  }
  /**
   * <code>.clarity.v1.SectionKind kind = 1;</code>
   */
  private void clearKind() {
    
    kind_ = 0;
  }

  public static final int LABEL_FIELD_NUMBER = 2;
  private java.lang.String label_;
  /**
   * <pre>
   * Label names the band: "HEAD", "CI Passed", "Deployed". Here rather than on
   * the client so three UIs cannot disagree about what to call it.
   * </pre>
   *
   * <code>string label = 2;</code>
   * @return The label.
   */
  @java.lang.Override
  public java.lang.String getLabel() {
    return label_;
  }
  /**
   * <pre>
   * Label names the band: "HEAD", "CI Passed", "Deployed". Here rather than on
   * the client so three UIs cannot disagree about what to call it.
   * </pre>
   *
   * <code>string label = 2;</code>
   * @return The bytes for label.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLabelBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(label_);
  }
  /**
   * <pre>
   * Label names the band: "HEAD", "CI Passed", "Deployed". Here rather than on
   * the client so three UIs cannot disagree about what to call it.
   * </pre>
   *
   * <code>string label = 2;</code>
   * @param value The label to set.
   */
  private void setLabel(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    label_ = value;
  }
  /**
   * <pre>
   * Label names the band: "HEAD", "CI Passed", "Deployed". Here rather than on
   * the client so three UIs cannot disagree about what to call it.
   * </pre>
   *
   * <code>string label = 2;</code>
   */
  private void clearLabel() {
    
    label_ = getDefaultInstance().getLabel();
  }
  /**
   * <pre>
   * Label names the band: "HEAD", "CI Passed", "Deployed". Here rather than on
   * the client so three UIs cannot disagree about what to call it.
   * </pre>
   *
   * <code>string label = 2;</code>
   * @param value The bytes for label to set.
   */
  private void setLabelBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    label_ = value.toStringUtf8();
    
  }

  public static final int COMMITS_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.ProtobufList<dev.ezcd.clarity.proto.Commit> commits_;
  /**
   * <code>repeated .clarity.v1.Commit commits = 3;</code>
   */
  @java.lang.Override
  public java.util.List<dev.ezcd.clarity.proto.Commit> getCommitsList() {
    return commits_;
  }
  /**
   * <code>repeated .clarity.v1.Commit commits = 3;</code>
   */
  public java.util.List<? extends dev.ezcd.clarity.proto.CommitOrBuilder> 
      getCommitsOrBuilderList() {
    return commits_;
  }
  /**
   * <code>repeated .clarity.v1.Commit commits = 3;</code>
   */
  @java.lang.Override
  public int getCommitsCount() {
    return commits_.size();
  }
  /**
   * <code>repeated .clarity.v1.Commit commits = 3;</code>
   */
  @java.lang.Override
  public dev.ezcd.clarity.proto.Commit getCommits(int index) {
    return commits_.get(index);
  }
  /**
   * <code>repeated .clarity.v1.Commit commits = 3;</code>
   */
  public dev.ezcd.clarity.proto.CommitOrBuilder getCommitsOrBuilder(
      int index) {
    return commits_.get(index);
  }
  private void ensureCommitsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<dev.ezcd.clarity.proto.Commit> tmp = commits_;
    if (!tmp.isModifiable()) {
      commits_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .clarity.v1.Commit commits = 3;</code>
   */
  private void setCommits(
      int index, dev.ezcd.clarity.proto.Commit value) {
    value.getClass();
  ensureCommitsIsMutable();
    commits_.set(index, value);
  }
  /**
   * <code>repeated .clarity.v1.Commit commits = 3;</code>
   */
  private void addCommits(dev.ezcd.clarity.proto.Commit value) {
    value.getClass();
  ensureCommitsIsMutable();
    commits_.add(value);
  }
  /**
   * <code>repeated .clarity.v1.Commit commits = 3;</code>
   */
  private void addCommits(
      int index, dev.ezcd.clarity.proto.Commit value) {
    value.getClass();
  ensureCommitsIsMutable();
    commits_.add(index, value);
  }
  /**
   * <code>repeated .clarity.v1.Commit commits = 3;</code>
   */
  private void addAllCommits(
      java.lang.Iterable<? extends dev.ezcd.clarity.proto.Commit> values) {
    ensureCommitsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, commits_);
  }
  /**
   * <code>repeated .clarity.v1.Commit commits = 3;</code>
   */
  private void clearCommits() {
    commits_ = emptyProtobufList();
  }
  /**
   * <code>repeated .clarity.v1.Commit commits = 3;</code>
   */
  private void removeCommits(int index) {
    ensureCommitsIsMutable();
    commits_.remove(index);
  }

  public static final int BATCHES_FIELD_NUMBER = 4;
  private com.google.protobuf.Internal.ProtobufList<dev.ezcd.clarity.proto.Batch> batches_;
  /**
   * <code>repeated .clarity.v1.Batch batches = 4;</code>
   */
  @java.lang.Override
  public java.util.List<dev.ezcd.clarity.proto.Batch> getBatchesList() {
    return batches_;
  }
  /**
   * <code>repeated .clarity.v1.Batch batches = 4;</code>
   */
  public java.util.List<? extends dev.ezcd.clarity.proto.BatchOrBuilder> 
      getBatchesOrBuilderList() {
    return batches_;
  }
  /**
   * <code>repeated .clarity.v1.Batch batches = 4;</code>
   */
  @java.lang.Override
  public int getBatchesCount() {
    return batches_.size();
  }
  /**
   * <code>repeated .clarity.v1.Batch batches = 4;</code>
   */
  @java.lang.Override
  public dev.ezcd.clarity.proto.Batch getBatches(int index) {
    return batches_.get(index);
  }
  /**
   * <code>repeated .clarity.v1.Batch batches = 4;</code>
   */
  public dev.ezcd.clarity.proto.BatchOrBuilder getBatchesOrBuilder(
      int index) {
    return batches_.get(index);
  }
  private void ensureBatchesIsMutable() {
    com.google.protobuf.Internal.ProtobufList<dev.ezcd.clarity.proto.Batch> tmp = batches_;
    if (!tmp.isModifiable()) {
      batches_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .clarity.v1.Batch batches = 4;</code>
   */
  private void setBatches(
      int index, dev.ezcd.clarity.proto.Batch value) {
    value.getClass();
  ensureBatchesIsMutable();
    batches_.set(index, value);
  }
  /**
   * <code>repeated .clarity.v1.Batch batches = 4;</code>
   */
  private void addBatches(dev.ezcd.clarity.proto.Batch value) {
    value.getClass();
  ensureBatchesIsMutable();
    batches_.add(value);
  }
  /**
   * <code>repeated .clarity.v1.Batch batches = 4;</code>
   */
  private void addBatches(
      int index, dev.ezcd.clarity.proto.Batch value) {
    value.getClass();
  ensureBatchesIsMutable();
    batches_.add(index, value);
  }
  /**
   * <code>repeated .clarity.v1.Batch batches = 4;</code>
   */
  private void addAllBatches(
      java.lang.Iterable<? extends dev.ezcd.clarity.proto.Batch> values) {
    ensureBatchesIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, batches_);
  }
  /**
   * <code>repeated .clarity.v1.Batch batches = 4;</code>
   */
  private void clearBatches() {
    batches_ = emptyProtobufList();
  }
  /**
   * <code>repeated .clarity.v1.Batch batches = 4;</code>
   */
  private void removeBatches(int index) {
    ensureBatchesIsMutable();
    batches_.remove(index);
  }

  public static final int SUMMARY_FIELD_NUMBER = 5;
  private java.lang.String summary_;
  /**
   * <pre>
   * Only on Deployed: this week's throughput, as the terminal puts it on the
   * right of the section rule — "W2026-40  3 deploys  2h 14m avg".
   * Empty when the window was truncated through this week's bucket, where the
   * count is unknown rather than zero: printing "0 deploys" above the very
   * deploys it denies is worse than printing nothing.
   * </pre>
   *
   * <code>string summary = 5;</code>
   * @return The summary.
   */
  @java.lang.Override
  public java.lang.String getSummary() {
    return summary_;
  }
  /**
   * <pre>
   * Only on Deployed: this week's throughput, as the terminal puts it on the
   * right of the section rule — "W2026-40  3 deploys  2h 14m avg".
   * Empty when the window was truncated through this week's bucket, where the
   * count is unknown rather than zero: printing "0 deploys" above the very
   * deploys it denies is worse than printing nothing.
   * </pre>
   *
   * <code>string summary = 5;</code>
   * @return The bytes for summary.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSummaryBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(summary_);
  }
  /**
   * <pre>
   * Only on Deployed: this week's throughput, as the terminal puts it on the
   * right of the section rule — "W2026-40  3 deploys  2h 14m avg".
   * Empty when the window was truncated through this week's bucket, where the
   * count is unknown rather than zero: printing "0 deploys" above the very
   * deploys it denies is worse than printing nothing.
   * </pre>
   *
   * <code>string summary = 5;</code>
   * @param value The summary to set.
   */
  private void setSummary(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    summary_ = value;
  }
  /**
   * <pre>
   * Only on Deployed: this week's throughput, as the terminal puts it on the
   * right of the section rule — "W2026-40  3 deploys  2h 14m avg".
   * Empty when the window was truncated through this week's bucket, where the
   * count is unknown rather than zero: printing "0 deploys" above the very
   * deploys it denies is worse than printing nothing.
   * </pre>
   *
   * <code>string summary = 5;</code>
   */
  private void clearSummary() {
    
    summary_ = getDefaultInstance().getSummary();
  }
  /**
   * <pre>
   * Only on Deployed: this week's throughput, as the terminal puts it on the
   * right of the section rule — "W2026-40  3 deploys  2h 14m avg".
   * Empty when the window was truncated through this week's bucket, where the
   * count is unknown rather than zero: printing "0 deploys" above the very
   * deploys it denies is worse than printing nothing.
   * </pre>
   *
   * <code>string summary = 5;</code>
   * @param value The bytes for summary to set.
   */
  private void setSummaryBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    summary_ = value.toStringUtf8();
    
  }

  public static dev.ezcd.clarity.proto.Section parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.Section parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.Section parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.Section parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.Section parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.Section parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.Section parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.Section parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.Section parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.Section parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.Section parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.Section parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(dev.ezcd.clarity.proto.Section prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Section is one of the three lifecycle bands.
   * A section holds loose commits, batches, or both: HEAD is only loose commits,
   * Deployed is only batches, and CI Passed is the one that has both — commits
   * queued for the next deploy, then any attempt that has not landed yet.
   * </pre>
   *
   * Protobuf type {@code clarity.v1.Section}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        dev.ezcd.clarity.proto.Section, Builder> implements
      // @@protoc_insertion_point(builder_implements:clarity.v1.Section)
      dev.ezcd.clarity.proto.SectionOrBuilder {
    // Construct using dev.ezcd.clarity.proto.Section.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.clarity.v1.SectionKind kind = 1;</code>
     * @return The enum numeric value on the wire for kind.
     */
    @java.lang.Override
    public int getKindValue() {
      return instance.getKindValue();
    }
    /**
     * <code>.clarity.v1.SectionKind kind = 1;</code>
     * @param value The kind to set.
     * @return This builder for chaining.
     */
    public Builder setKindValue(int value) {
      copyOnWrite();
      instance.setKindValue(value);
      return this;
    }
    /**
     * <code>.clarity.v1.SectionKind kind = 1;</code>
     * @return The kind.
     */
    @java.lang.Override
    public dev.ezcd.clarity.proto.SectionKind getKind() {
      return instance.getKind();
    }
    /**
     * <code>.clarity.v1.SectionKind kind = 1;</code>
     * @param value The enum numeric value on the wire for kind to set.
     * @return This builder for chaining.
     */
    public Builder setKind(dev.ezcd.clarity.proto.SectionKind value) {
      copyOnWrite();
      instance.setKind(value);
      return this;
    }
    /**
     * <code>.clarity.v1.SectionKind kind = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearKind() {
      copyOnWrite();
      instance.clearKind();
      return this;
    }

    /**
     * <pre>
     * Label names the band: "HEAD", "CI Passed", "Deployed". Here rather than on
     * the client so three UIs cannot disagree about what to call it.
     * </pre>
     *
     * <code>string label = 2;</code>
     * @return The label.
     */
    @java.lang.Override
    public java.lang.String getLabel() {
      return instance.getLabel();
    }
    /**
     * <pre>
     * Label names the band: "HEAD", "CI Passed", "Deployed". Here rather than on
     * the client so three UIs cannot disagree about what to call it.
     * </pre>
     *
     * <code>string label = 2;</code>
     * @return The bytes for label.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLabelBytes() {
      return instance.getLabelBytes();
    }
    /**
     * <pre>
     * Label names the band: "HEAD", "CI Passed", "Deployed". Here rather than on
     * the client so three UIs cannot disagree about what to call it.
     * </pre>
     *
     * <code>string label = 2;</code>
     * @param value The label to set.
     * @return This builder for chaining.
     */
    public Builder setLabel(
        java.lang.String value) {
      copyOnWrite();
      instance.setLabel(value);
      return this;
    }
    /**
     * <pre>
     * Label names the band: "HEAD", "CI Passed", "Deployed". Here rather than on
     * the client so three UIs cannot disagree about what to call it.
     * </pre>
     *
     * <code>string label = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLabel() {
      copyOnWrite();
      instance.clearLabel();
      return this;
    }
    /**
     * <pre>
     * Label names the band: "HEAD", "CI Passed", "Deployed". Here rather than on
     * the client so three UIs cannot disagree about what to call it.
     * </pre>
     *
     * <code>string label = 2;</code>
     * @param value The bytes for label to set.
     * @return This builder for chaining.
     */
    public Builder setLabelBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setLabelBytes(value);
      return this;
    }

    /**
     * <code>repeated .clarity.v1.Commit commits = 3;</code>
     */
    @java.lang.Override
    public java.util.List<dev.ezcd.clarity.proto.Commit> getCommitsList() {
      return java.util.Collections.unmodifiableList(
          instance.getCommitsList());
    }
    /**
     * <code>repeated .clarity.v1.Commit commits = 3;</code>
     */
    @java.lang.Override
    public int getCommitsCount() {
      return instance.getCommitsCount();
    }/**
     * <code>repeated .clarity.v1.Commit commits = 3;</code>
     */
    @java.lang.Override
    public dev.ezcd.clarity.proto.Commit getCommits(int index) {
      return instance.getCommits(index);
    }
    /**
     * <code>repeated .clarity.v1.Commit commits = 3;</code>
     */
    public Builder setCommits(
        int index, dev.ezcd.clarity.proto.Commit value) {
      copyOnWrite();
      instance.setCommits(index, value);
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Commit commits = 3;</code>
     */
    public Builder setCommits(
        int index, dev.ezcd.clarity.proto.Commit.Builder builderForValue) {
      copyOnWrite();
      instance.setCommits(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Commit commits = 3;</code>
     */
    public Builder addCommits(dev.ezcd.clarity.proto.Commit value) {
      copyOnWrite();
      instance.addCommits(value);
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Commit commits = 3;</code>
     */
    public Builder addCommits(
        int index, dev.ezcd.clarity.proto.Commit value) {
      copyOnWrite();
      instance.addCommits(index, value);
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Commit commits = 3;</code>
     */
    public Builder addCommits(
        dev.ezcd.clarity.proto.Commit.Builder builderForValue) {
      copyOnWrite();
      instance.addCommits(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Commit commits = 3;</code>
     */
    public Builder addCommits(
        int index, dev.ezcd.clarity.proto.Commit.Builder builderForValue) {
      copyOnWrite();
      instance.addCommits(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Commit commits = 3;</code>
     */
    public Builder addAllCommits(
        java.lang.Iterable<? extends dev.ezcd.clarity.proto.Commit> values) {
      copyOnWrite();
      instance.addAllCommits(values);
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Commit commits = 3;</code>
     */
    public Builder clearCommits() {
      copyOnWrite();
      instance.clearCommits();
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Commit commits = 3;</code>
     */
    public Builder removeCommits(int index) {
      copyOnWrite();
      instance.removeCommits(index);
      return this;
    }

    /**
     * <code>repeated .clarity.v1.Batch batches = 4;</code>
     */
    @java.lang.Override
    public java.util.List<dev.ezcd.clarity.proto.Batch> getBatchesList() {
      return java.util.Collections.unmodifiableList(
          instance.getBatchesList());
    }
    /**
     * <code>repeated .clarity.v1.Batch batches = 4;</code>
     */
    @java.lang.Override
    public int getBatchesCount() {
      return instance.getBatchesCount();
    }/**
     * <code>repeated .clarity.v1.Batch batches = 4;</code>
     */
    @java.lang.Override
    public dev.ezcd.clarity.proto.Batch getBatches(int index) {
      return instance.getBatches(index);
    }
    /**
     * <code>repeated .clarity.v1.Batch batches = 4;</code>
     */
    public Builder setBatches(
        int index, dev.ezcd.clarity.proto.Batch value) {
      copyOnWrite();
      instance.setBatches(index, value);
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Batch batches = 4;</code>
     */
    public Builder setBatches(
        int index, dev.ezcd.clarity.proto.Batch.Builder builderForValue) {
      copyOnWrite();
      instance.setBatches(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Batch batches = 4;</code>
     */
    public Builder addBatches(dev.ezcd.clarity.proto.Batch value) {
      copyOnWrite();
      instance.addBatches(value);
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Batch batches = 4;</code>
     */
    public Builder addBatches(
        int index, dev.ezcd.clarity.proto.Batch value) {
      copyOnWrite();
      instance.addBatches(index, value);
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Batch batches = 4;</code>
     */
    public Builder addBatches(
        dev.ezcd.clarity.proto.Batch.Builder builderForValue) {
      copyOnWrite();
      instance.addBatches(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Batch batches = 4;</code>
     */
    public Builder addBatches(
        int index, dev.ezcd.clarity.proto.Batch.Builder builderForValue) {
      copyOnWrite();
      instance.addBatches(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Batch batches = 4;</code>
     */
    public Builder addAllBatches(
        java.lang.Iterable<? extends dev.ezcd.clarity.proto.Batch> values) {
      copyOnWrite();
      instance.addAllBatches(values);
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Batch batches = 4;</code>
     */
    public Builder clearBatches() {
      copyOnWrite();
      instance.clearBatches();
      return this;
    }
    /**
     * <code>repeated .clarity.v1.Batch batches = 4;</code>
     */
    public Builder removeBatches(int index) {
      copyOnWrite();
      instance.removeBatches(index);
      return this;
    }

    /**
     * <pre>
     * Only on Deployed: this week's throughput, as the terminal puts it on the
     * right of the section rule — "W2026-40  3 deploys  2h 14m avg".
     * Empty when the window was truncated through this week's bucket, where the
     * count is unknown rather than zero: printing "0 deploys" above the very
     * deploys it denies is worse than printing nothing.
     * </pre>
     *
     * <code>string summary = 5;</code>
     * @return The summary.
     */
    @java.lang.Override
    public java.lang.String getSummary() {
      return instance.getSummary();
    }
    /**
     * <pre>
     * Only on Deployed: this week's throughput, as the terminal puts it on the
     * right of the section rule — "W2026-40  3 deploys  2h 14m avg".
     * Empty when the window was truncated through this week's bucket, where the
     * count is unknown rather than zero: printing "0 deploys" above the very
     * deploys it denies is worse than printing nothing.
     * </pre>
     *
     * <code>string summary = 5;</code>
     * @return The bytes for summary.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSummaryBytes() {
      return instance.getSummaryBytes();
    }
    /**
     * <pre>
     * Only on Deployed: this week's throughput, as the terminal puts it on the
     * right of the section rule — "W2026-40  3 deploys  2h 14m avg".
     * Empty when the window was truncated through this week's bucket, where the
     * count is unknown rather than zero: printing "0 deploys" above the very
     * deploys it denies is worse than printing nothing.
     * </pre>
     *
     * <code>string summary = 5;</code>
     * @param value The summary to set.
     * @return This builder for chaining.
     */
    public Builder setSummary(
        java.lang.String value) {
      copyOnWrite();
      instance.setSummary(value);
      return this;
    }
    /**
     * <pre>
     * Only on Deployed: this week's throughput, as the terminal puts it on the
     * right of the section rule — "W2026-40  3 deploys  2h 14m avg".
     * Empty when the window was truncated through this week's bucket, where the
     * count is unknown rather than zero: printing "0 deploys" above the very
     * deploys it denies is worse than printing nothing.
     * </pre>
     *
     * <code>string summary = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSummary() {
      copyOnWrite();
      instance.clearSummary();
      return this;
    }
    /**
     * <pre>
     * Only on Deployed: this week's throughput, as the terminal puts it on the
     * right of the section rule — "W2026-40  3 deploys  2h 14m avg".
     * Empty when the window was truncated through this week's bucket, where the
     * count is unknown rather than zero: printing "0 deploys" above the very
     * deploys it denies is worse than printing nothing.
     * </pre>
     *
     * <code>string summary = 5;</code>
     * @param value The bytes for summary to set.
     * @return This builder for chaining.
     */
    public Builder setSummaryBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSummaryBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:clarity.v1.Section)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new dev.ezcd.clarity.proto.Section();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "kind_",
            "label_",
            "commits_",
            dev.ezcd.clarity.proto.Commit.class,
            "batches_",
            dev.ezcd.clarity.proto.Batch.class,
            "summary_",
          };
          java.lang.String info =
              "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0000\u0002\u0000\u0001\f\u0002\u0208" +
              "\u0003\u001b\u0004\u001b\u0005\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<dev.ezcd.clarity.proto.Section> parser = PARSER;
        if (parser == null) {
          synchronized (dev.ezcd.clarity.proto.Section.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<dev.ezcd.clarity.proto.Section>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:clarity.v1.Section)
  private static final dev.ezcd.clarity.proto.Section DEFAULT_INSTANCE;
  static {
    Section defaultInstance = new Section();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Section.class, defaultInstance);
  }

  public static dev.ezcd.clarity.proto.Section getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Section> PARSER;

  public static com.google.protobuf.Parser<Section> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

