// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clarity/v1/view.proto

package dev.ezcd.clarity.proto;

/**
 * <pre>
 * Status is the resolved state of a stage. Semantic, not visual — the glyph
 * and the colour are the platform's choice, and the terminal's ✓/✗ were
 * picked for a greyscale-safe palette that means nothing on a phone.
 * </pre>
 *
 * Protobuf enum {@code clarity.v1.Status}
 */
public enum Status
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>STATUS_UNSPECIFIED = 0;</code>
   */
  STATUS_UNSPECIFIED(0),
  /**
   * <pre>
   * nothing reported
   * </pre>
   *
   * <code>STATUS_NONE = 1;</code>
   */
  STATUS_NONE(1),
  /**
   * <pre>
   * in flight
   * </pre>
   *
   * <code>STATUS_STARTED = 2;</code>
   */
  STATUS_STARTED(2),
  /**
   * <code>STATUS_PASSED = 3;</code>
   */
  STATUS_PASSED(3),
  /**
   * <code>STATUS_FAILED = 4;</code>
   */
  STATUS_FAILED(4),
  /**
   * <code>STATUS_SKIPPED = 5;</code>
   */
  STATUS_SKIPPED(5),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>STATUS_UNSPECIFIED = 0;</code>
   */
  public static final int STATUS_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * nothing reported
   * </pre>
   *
   * <code>STATUS_NONE = 1;</code>
   */
  public static final int STATUS_NONE_VALUE = 1;
  /**
   * <pre>
   * in flight
   * </pre>
   *
   * <code>STATUS_STARTED = 2;</code>
   */
  public static final int STATUS_STARTED_VALUE = 2;
  /**
   * <code>STATUS_PASSED = 3;</code>
   */
  public static final int STATUS_PASSED_VALUE = 3;
  /**
   * <code>STATUS_FAILED = 4;</code>
   */
  public static final int STATUS_FAILED_VALUE = 4;
  /**
   * <code>STATUS_SKIPPED = 5;</code>
   */
  public static final int STATUS_SKIPPED_VALUE = 5;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Status valueOf(int value) {
    return forNumber(value);
  }

  public static Status forNumber(int value) {
    switch (value) {
      case 0: return STATUS_UNSPECIFIED;
      case 1: return STATUS_NONE;
      case 2: return STATUS_STARTED;
      case 3: return STATUS_PASSED;
      case 4: return STATUS_FAILED;
      case 5: return STATUS_SKIPPED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Status>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Status> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Status>() {
          @java.lang.Override
          public Status findValueByNumber(int number) {
            return Status.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return StatusVerifier.INSTANCE;
  }

  private static final class StatusVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new StatusVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return Status.forNumber(number) != null;
          }
        };

  private final int value;

  private Status(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:clarity.v1.Status)
}

