// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clarity/v1/view.proto

package dev.ezcd.clarity.proto;

public interface SyncResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clarity.v1.SyncResult)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.clarity.v1.Outcome outcome = 1;</code>
   * @return The enum numeric value on the wire for outcome.
   */
  int getOutcomeValue();
  /**
   * <code>.clarity.v1.Outcome outcome = 1;</code>
   * @return The outcome.
   */
  dev.ezcd.clarity.proto.Outcome getOutcome();

  /**
   * <pre>
   * Message is already written for a person to read — git's own diagnosis,
   * usually — and is shown as-is rather than replaced with a category.
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * Message is already written for a person to read — git's own diagnosis,
   * usually — and is shown as-is rather than replaced with a category.
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * Set when the outcome is about a host key, for the dialog that asks.
   * </pre>
   *
   * <code>.clarity.v1.HostKey host_key = 3;</code>
   * @return Whether the hostKey field is set.
   */
  boolean hasHostKey();
  /**
   * <pre>
   * Set when the outcome is about a host key, for the dialog that asks.
   * </pre>
   *
   * <code>.clarity.v1.HostKey host_key = 3;</code>
   * @return The hostKey.
   */
  dev.ezcd.clarity.proto.HostKey getHostKey();

  /**
   * <pre>
   * The raw stderr behind an authentication failure, for the "Show git output"
   * disclosure. Empty when there is nothing more to show than the message.
   * </pre>
   *
   * <code>string git_output = 4;</code>
   * @return The gitOutput.
   */
  java.lang.String getGitOutput();
  /**
   * <pre>
   * The raw stderr behind an authentication failure, for the "Show git output"
   * disclosure. Empty when there is nothing more to show than the message.
   * </pre>
   *
   * <code>string git_output = 4;</code>
   * @return The bytes for gitOutput.
   */
  com.google.protobuf.ByteString
      getGitOutputBytes();
}
