// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clarity/v1/view.proto

package dev.ezcd.clarity.proto;

/**
 * <pre>
 * SyncResult is what a fetch did, rather than whether it threw.
 * A fetch has outcomes a UI must tell apart and an exception cannot: a host
 * nobody has agreed to yet is a question, a rejected key is a fixable setup
 * step with its own screen, and everything else is a message. Matching on the
 * text of an error to find out which would be a parser for prose, in three
 * clients, that breaks when git rewords something.
 * </pre>
 *
 * Protobuf type {@code clarity.v1.SyncResult}
 */
public  final class SyncResult extends
    com.google.protobuf.GeneratedMessageLite<
        SyncResult, SyncResult.Builder> implements
    // @@protoc_insertion_point(message_implements:clarity.v1.SyncResult)
    SyncResultOrBuilder {
  private SyncResult() {
    message_ = "";
    gitOutput_ = "";
  }
  public static final int OUTCOME_FIELD_NUMBER = 1;
  private int outcome_;
  /**
   * <code>.clarity.v1.Outcome outcome = 1;</code>
   * @return The enum numeric value on the wire for outcome.
   */
  @java.lang.Override
  public int getOutcomeValue() {
    return outcome_;
  }
  /**
   * <code>.clarity.v1.Outcome outcome = 1;</code>
   * @return The outcome.
   */
  @java.lang.Override
  public dev.ezcd.clarity.proto.Outcome getOutcome() {
    dev.ezcd.clarity.proto.Outcome result = dev.ezcd.clarity.proto.Outcome.forNumber(outcome_);
    return result == null ? dev.ezcd.clarity.proto.Outcome.UNRECOGNIZED : result;
  }
  /**
   * <code>.clarity.v1.Outcome outcome = 1;</code>
   * @param value The enum numeric value on the wire for outcome to set.
   */
  private void setOutcomeValue(int value) {
      outcome_ = value;
  }
  /**
   * <code>.clarity.v1.Outcome outcome = 1;</code>
   * @param value The outcome to set.
   */
  private void setOutcome(dev.ezcd.clarity.proto.Outcome value) {
    outcome_ = value.getNumber();
    
  }
  /**
   * <code>.clarity.v1.Outcome outcome = 1;</code>
   */
  private void clearOutcome() {
    
    outcome_ = 0;
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  private java.lang.String message_;
  /**
   * <pre>
   * Message is already written for a person to read — git's own diagnosis,
   * usually — and is shown as-is rather than replaced with a category.
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    return message_;
  }
  /**
   * <pre>
   * Message is already written for a person to read — git's own diagnosis,
   * usually — and is shown as-is rather than replaced with a category.
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(message_);
  }
  /**
   * <pre>
   * Message is already written for a person to read — git's own diagnosis,
   * usually — and is shown as-is rather than replaced with a category.
   * </pre>
   *
   * <code>string message = 2;</code>
   * @param value The message to set.
   */
  private void setMessage(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    message_ = value;
  }
  /**
   * <pre>
   * Message is already written for a person to read — git's own diagnosis,
   * usually — and is shown as-is rather than replaced with a category.
   * </pre>
   *
   * <code>string message = 2;</code>
   */
  private void clearMessage() {
    
    message_ = getDefaultInstance().getMessage();
  }
  /**
   * <pre>
   * Message is already written for a person to read — git's own diagnosis,
   * usually — and is shown as-is rather than replaced with a category.
   * </pre>
   *
   * <code>string message = 2;</code>
   * @param value The bytes for message to set.
   */
  private void setMessageBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    message_ = value.toStringUtf8();
    
  }

  public static final int HOST_KEY_FIELD_NUMBER = 3;
  private dev.ezcd.clarity.proto.HostKey hostKey_;
  /**
   * <pre>
   * Set when the outcome is about a host key, for the dialog that asks.
   * </pre>
   *
   * <code>.clarity.v1.HostKey host_key = 3;</code>
   */
  @java.lang.Override
  public boolean hasHostKey() {
    return hostKey_ != null;
  }
  /**
   * <pre>
   * Set when the outcome is about a host key, for the dialog that asks.
   * </pre>
   *
   * <code>.clarity.v1.HostKey host_key = 3;</code>
   */
  @java.lang.Override
  public dev.ezcd.clarity.proto.HostKey getHostKey() {
    return hostKey_ == null ? dev.ezcd.clarity.proto.HostKey.getDefaultInstance() : hostKey_;
  }
  /**
   * <pre>
   * Set when the outcome is about a host key, for the dialog that asks.
   * </pre>
   *
   * <code>.clarity.v1.HostKey host_key = 3;</code>
   */
  private void setHostKey(dev.ezcd.clarity.proto.HostKey value) {
    value.getClass();
  hostKey_ = value;
    
    }
  /**
   * <pre>
   * Set when the outcome is about a host key, for the dialog that asks.
   * </pre>
   *
   * <code>.clarity.v1.HostKey host_key = 3;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeHostKey(dev.ezcd.clarity.proto.HostKey value) {
    value.getClass();
  if (hostKey_ != null &&
        hostKey_ != dev.ezcd.clarity.proto.HostKey.getDefaultInstance()) {
      hostKey_ =
        dev.ezcd.clarity.proto.HostKey.newBuilder(hostKey_).mergeFrom(value).buildPartial();
    } else {
      hostKey_ = value;
    }
    
  }
  /**
   * <pre>
   * Set when the outcome is about a host key, for the dialog that asks.
   * </pre>
   *
   * <code>.clarity.v1.HostKey host_key = 3;</code>
   */
  private void clearHostKey() {  hostKey_ = null;
    
  }

  public static final int GIT_OUTPUT_FIELD_NUMBER = 4;
  private java.lang.String gitOutput_;
  /**
   * <pre>
   * The raw stderr behind an authentication failure, for the "Show git output"
   * disclosure. Empty when there is nothing more to show than the message.
   * </pre>
   *
   * <code>string git_output = 4;</code>
   * @return The gitOutput.
   */
  @java.lang.Override
  public java.lang.String getGitOutput() {
    return gitOutput_;
  }
  /**
   * <pre>
   * The raw stderr behind an authentication failure, for the "Show git output"
   * disclosure. Empty when there is nothing more to show than the message.
   * </pre>
   *
   * <code>string git_output = 4;</code>
   * @return The bytes for gitOutput.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGitOutputBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(gitOutput_);
  }
  /**
   * <pre>
   * The raw stderr behind an authentication failure, for the "Show git output"
   * disclosure. Empty when there is nothing more to show than the message.
   * </pre>
   *
   * <code>string git_output = 4;</code>
   * @param value The gitOutput to set.
   */
  private void setGitOutput(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    gitOutput_ = value;
  }
  /**
   * <pre>
   * The raw stderr behind an authentication failure, for the "Show git output"
   * disclosure. Empty when there is nothing more to show than the message.
   * </pre>
   *
   * <code>string git_output = 4;</code>
   */
  private void clearGitOutput() {
    
    gitOutput_ = getDefaultInstance().getGitOutput();
  }
  /**
   * <pre>
   * The raw stderr behind an authentication failure, for the "Show git output"
   * disclosure. Empty when there is nothing more to show than the message.
   * </pre>
   *
   * <code>string git_output = 4;</code>
   * @param value The bytes for gitOutput to set.
   */
  private void setGitOutputBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    gitOutput_ = value.toStringUtf8();
    
  }

  public static dev.ezcd.clarity.proto.SyncResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.SyncResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.SyncResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.SyncResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.SyncResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.SyncResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.SyncResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.SyncResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.SyncResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.SyncResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.SyncResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.SyncResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(dev.ezcd.clarity.proto.SyncResult prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * SyncResult is what a fetch did, rather than whether it threw.
   * A fetch has outcomes a UI must tell apart and an exception cannot: a host
   * nobody has agreed to yet is a question, a rejected key is a fixable setup
   * step with its own screen, and everything else is a message. Matching on the
   * text of an error to find out which would be a parser for prose, in three
   * clients, that breaks when git rewords something.
   * </pre>
   *
   * Protobuf type {@code clarity.v1.SyncResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        dev.ezcd.clarity.proto.SyncResult, Builder> implements
      // @@protoc_insertion_point(builder_implements:clarity.v1.SyncResult)
      dev.ezcd.clarity.proto.SyncResultOrBuilder {
    // Construct using dev.ezcd.clarity.proto.SyncResult.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.clarity.v1.Outcome outcome = 1;</code>
     * @return The enum numeric value on the wire for outcome.
     */
    @java.lang.Override
    public int getOutcomeValue() {
      return instance.getOutcomeValue();
    }
    /**
     * <code>.clarity.v1.Outcome outcome = 1;</code>
     * @param value The outcome to set.
     * @return This builder for chaining.
     */
    public Builder setOutcomeValue(int value) {
      copyOnWrite();
      instance.setOutcomeValue(value);
      return this;
    }
    /**
     * <code>.clarity.v1.Outcome outcome = 1;</code>
     * @return The outcome.
     */
    @java.lang.Override
    public dev.ezcd.clarity.proto.Outcome getOutcome() {
      return instance.getOutcome();
    }
    /**
     * <code>.clarity.v1.Outcome outcome = 1;</code>
     * @param value The enum numeric value on the wire for outcome to set.
     * @return This builder for chaining.
     */
    public Builder setOutcome(dev.ezcd.clarity.proto.Outcome value) {
      copyOnWrite();
      instance.setOutcome(value);
      return this;
    }
    /**
     * <code>.clarity.v1.Outcome outcome = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOutcome() {
      copyOnWrite();
      instance.clearOutcome();
      return this;
    }

    /**
     * <pre>
     * Message is already written for a person to read — git's own diagnosis,
     * usually — and is shown as-is rather than replaced with a category.
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      return instance.getMessage();
    }
    /**
     * <pre>
     * Message is already written for a person to read — git's own diagnosis,
     * usually — and is shown as-is rather than replaced with a category.
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      return instance.getMessageBytes();
    }
    /**
     * <pre>
     * Message is already written for a person to read — git's own diagnosis,
     * usually — and is shown as-is rather than replaced with a category.
     * </pre>
     *
     * <code>string message = 2;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      copyOnWrite();
      instance.setMessage(value);
      return this;
    }
    /**
     * <pre>
     * Message is already written for a person to read — git's own diagnosis,
     * usually — and is shown as-is rather than replaced with a category.
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      copyOnWrite();
      instance.clearMessage();
      return this;
    }
    /**
     * <pre>
     * Message is already written for a person to read — git's own diagnosis,
     * usually — and is shown as-is rather than replaced with a category.
     * </pre>
     *
     * <code>string message = 2;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMessageBytes(value);
      return this;
    }

    /**
     * <pre>
     * Set when the outcome is about a host key, for the dialog that asks.
     * </pre>
     *
     * <code>.clarity.v1.HostKey host_key = 3;</code>
     */
    @java.lang.Override
    public boolean hasHostKey() {
      return instance.hasHostKey();
    }
    /**
     * <pre>
     * Set when the outcome is about a host key, for the dialog that asks.
     * </pre>
     *
     * <code>.clarity.v1.HostKey host_key = 3;</code>
     */
    @java.lang.Override
    public dev.ezcd.clarity.proto.HostKey getHostKey() {
      return instance.getHostKey();
    }
    /**
     * <pre>
     * Set when the outcome is about a host key, for the dialog that asks.
     * </pre>
     *
     * <code>.clarity.v1.HostKey host_key = 3;</code>
     */
    public Builder setHostKey(dev.ezcd.clarity.proto.HostKey value) {
      copyOnWrite();
      instance.setHostKey(value);
      return this;
      }
    /**
     * <pre>
     * Set when the outcome is about a host key, for the dialog that asks.
     * </pre>
     *
     * <code>.clarity.v1.HostKey host_key = 3;</code>
     */
    public Builder setHostKey(
        dev.ezcd.clarity.proto.HostKey.Builder builderForValue) {
      copyOnWrite();
      instance.setHostKey(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * Set when the outcome is about a host key, for the dialog that asks.
     * </pre>
     *
     * <code>.clarity.v1.HostKey host_key = 3;</code>
     */
    public Builder mergeHostKey(dev.ezcd.clarity.proto.HostKey value) {
      copyOnWrite();
      instance.mergeHostKey(value);
      return this;
    }
    /**
     * <pre>
     * Set when the outcome is about a host key, for the dialog that asks.
     * </pre>
     *
     * <code>.clarity.v1.HostKey host_key = 3;</code>
     */
    public Builder clearHostKey() {  copyOnWrite();
      instance.clearHostKey();
      return this;
    }

    /**
     * <pre>
     * The raw stderr behind an authentication failure, for the "Show git output"
     * disclosure. Empty when there is nothing more to show than the message.
     * </pre>
     *
     * <code>string git_output = 4;</code>
     * @return The gitOutput.
     */
    @java.lang.Override
    public java.lang.String getGitOutput() {
      return instance.getGitOutput();
    }
    /**
     * <pre>
     * The raw stderr behind an authentication failure, for the "Show git output"
     * disclosure. Empty when there is nothing more to show than the message.
     * </pre>
     *
     * <code>string git_output = 4;</code>
     * @return The bytes for gitOutput.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGitOutputBytes() {
      return instance.getGitOutputBytes();
    }
    /**
     * <pre>
     * The raw stderr behind an authentication failure, for the "Show git output"
     * disclosure. Empty when there is nothing more to show than the message.
     * </pre>
     *
     * <code>string git_output = 4;</code>
     * @param value The gitOutput to set.
     * @return This builder for chaining.
     */
    public Builder setGitOutput(
        java.lang.String value) {
      copyOnWrite();
      instance.setGitOutput(value);
      return this;
    }
    /**
     * <pre>
     * The raw stderr behind an authentication failure, for the "Show git output"
     * disclosure. Empty when there is nothing more to show than the message.
     * </pre>
     *
     * <code>string git_output = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearGitOutput() {
      copyOnWrite();
      instance.clearGitOutput();
      return this;
    }
    /**
     * <pre>
     * The raw stderr behind an authentication failure, for the "Show git output"
     * disclosure. Empty when there is nothing more to show than the message.
     * </pre>
     *
     * <code>string git_output = 4;</code>
     * @param value The bytes for gitOutput to set.
     * @return This builder for chaining.
     */
    public Builder setGitOutputBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setGitOutputBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:clarity.v1.SyncResult)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new dev.ezcd.clarity.proto.SyncResult();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "outcome_",
            "message_",
            "hostKey_",
            "gitOutput_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\f\u0002\u0208" +
              "\u0003\t\u0004\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<dev.ezcd.clarity.proto.SyncResult> parser = PARSER;
        if (parser == null) {
          synchronized (dev.ezcd.clarity.proto.SyncResult.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<dev.ezcd.clarity.proto.SyncResult>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:clarity.v1.SyncResult)
  private static final dev.ezcd.clarity.proto.SyncResult DEFAULT_INSTANCE;
  static {
    SyncResult defaultInstance = new SyncResult();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      SyncResult.class, defaultInstance);
  }

  public static dev.ezcd.clarity.proto.SyncResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<SyncResult> PARSER;

  public static com.google.protobuf.Parser<SyncResult> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

