// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clarity/v1/view.proto

package dev.ezcd.clarity.proto;

public interface ViewOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clarity.v1.View)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string repo_name = 1;</code>
   * @return The repoName.
   */
  java.lang.String getRepoName();
  /**
   * <code>string repo_name = 1;</code>
   * @return The bytes for repoName.
   */
  com.google.protobuf.ByteString
      getRepoNameBytes();

  /**
   * <code>.clarity.v1.Status ci = 2;</code>
   * @return The enum numeric value on the wire for ci.
   */
  int getCiValue();
  /**
   * <code>.clarity.v1.Status ci = 2;</code>
   * @return The ci.
   */
  dev.ezcd.clarity.proto.Status getCi();

  /**
   * <code>.clarity.v1.Status deploy = 3;</code>
   * @return The enum numeric value on the wire for deploy.
   */
  int getDeployValue();
  /**
   * <code>.clarity.v1.Status deploy = 3;</code>
   * @return The deploy.
   */
  dev.ezcd.clarity.proto.Status getDeploy();

  /**
   * <pre>
   * Flows are the deploy targets, in display order. Always at least one: a
   * repo with no targets has exactly one, which is how the single-flow case
   * stays the same shape as the many-flow one.
   * </pre>
   *
   * <code>repeated .clarity.v1.Flow flows = 4;</code>
   */
  java.util.List<dev.ezcd.clarity.proto.Flow> 
      getFlowsList();
  /**
   * <pre>
   * Flows are the deploy targets, in display order. Always at least one: a
   * repo with no targets has exactly one, which is how the single-flow case
   * stays the same shape as the many-flow one.
   * </pre>
   *
   * <code>repeated .clarity.v1.Flow flows = 4;</code>
   */
  dev.ezcd.clarity.proto.Flow getFlows(int index);
  /**
   * <pre>
   * Flows are the deploy targets, in display order. Always at least one: a
   * repo with no targets has exactly one, which is how the single-flow case
   * stays the same shape as the many-flow one.
   * </pre>
   *
   * <code>repeated .clarity.v1.Flow flows = 4;</code>
   */
  int getFlowsCount();

  /**
   * <pre>
   * Truncated reports that the window ended before the repository did, so an
   * aggregate built from it is not the whole history. The limit is carried so
   * a client can say which number ended it.
   * </pre>
   *
   * <code>bool truncated = 5;</code>
   * @return The truncated.
   */
  boolean getTruncated();

  /**
   * <code>int32 limit = 6;</code>
   * @return The limit.
   */
  int getLimit();
}
