// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clarity/v1/view.proto

package dev.ezcd.clarity.proto;

/**
 * <pre>
 * ViewResult is a read of one repository: what to draw, and what moved since
 * the last read.
 * The two travel together because reading is what advances the baseline. A
 * plain View records the verdict it derived as a side effect, so a pipeline
 * that breaks while its own screen is open has its transition consumed by the
 * very read that drew it red — invisible to the background check afterwards.
 * That is the right outcome for a notification, which would be telling the user
 * something they watched happen, and the wrong one for silence: the app is
 * holding the news and saying nothing.
 * </pre>
 *
 * Protobuf type {@code clarity.v1.ViewResult}
 */
public  final class ViewResult extends
    com.google.protobuf.GeneratedMessageLite<
        ViewResult, ViewResult.Builder> implements
    // @@protoc_insertion_point(message_implements:clarity.v1.ViewResult)
    ViewResultOrBuilder {
  private ViewResult() {
    changes_ = emptyProtobufList();
  }
  public static final int VIEW_FIELD_NUMBER = 1;
  private dev.ezcd.clarity.proto.View view_;
  /**
   * <code>.clarity.v1.View view = 1;</code>
   */
  @java.lang.Override
  public boolean hasView() {
    return view_ != null;
  }
  /**
   * <code>.clarity.v1.View view = 1;</code>
   */
  @java.lang.Override
  public dev.ezcd.clarity.proto.View getView() {
    return view_ == null ? dev.ezcd.clarity.proto.View.getDefaultInstance() : view_;
  }
  /**
   * <code>.clarity.v1.View view = 1;</code>
   */
  private void setView(dev.ezcd.clarity.proto.View value) {
    value.getClass();
  view_ = value;
    
    }
  /**
   * <code>.clarity.v1.View view = 1;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeView(dev.ezcd.clarity.proto.View value) {
    value.getClass();
  if (view_ != null &&
        view_ != dev.ezcd.clarity.proto.View.getDefaultInstance()) {
      view_ =
        dev.ezcd.clarity.proto.View.newBuilder(view_).mergeFrom(value).buildPartial();
    } else {
      view_ = value;
    }
    
  }
  /**
   * <code>.clarity.v1.View view = 1;</code>
   */
  private void clearView() {  view_ = null;
    
  }

  public static final int CHANGES_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.ProtobufList<dev.ezcd.clarity.proto.Change> changes_;
  /**
   * <pre>
   * The crossings this read observed, for the client to announce however suits
   * a screen that is already showing them — a short tone rather than a
   * notification, in the way a messaging app chimes for the conversation you
   * are already in.
   * </pre>
   *
   * <code>repeated .clarity.v1.Change changes = 2;</code>
   */
  @java.lang.Override
  public java.util.List<dev.ezcd.clarity.proto.Change> getChangesList() {
    return changes_;
  }
  /**
   * <pre>
   * The crossings this read observed, for the client to announce however suits
   * a screen that is already showing them — a short tone rather than a
   * notification, in the way a messaging app chimes for the conversation you
   * are already in.
   * </pre>
   *
   * <code>repeated .clarity.v1.Change changes = 2;</code>
   */
  public java.util.List<? extends dev.ezcd.clarity.proto.ChangeOrBuilder> 
      getChangesOrBuilderList() {
    return changes_;
  }
  /**
   * <pre>
   * The crossings this read observed, for the client to announce however suits
   * a screen that is already showing them — a short tone rather than a
   * notification, in the way a messaging app chimes for the conversation you
   * are already in.
   * </pre>
   *
   * <code>repeated .clarity.v1.Change changes = 2;</code>
   */
  @java.lang.Override
  public int getChangesCount() {
    return changes_.size();
  }
  /**
   * <pre>
   * The crossings this read observed, for the client to announce however suits
   * a screen that is already showing them — a short tone rather than a
   * notification, in the way a messaging app chimes for the conversation you
   * are already in.
   * </pre>
   *
   * <code>repeated .clarity.v1.Change changes = 2;</code>
   */
  @java.lang.Override
  public dev.ezcd.clarity.proto.Change getChanges(int index) {
    return changes_.get(index);
  }
  /**
   * <pre>
   * The crossings this read observed, for the client to announce however suits
   * a screen that is already showing them — a short tone rather than a
   * notification, in the way a messaging app chimes for the conversation you
   * are already in.
   * </pre>
   *
   * <code>repeated .clarity.v1.Change changes = 2;</code>
   */
  public dev.ezcd.clarity.proto.ChangeOrBuilder getChangesOrBuilder(
      int index) {
    return changes_.get(index);
  }
  private void ensureChangesIsMutable() {
    com.google.protobuf.Internal.ProtobufList<dev.ezcd.clarity.proto.Change> tmp = changes_;
    if (!tmp.isModifiable()) {
      changes_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <pre>
   * The crossings this read observed, for the client to announce however suits
   * a screen that is already showing them — a short tone rather than a
   * notification, in the way a messaging app chimes for the conversation you
   * are already in.
   * </pre>
   *
   * <code>repeated .clarity.v1.Change changes = 2;</code>
   */
  private void setChanges(
      int index, dev.ezcd.clarity.proto.Change value) {
    value.getClass();
  ensureChangesIsMutable();
    changes_.set(index, value);
  }
  /**
   * <pre>
   * The crossings this read observed, for the client to announce however suits
   * a screen that is already showing them — a short tone rather than a
   * notification, in the way a messaging app chimes for the conversation you
   * are already in.
   * </pre>
   *
   * <code>repeated .clarity.v1.Change changes = 2;</code>
   */
  private void addChanges(dev.ezcd.clarity.proto.Change value) {
    value.getClass();
  ensureChangesIsMutable();
    changes_.add(value);
  }
  /**
   * <pre>
   * The crossings this read observed, for the client to announce however suits
   * a screen that is already showing them — a short tone rather than a
   * notification, in the way a messaging app chimes for the conversation you
   * are already in.
   * </pre>
   *
   * <code>repeated .clarity.v1.Change changes = 2;</code>
   */
  private void addChanges(
      int index, dev.ezcd.clarity.proto.Change value) {
    value.getClass();
  ensureChangesIsMutable();
    changes_.add(index, value);
  }
  /**
   * <pre>
   * The crossings this read observed, for the client to announce however suits
   * a screen that is already showing them — a short tone rather than a
   * notification, in the way a messaging app chimes for the conversation you
   * are already in.
   * </pre>
   *
   * <code>repeated .clarity.v1.Change changes = 2;</code>
   */
  private void addAllChanges(
      java.lang.Iterable<? extends dev.ezcd.clarity.proto.Change> values) {
    ensureChangesIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, changes_);
  }
  /**
   * <pre>
   * The crossings this read observed, for the client to announce however suits
   * a screen that is already showing them — a short tone rather than a
   * notification, in the way a messaging app chimes for the conversation you
   * are already in.
   * </pre>
   *
   * <code>repeated .clarity.v1.Change changes = 2;</code>
   */
  private void clearChanges() {
    changes_ = emptyProtobufList();
  }
  /**
   * <pre>
   * The crossings this read observed, for the client to announce however suits
   * a screen that is already showing them — a short tone rather than a
   * notification, in the way a messaging app chimes for the conversation you
   * are already in.
   * </pre>
   *
   * <code>repeated .clarity.v1.Change changes = 2;</code>
   */
  private void removeChanges(int index) {
    ensureChangesIsMutable();
    changes_.remove(index);
  }

  public static dev.ezcd.clarity.proto.ViewResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.ViewResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.ViewResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.ViewResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.ViewResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.ViewResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.ViewResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.ViewResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.ViewResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.ViewResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.ViewResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.ViewResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(dev.ezcd.clarity.proto.ViewResult prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * ViewResult is a read of one repository: what to draw, and what moved since
   * the last read.
   * The two travel together because reading is what advances the baseline. A
   * plain View records the verdict it derived as a side effect, so a pipeline
   * that breaks while its own screen is open has its transition consumed by the
   * very read that drew it red — invisible to the background check afterwards.
   * That is the right outcome for a notification, which would be telling the user
   * something they watched happen, and the wrong one for silence: the app is
   * holding the news and saying nothing.
   * </pre>
   *
   * Protobuf type {@code clarity.v1.ViewResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        dev.ezcd.clarity.proto.ViewResult, Builder> implements
      // @@protoc_insertion_point(builder_implements:clarity.v1.ViewResult)
      dev.ezcd.clarity.proto.ViewResultOrBuilder {
    // Construct using dev.ezcd.clarity.proto.ViewResult.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.clarity.v1.View view = 1;</code>
     */
    @java.lang.Override
    public boolean hasView() {
      return instance.hasView();
    }
    /**
     * <code>.clarity.v1.View view = 1;</code>
     */
    @java.lang.Override
    public dev.ezcd.clarity.proto.View getView() {
      return instance.getView();
    }
    /**
     * <code>.clarity.v1.View view = 1;</code>
     */
    public Builder setView(dev.ezcd.clarity.proto.View value) {
      copyOnWrite();
      instance.setView(value);
      return this;
      }
    /**
     * <code>.clarity.v1.View view = 1;</code>
     */
    public Builder setView(
        dev.ezcd.clarity.proto.View.Builder builderForValue) {
      copyOnWrite();
      instance.setView(builderForValue.build());
      return this;
    }
    /**
     * <code>.clarity.v1.View view = 1;</code>
     */
    public Builder mergeView(dev.ezcd.clarity.proto.View value) {
      copyOnWrite();
      instance.mergeView(value);
      return this;
    }
    /**
     * <code>.clarity.v1.View view = 1;</code>
     */
    public Builder clearView() {  copyOnWrite();
      instance.clearView();
      return this;
    }

    /**
     * <pre>
     * The crossings this read observed, for the client to announce however suits
     * a screen that is already showing them — a short tone rather than a
     * notification, in the way a messaging app chimes for the conversation you
     * are already in.
     * </pre>
     *
     * <code>repeated .clarity.v1.Change changes = 2;</code>
     */
    @java.lang.Override
    public java.util.List<dev.ezcd.clarity.proto.Change> getChangesList() {
      return java.util.Collections.unmodifiableList(
          instance.getChangesList());
    }
    /**
     * <pre>
     * The crossings this read observed, for the client to announce however suits
     * a screen that is already showing them — a short tone rather than a
     * notification, in the way a messaging app chimes for the conversation you
     * are already in.
     * </pre>
     *
     * <code>repeated .clarity.v1.Change changes = 2;</code>
     */
    @java.lang.Override
    public int getChangesCount() {
      return instance.getChangesCount();
    }/**
     * <pre>
     * The crossings this read observed, for the client to announce however suits
     * a screen that is already showing them — a short tone rather than a
     * notification, in the way a messaging app chimes for the conversation you
     * are already in.
     * </pre>
     *
     * <code>repeated .clarity.v1.Change changes = 2;</code>
     */
    @java.lang.Override
    public dev.ezcd.clarity.proto.Change getChanges(int index) {
      return instance.getChanges(index);
    }
    /**
     * <pre>
     * The crossings this read observed, for the client to announce however suits
     * a screen that is already showing them — a short tone rather than a
     * notification, in the way a messaging app chimes for the conversation you
     * are already in.
     * </pre>
     *
     * <code>repeated .clarity.v1.Change changes = 2;</code>
     */
    public Builder setChanges(
        int index, dev.ezcd.clarity.proto.Change value) {
      copyOnWrite();
      instance.setChanges(index, value);
      return this;
    }
    /**
     * <pre>
     * The crossings this read observed, for the client to announce however suits
     * a screen that is already showing them — a short tone rather than a
     * notification, in the way a messaging app chimes for the conversation you
     * are already in.
     * </pre>
     *
     * <code>repeated .clarity.v1.Change changes = 2;</code>
     */
    public Builder setChanges(
        int index, dev.ezcd.clarity.proto.Change.Builder builderForValue) {
      copyOnWrite();
      instance.setChanges(index,
          builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * The crossings this read observed, for the client to announce however suits
     * a screen that is already showing them — a short tone rather than a
     * notification, in the way a messaging app chimes for the conversation you
     * are already in.
     * </pre>
     *
     * <code>repeated .clarity.v1.Change changes = 2;</code>
     */
    public Builder addChanges(dev.ezcd.clarity.proto.Change value) {
      copyOnWrite();
      instance.addChanges(value);
      return this;
    }
    /**
     * <pre>
     * The crossings this read observed, for the client to announce however suits
     * a screen that is already showing them — a short tone rather than a
     * notification, in the way a messaging app chimes for the conversation you
     * are already in.
     * </pre>
     *
     * <code>repeated .clarity.v1.Change changes = 2;</code>
     */
    public Builder addChanges(
        int index, dev.ezcd.clarity.proto.Change value) {
      copyOnWrite();
      instance.addChanges(index, value);
      return this;
    }
    /**
     * <pre>
     * The crossings this read observed, for the client to announce however suits
     * a screen that is already showing them — a short tone rather than a
     * notification, in the way a messaging app chimes for the conversation you
     * are already in.
     * </pre>
     *
     * <code>repeated .clarity.v1.Change changes = 2;</code>
     */
    public Builder addChanges(
        dev.ezcd.clarity.proto.Change.Builder builderForValue) {
      copyOnWrite();
      instance.addChanges(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * The crossings this read observed, for the client to announce however suits
     * a screen that is already showing them — a short tone rather than a
     * notification, in the way a messaging app chimes for the conversation you
     * are already in.
     * </pre>
     *
     * <code>repeated .clarity.v1.Change changes = 2;</code>
     */
    public Builder addChanges(
        int index, dev.ezcd.clarity.proto.Change.Builder builderForValue) {
      copyOnWrite();
      instance.addChanges(index,
          builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * The crossings this read observed, for the client to announce however suits
     * a screen that is already showing them — a short tone rather than a
     * notification, in the way a messaging app chimes for the conversation you
     * are already in.
     * </pre>
     *
     * <code>repeated .clarity.v1.Change changes = 2;</code>
     */
    public Builder addAllChanges(
        java.lang.Iterable<? extends dev.ezcd.clarity.proto.Change> values) {
      copyOnWrite();
      instance.addAllChanges(values);
      return this;
    }
    /**
     * <pre>
     * The crossings this read observed, for the client to announce however suits
     * a screen that is already showing them — a short tone rather than a
     * notification, in the way a messaging app chimes for the conversation you
     * are already in.
     * </pre>
     *
     * <code>repeated .clarity.v1.Change changes = 2;</code>
     */
    public Builder clearChanges() {
      copyOnWrite();
      instance.clearChanges();
      return this;
    }
    /**
     * <pre>
     * The crossings this read observed, for the client to announce however suits
     * a screen that is already showing them — a short tone rather than a
     * notification, in the way a messaging app chimes for the conversation you
     * are already in.
     * </pre>
     *
     * <code>repeated .clarity.v1.Change changes = 2;</code>
     */
    public Builder removeChanges(int index) {
      copyOnWrite();
      instance.removeChanges(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:clarity.v1.ViewResult)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new dev.ezcd.clarity.proto.ViewResult();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "view_",
            "changes_",
            dev.ezcd.clarity.proto.Change.class,
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0001\u0000\u0001\t\u0002\u001b" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<dev.ezcd.clarity.proto.ViewResult> parser = PARSER;
        if (parser == null) {
          synchronized (dev.ezcd.clarity.proto.ViewResult.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<dev.ezcd.clarity.proto.ViewResult>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:clarity.v1.ViewResult)
  private static final dev.ezcd.clarity.proto.ViewResult DEFAULT_INSTANCE;
  static {
    ViewResult defaultInstance = new ViewResult();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ViewResult.class, defaultInstance);
  }

  public static dev.ezcd.clarity.proto.ViewResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ViewResult> PARSER;

  public static com.google.protobuf.Parser<ViewResult> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

