// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clarity/v1/view.proto

package dev.ezcd.clarity.proto;

public interface ViewResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clarity.v1.ViewResult)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.clarity.v1.View view = 1;</code>
   * @return Whether the view field is set.
   */
  boolean hasView();
  /**
   * <code>.clarity.v1.View view = 1;</code>
   * @return The view.
   */
  dev.ezcd.clarity.proto.View getView();

  /**
   * <pre>
   * The crossings this read observed, for the client to announce however suits
   * a screen that is already showing them — a short tone rather than a
   * notification, in the way a messaging app chimes for the conversation you
   * are already in.
   * </pre>
   *
   * <code>repeated .clarity.v1.Change changes = 2;</code>
   */
  java.util.List<dev.ezcd.clarity.proto.Change> 
      getChangesList();
  /**
   * <pre>
   * The crossings this read observed, for the client to announce however suits
   * a screen that is already showing them — a short tone rather than a
   * notification, in the way a messaging app chimes for the conversation you
   * are already in.
   * </pre>
   *
   * <code>repeated .clarity.v1.Change changes = 2;</code>
   */
  dev.ezcd.clarity.proto.Change getChanges(int index);
  /**
   * <pre>
   * The crossings this read observed, for the client to announce however suits
   * a screen that is already showing them — a short tone rather than a
   * notification, in the way a messaging app chimes for the conversation you
   * are already in.
   * </pre>
   *
   * <code>repeated .clarity.v1.Change changes = 2;</code>
   */
  int getChangesCount();
}
