// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clarity/v1/view.proto

package dev.ezcd.clarity.proto;

/**
 * <pre>
 * Week is one ISO week's DORA-shaped summary.
 * The bucket is the deploy date, which is DORA's own aggregation: a commit
 * authored three weeks ago and deployed today counts towards this week. A
 * ten-commit batch is one deploy, not ten.
 * </pre>
 *
 * Protobuf type {@code clarity.v1.Week}
 */
public  final class Week extends
    com.google.protobuf.GeneratedMessageLite<
        Week, Week.Builder> implements
    // @@protoc_insertion_point(message_implements:clarity.v1.Week)
    WeekOrBuilder {
  private Week() {
    label_ = "";
    sampleSeconds_ = emptyLongList();
  }
  public static final int LABEL_FIELD_NUMBER = 1;
  private java.lang.String label_;
  /**
   * <pre>
   * "W2026-39"
   * </pre>
   *
   * <code>string label = 1;</code>
   * @return The label.
   */
  @java.lang.Override
  public java.lang.String getLabel() {
    return label_;
  }
  /**
   * <pre>
   * "W2026-39"
   * </pre>
   *
   * <code>string label = 1;</code>
   * @return The bytes for label.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLabelBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(label_);
  }
  /**
   * <pre>
   * "W2026-39"
   * </pre>
   *
   * <code>string label = 1;</code>
   * @param value The label to set.
   */
  private void setLabel(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    label_ = value;
  }
  /**
   * <pre>
   * "W2026-39"
   * </pre>
   *
   * <code>string label = 1;</code>
   */
  private void clearLabel() {
    
    label_ = getDefaultInstance().getLabel();
  }
  /**
   * <pre>
   * "W2026-39"
   * </pre>
   *
   * <code>string label = 1;</code>
   * @param value The bytes for label to set.
   */
  private void setLabelBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    label_ = value.toStringUtf8();
    
  }

  public static final int DEPLOYS_FIELD_NUMBER = 2;
  private int deploys_;
  /**
   * <code>int32 deploys = 2;</code>
   * @return The deploys.
   */
  @java.lang.Override
  public int getDeploys() {
    return deploys_;
  }
  /**
   * <code>int32 deploys = 2;</code>
   * @param value The deploys to set.
   */
  private void setDeploys(int value) {
    
    deploys_ = value;
  }
  /**
   * <code>int32 deploys = 2;</code>
   */
  private void clearDeploys() {
    
    deploys_ = 0;
  }

  public static final int PLOT_FIELD_NUMBER = 3;
  private int plot_;
  /**
   * <code>.clarity.v1.Plot plot = 3;</code>
   * @return The enum numeric value on the wire for plot.
   */
  @java.lang.Override
  public int getPlotValue() {
    return plot_;
  }
  /**
   * <code>.clarity.v1.Plot plot = 3;</code>
   * @return The plot.
   */
  @java.lang.Override
  public dev.ezcd.clarity.proto.Plot getPlot() {
    dev.ezcd.clarity.proto.Plot result = dev.ezcd.clarity.proto.Plot.forNumber(plot_);
    return result == null ? dev.ezcd.clarity.proto.Plot.UNRECOGNIZED : result;
  }
  /**
   * <code>.clarity.v1.Plot plot = 3;</code>
   * @param value The enum numeric value on the wire for plot to set.
   */
  private void setPlotValue(int value) {
      plot_ = value;
  }
  /**
   * <code>.clarity.v1.Plot plot = 3;</code>
   * @param value The plot to set.
   */
  private void setPlot(dev.ezcd.clarity.proto.Plot value) {
    plot_ = value.getNumber();
    
  }
  /**
   * <code>.clarity.v1.Plot plot = 3;</code>
   */
  private void clearPlot() {
    
    plot_ = 0;
  }

  public static final int N_FIELD_NUMBER = 4;
  private int n_;
  /**
   * <pre>
   * How many commits contributed a lead time. Not the same as deploys: a
   * batch carries several commits, and a week can measure lead times from
   * batches whose own deploy event was never recorded.
   * </pre>
   *
   * <code>int32 n = 4;</code>
   * @return The n.
   */
  @java.lang.Override
  public int getN() {
    return n_;
  }
  /**
   * <pre>
   * How many commits contributed a lead time. Not the same as deploys: a
   * batch carries several commits, and a week can measure lead times from
   * batches whose own deploy event was never recorded.
   * </pre>
   *
   * <code>int32 n = 4;</code>
   * @param value The n to set.
   */
  private void setN(int value) {
    
    n_ = value;
  }
  /**
   * <pre>
   * How many commits contributed a lead time. Not the same as deploys: a
   * batch carries several commits, and a week can measure lead times from
   * batches whose own deploy event was never recorded.
   * </pre>
   *
   * <code>int32 n = 4;</code>
   */
  private void clearN() {
    
    n_ = 0;
  }

  public static final int MIN_SECONDS_FIELD_NUMBER = 5;
  private long minSeconds_;
  /**
   * <pre>
   * The five-number summary, in seconds. The median is the headline rather
   * than a mean: lead times are strongly right-skewed, so one commit that sat
   * over a weekend drags an average badly. The quartiles carry the spread,
   * which matters as much as the middle — a two-hour median with a three-day
   * p75 is a problem the median alone hides.
   * </pre>
   *
   * <code>int64 min_seconds = 5;</code>
   * @return The minSeconds.
   */
  @java.lang.Override
  public long getMinSeconds() {
    return minSeconds_;
  }
  /**
   * <pre>
   * The five-number summary, in seconds. The median is the headline rather
   * than a mean: lead times are strongly right-skewed, so one commit that sat
   * over a weekend drags an average badly. The quartiles carry the spread,
   * which matters as much as the middle — a two-hour median with a three-day
   * p75 is a problem the median alone hides.
   * </pre>
   *
   * <code>int64 min_seconds = 5;</code>
   * @param value The minSeconds to set.
   */
  private void setMinSeconds(long value) {
    
    minSeconds_ = value;
  }
  /**
   * <pre>
   * The five-number summary, in seconds. The median is the headline rather
   * than a mean: lead times are strongly right-skewed, so one commit that sat
   * over a weekend drags an average badly. The quartiles carry the spread,
   * which matters as much as the middle — a two-hour median with a three-day
   * p75 is a problem the median alone hides.
   * </pre>
   *
   * <code>int64 min_seconds = 5;</code>
   */
  private void clearMinSeconds() {
    
    minSeconds_ = 0L;
  }

  public static final int P25_SECONDS_FIELD_NUMBER = 6;
  private long p25Seconds_;
  /**
   * <code>int64 p25_seconds = 6;</code>
   * @return The p25Seconds.
   */
  @java.lang.Override
  public long getP25Seconds() {
    return p25Seconds_;
  }
  /**
   * <code>int64 p25_seconds = 6;</code>
   * @param value The p25Seconds to set.
   */
  private void setP25Seconds(long value) {
    
    p25Seconds_ = value;
  }
  /**
   * <code>int64 p25_seconds = 6;</code>
   */
  private void clearP25Seconds() {
    
    p25Seconds_ = 0L;
  }

  public static final int P50_SECONDS_FIELD_NUMBER = 7;
  private long p50Seconds_;
  /**
   * <code>int64 p50_seconds = 7;</code>
   * @return The p50Seconds.
   */
  @java.lang.Override
  public long getP50Seconds() {
    return p50Seconds_;
  }
  /**
   * <code>int64 p50_seconds = 7;</code>
   * @param value The p50Seconds to set.
   */
  private void setP50Seconds(long value) {
    
    p50Seconds_ = value;
  }
  /**
   * <code>int64 p50_seconds = 7;</code>
   */
  private void clearP50Seconds() {
    
    p50Seconds_ = 0L;
  }

  public static final int P75_SECONDS_FIELD_NUMBER = 8;
  private long p75Seconds_;
  /**
   * <code>int64 p75_seconds = 8;</code>
   * @return The p75Seconds.
   */
  @java.lang.Override
  public long getP75Seconds() {
    return p75Seconds_;
  }
  /**
   * <code>int64 p75_seconds = 8;</code>
   * @param value The p75Seconds to set.
   */
  private void setP75Seconds(long value) {
    
    p75Seconds_ = value;
  }
  /**
   * <code>int64 p75_seconds = 8;</code>
   */
  private void clearP75Seconds() {
    
    p75Seconds_ = 0L;
  }

  public static final int MAX_SECONDS_FIELD_NUMBER = 9;
  private long maxSeconds_;
  /**
   * <code>int64 max_seconds = 9;</code>
   * @return The maxSeconds.
   */
  @java.lang.Override
  public long getMaxSeconds() {
    return maxSeconds_;
  }
  /**
   * <code>int64 max_seconds = 9;</code>
   * @param value The maxSeconds to set.
   */
  private void setMaxSeconds(long value) {
    
    maxSeconds_ = value;
  }
  /**
   * <code>int64 max_seconds = 9;</code>
   */
  private void clearMaxSeconds() {
    
    maxSeconds_ = 0L;
  }

  public static final int SAMPLE_SECONDS_FIELD_NUMBER = 10;
  private com.google.protobuf.Internal.LongList sampleSeconds_;
  /**
   * <pre>
   * The individual lead times, set only when plot is PLOT_POINTS. Bounded by
   * the same threshold, so this cannot grow with a busy week.
   * </pre>
   *
   * <code>repeated int64 sample_seconds = 10;</code>
   * @return A list containing the sampleSeconds.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getSampleSecondsList() {
    return sampleSeconds_;
  }
  /**
   * <pre>
   * The individual lead times, set only when plot is PLOT_POINTS. Bounded by
   * the same threshold, so this cannot grow with a busy week.
   * </pre>
   *
   * <code>repeated int64 sample_seconds = 10;</code>
   * @return The count of sampleSeconds.
   */
  @java.lang.Override
  public int getSampleSecondsCount() {
    return sampleSeconds_.size();
  }
  /**
   * <pre>
   * The individual lead times, set only when plot is PLOT_POINTS. Bounded by
   * the same threshold, so this cannot grow with a busy week.
   * </pre>
   *
   * <code>repeated int64 sample_seconds = 10;</code>
   * @param index The index of the element to return.
   * @return The sampleSeconds at the given index.
   */
  @java.lang.Override
  public long getSampleSeconds(int index) {
    return sampleSeconds_.getLong(index);
  }
  private int sampleSecondsMemoizedSerializedSize = -1;
  private void ensureSampleSecondsIsMutable() {
    com.google.protobuf.Internal.LongList tmp = sampleSeconds_;
    if (!tmp.isModifiable()) {
      sampleSeconds_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <pre>
   * The individual lead times, set only when plot is PLOT_POINTS. Bounded by
   * the same threshold, so this cannot grow with a busy week.
   * </pre>
   *
   * <code>repeated int64 sample_seconds = 10;</code>
   * @param index The index to set the value at.
   * @param value The sampleSeconds to set.
   */
  private void setSampleSeconds(
      int index, long value) {
    ensureSampleSecondsIsMutable();
    sampleSeconds_.setLong(index, value);
  }
  /**
   * <pre>
   * The individual lead times, set only when plot is PLOT_POINTS. Bounded by
   * the same threshold, so this cannot grow with a busy week.
   * </pre>
   *
   * <code>repeated int64 sample_seconds = 10;</code>
   * @param value The sampleSeconds to add.
   */
  private void addSampleSeconds(long value) {
    ensureSampleSecondsIsMutable();
    sampleSeconds_.addLong(value);
  }
  /**
   * <pre>
   * The individual lead times, set only when plot is PLOT_POINTS. Bounded by
   * the same threshold, so this cannot grow with a busy week.
   * </pre>
   *
   * <code>repeated int64 sample_seconds = 10;</code>
   * @param values The sampleSeconds to add.
   */
  private void addAllSampleSeconds(
      java.lang.Iterable<? extends java.lang.Long> values) {
    ensureSampleSecondsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, sampleSeconds_);
  }
  /**
   * <pre>
   * The individual lead times, set only when plot is PLOT_POINTS. Bounded by
   * the same threshold, so this cannot grow with a busy week.
   * </pre>
   *
   * <code>repeated int64 sample_seconds = 10;</code>
   */
  private void clearSampleSeconds() {
    sampleSeconds_ = emptyLongList();
  }

  public static final int BEYOND_AXIS_FIELD_NUMBER = 11;
  private boolean beyondAxis_;
  /**
   * <pre>
   * Whether this week has a lead time past the axis, so a client can mark the
   * row rather than silently clipping it. Strictly beyond, so a value landing
   * exactly on the axis is drawn rather than marked as excluded.
   * </pre>
   *
   * <code>bool beyond_axis = 11;</code>
   * @return The beyondAxis.
   */
  @java.lang.Override
  public boolean getBeyondAxis() {
    return beyondAxis_;
  }
  /**
   * <pre>
   * Whether this week has a lead time past the axis, so a client can mark the
   * row rather than silently clipping it. Strictly beyond, so a value landing
   * exactly on the axis is drawn rather than marked as excluded.
   * </pre>
   *
   * <code>bool beyond_axis = 11;</code>
   * @param value The beyondAxis to set.
   */
  private void setBeyondAxis(boolean value) {
    
    beyondAxis_ = value;
  }
  /**
   * <pre>
   * Whether this week has a lead time past the axis, so a client can mark the
   * row rather than silently clipping it. Strictly beyond, so a value landing
   * exactly on the axis is drawn rather than marked as excluded.
   * </pre>
   *
   * <code>bool beyond_axis = 11;</code>
   */
  private void clearBeyondAxis() {
    
    beyondAxis_ = false;
  }

  public static dev.ezcd.clarity.proto.Week parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.Week parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.Week parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.Week parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.Week parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.ezcd.clarity.proto.Week parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.Week parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.Week parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.Week parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.Week parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static dev.ezcd.clarity.proto.Week parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.ezcd.clarity.proto.Week parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(dev.ezcd.clarity.proto.Week prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Week is one ISO week's DORA-shaped summary.
   * The bucket is the deploy date, which is DORA's own aggregation: a commit
   * authored three weeks ago and deployed today counts towards this week. A
   * ten-commit batch is one deploy, not ten.
   * </pre>
   *
   * Protobuf type {@code clarity.v1.Week}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        dev.ezcd.clarity.proto.Week, Builder> implements
      // @@protoc_insertion_point(builder_implements:clarity.v1.Week)
      dev.ezcd.clarity.proto.WeekOrBuilder {
    // Construct using dev.ezcd.clarity.proto.Week.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * "W2026-39"
     * </pre>
     *
     * <code>string label = 1;</code>
     * @return The label.
     */
    @java.lang.Override
    public java.lang.String getLabel() {
      return instance.getLabel();
    }
    /**
     * <pre>
     * "W2026-39"
     * </pre>
     *
     * <code>string label = 1;</code>
     * @return The bytes for label.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLabelBytes() {
      return instance.getLabelBytes();
    }
    /**
     * <pre>
     * "W2026-39"
     * </pre>
     *
     * <code>string label = 1;</code>
     * @param value The label to set.
     * @return This builder for chaining.
     */
    public Builder setLabel(
        java.lang.String value) {
      copyOnWrite();
      instance.setLabel(value);
      return this;
    }
    /**
     * <pre>
     * "W2026-39"
     * </pre>
     *
     * <code>string label = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLabel() {
      copyOnWrite();
      instance.clearLabel();
      return this;
    }
    /**
     * <pre>
     * "W2026-39"
     * </pre>
     *
     * <code>string label = 1;</code>
     * @param value The bytes for label to set.
     * @return This builder for chaining.
     */
    public Builder setLabelBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setLabelBytes(value);
      return this;
    }

    /**
     * <code>int32 deploys = 2;</code>
     * @return The deploys.
     */
    @java.lang.Override
    public int getDeploys() {
      return instance.getDeploys();
    }
    /**
     * <code>int32 deploys = 2;</code>
     * @param value The deploys to set.
     * @return This builder for chaining.
     */
    public Builder setDeploys(int value) {
      copyOnWrite();
      instance.setDeploys(value);
      return this;
    }
    /**
     * <code>int32 deploys = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeploys() {
      copyOnWrite();
      instance.clearDeploys();
      return this;
    }

    /**
     * <code>.clarity.v1.Plot plot = 3;</code>
     * @return The enum numeric value on the wire for plot.
     */
    @java.lang.Override
    public int getPlotValue() {
      return instance.getPlotValue();
    }
    /**
     * <code>.clarity.v1.Plot plot = 3;</code>
     * @param value The plot to set.
     * @return This builder for chaining.
     */
    public Builder setPlotValue(int value) {
      copyOnWrite();
      instance.setPlotValue(value);
      return this;
    }
    /**
     * <code>.clarity.v1.Plot plot = 3;</code>
     * @return The plot.
     */
    @java.lang.Override
    public dev.ezcd.clarity.proto.Plot getPlot() {
      return instance.getPlot();
    }
    /**
     * <code>.clarity.v1.Plot plot = 3;</code>
     * @param value The enum numeric value on the wire for plot to set.
     * @return This builder for chaining.
     */
    public Builder setPlot(dev.ezcd.clarity.proto.Plot value) {
      copyOnWrite();
      instance.setPlot(value);
      return this;
    }
    /**
     * <code>.clarity.v1.Plot plot = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlot() {
      copyOnWrite();
      instance.clearPlot();
      return this;
    }

    /**
     * <pre>
     * How many commits contributed a lead time. Not the same as deploys: a
     * batch carries several commits, and a week can measure lead times from
     * batches whose own deploy event was never recorded.
     * </pre>
     *
     * <code>int32 n = 4;</code>
     * @return The n.
     */
    @java.lang.Override
    public int getN() {
      return instance.getN();
    }
    /**
     * <pre>
     * How many commits contributed a lead time. Not the same as deploys: a
     * batch carries several commits, and a week can measure lead times from
     * batches whose own deploy event was never recorded.
     * </pre>
     *
     * <code>int32 n = 4;</code>
     * @param value The n to set.
     * @return This builder for chaining.
     */
    public Builder setN(int value) {
      copyOnWrite();
      instance.setN(value);
      return this;
    }
    /**
     * <pre>
     * How many commits contributed a lead time. Not the same as deploys: a
     * batch carries several commits, and a week can measure lead times from
     * batches whose own deploy event was never recorded.
     * </pre>
     *
     * <code>int32 n = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearN() {
      copyOnWrite();
      instance.clearN();
      return this;
    }

    /**
     * <pre>
     * The five-number summary, in seconds. The median is the headline rather
     * than a mean: lead times are strongly right-skewed, so one commit that sat
     * over a weekend drags an average badly. The quartiles carry the spread,
     * which matters as much as the middle — a two-hour median with a three-day
     * p75 is a problem the median alone hides.
     * </pre>
     *
     * <code>int64 min_seconds = 5;</code>
     * @return The minSeconds.
     */
    @java.lang.Override
    public long getMinSeconds() {
      return instance.getMinSeconds();
    }
    /**
     * <pre>
     * The five-number summary, in seconds. The median is the headline rather
     * than a mean: lead times are strongly right-skewed, so one commit that sat
     * over a weekend drags an average badly. The quartiles carry the spread,
     * which matters as much as the middle — a two-hour median with a three-day
     * p75 is a problem the median alone hides.
     * </pre>
     *
     * <code>int64 min_seconds = 5;</code>
     * @param value The minSeconds to set.
     * @return This builder for chaining.
     */
    public Builder setMinSeconds(long value) {
      copyOnWrite();
      instance.setMinSeconds(value);
      return this;
    }
    /**
     * <pre>
     * The five-number summary, in seconds. The median is the headline rather
     * than a mean: lead times are strongly right-skewed, so one commit that sat
     * over a weekend drags an average badly. The quartiles carry the spread,
     * which matters as much as the middle — a two-hour median with a three-day
     * p75 is a problem the median alone hides.
     * </pre>
     *
     * <code>int64 min_seconds = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinSeconds() {
      copyOnWrite();
      instance.clearMinSeconds();
      return this;
    }

    /**
     * <code>int64 p25_seconds = 6;</code>
     * @return The p25Seconds.
     */
    @java.lang.Override
    public long getP25Seconds() {
      return instance.getP25Seconds();
    }
    /**
     * <code>int64 p25_seconds = 6;</code>
     * @param value The p25Seconds to set.
     * @return This builder for chaining.
     */
    public Builder setP25Seconds(long value) {
      copyOnWrite();
      instance.setP25Seconds(value);
      return this;
    }
    /**
     * <code>int64 p25_seconds = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearP25Seconds() {
      copyOnWrite();
      instance.clearP25Seconds();
      return this;
    }

    /**
     * <code>int64 p50_seconds = 7;</code>
     * @return The p50Seconds.
     */
    @java.lang.Override
    public long getP50Seconds() {
      return instance.getP50Seconds();
    }
    /**
     * <code>int64 p50_seconds = 7;</code>
     * @param value The p50Seconds to set.
     * @return This builder for chaining.
     */
    public Builder setP50Seconds(long value) {
      copyOnWrite();
      instance.setP50Seconds(value);
      return this;
    }
    /**
     * <code>int64 p50_seconds = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearP50Seconds() {
      copyOnWrite();
      instance.clearP50Seconds();
      return this;
    }

    /**
     * <code>int64 p75_seconds = 8;</code>
     * @return The p75Seconds.
     */
    @java.lang.Override
    public long getP75Seconds() {
      return instance.getP75Seconds();
    }
    /**
     * <code>int64 p75_seconds = 8;</code>
     * @param value The p75Seconds to set.
     * @return This builder for chaining.
     */
    public Builder setP75Seconds(long value) {
      copyOnWrite();
      instance.setP75Seconds(value);
      return this;
    }
    /**
     * <code>int64 p75_seconds = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearP75Seconds() {
      copyOnWrite();
      instance.clearP75Seconds();
      return this;
    }

    /**
     * <code>int64 max_seconds = 9;</code>
     * @return The maxSeconds.
     */
    @java.lang.Override
    public long getMaxSeconds() {
      return instance.getMaxSeconds();
    }
    /**
     * <code>int64 max_seconds = 9;</code>
     * @param value The maxSeconds to set.
     * @return This builder for chaining.
     */
    public Builder setMaxSeconds(long value) {
      copyOnWrite();
      instance.setMaxSeconds(value);
      return this;
    }
    /**
     * <code>int64 max_seconds = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxSeconds() {
      copyOnWrite();
      instance.clearMaxSeconds();
      return this;
    }

    /**
     * <pre>
     * The individual lead times, set only when plot is PLOT_POINTS. Bounded by
     * the same threshold, so this cannot grow with a busy week.
     * </pre>
     *
     * <code>repeated int64 sample_seconds = 10;</code>
     * @return A list containing the sampleSeconds.
     */
    @java.lang.Override
    public java.util.List<java.lang.Long>
        getSampleSecondsList() {
      return java.util.Collections.unmodifiableList(
          instance.getSampleSecondsList());
    }
    /**
     * <pre>
     * The individual lead times, set only when plot is PLOT_POINTS. Bounded by
     * the same threshold, so this cannot grow with a busy week.
     * </pre>
     *
     * <code>repeated int64 sample_seconds = 10;</code>
     * @return The count of sampleSeconds.
     */
    @java.lang.Override
    public int getSampleSecondsCount() {
      return instance.getSampleSecondsCount();
    }
    /**
     * <pre>
     * The individual lead times, set only when plot is PLOT_POINTS. Bounded by
     * the same threshold, so this cannot grow with a busy week.
     * </pre>
     *
     * <code>repeated int64 sample_seconds = 10;</code>
     * @param index The index of the element to return.
     * @return The sampleSeconds at the given index.
     */
    @java.lang.Override
    public long getSampleSeconds(int index) {
      return instance.getSampleSeconds(index);
    }
    /**
     * <pre>
     * The individual lead times, set only when plot is PLOT_POINTS. Bounded by
     * the same threshold, so this cannot grow with a busy week.
     * </pre>
     *
     * <code>repeated int64 sample_seconds = 10;</code>
     * @param value The sampleSeconds to set.
     * @return This builder for chaining.
     */
    public Builder setSampleSeconds(
        int index, long value) {
      copyOnWrite();
      instance.setSampleSeconds(index, value);
      return this;
    }
    /**
     * <pre>
     * The individual lead times, set only when plot is PLOT_POINTS. Bounded by
     * the same threshold, so this cannot grow with a busy week.
     * </pre>
     *
     * <code>repeated int64 sample_seconds = 10;</code>
     * @param value The sampleSeconds to add.
     * @return This builder for chaining.
     */
    public Builder addSampleSeconds(long value) {
      copyOnWrite();
      instance.addSampleSeconds(value);
      return this;
    }
    /**
     * <pre>
     * The individual lead times, set only when plot is PLOT_POINTS. Bounded by
     * the same threshold, so this cannot grow with a busy week.
     * </pre>
     *
     * <code>repeated int64 sample_seconds = 10;</code>
     * @param values The sampleSeconds to add.
     * @return This builder for chaining.
     */
    public Builder addAllSampleSeconds(
        java.lang.Iterable<? extends java.lang.Long> values) {
      copyOnWrite();
      instance.addAllSampleSeconds(values);
      return this;
    }
    /**
     * <pre>
     * The individual lead times, set only when plot is PLOT_POINTS. Bounded by
     * the same threshold, so this cannot grow with a busy week.
     * </pre>
     *
     * <code>repeated int64 sample_seconds = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearSampleSeconds() {
      copyOnWrite();
      instance.clearSampleSeconds();
      return this;
    }

    /**
     * <pre>
     * Whether this week has a lead time past the axis, so a client can mark the
     * row rather than silently clipping it. Strictly beyond, so a value landing
     * exactly on the axis is drawn rather than marked as excluded.
     * </pre>
     *
     * <code>bool beyond_axis = 11;</code>
     * @return The beyondAxis.
     */
    @java.lang.Override
    public boolean getBeyondAxis() {
      return instance.getBeyondAxis();
    }
    /**
     * <pre>
     * Whether this week has a lead time past the axis, so a client can mark the
     * row rather than silently clipping it. Strictly beyond, so a value landing
     * exactly on the axis is drawn rather than marked as excluded.
     * </pre>
     *
     * <code>bool beyond_axis = 11;</code>
     * @param value The beyondAxis to set.
     * @return This builder for chaining.
     */
    public Builder setBeyondAxis(boolean value) {
      copyOnWrite();
      instance.setBeyondAxis(value);
      return this;
    }
    /**
     * <pre>
     * Whether this week has a lead time past the axis, so a client can mark the
     * row rather than silently clipping it. Strictly beyond, so a value landing
     * exactly on the axis is drawn rather than marked as excluded.
     * </pre>
     *
     * <code>bool beyond_axis = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearBeyondAxis() {
      copyOnWrite();
      instance.clearBeyondAxis();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:clarity.v1.Week)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new dev.ezcd.clarity.proto.Week();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "label_",
            "deploys_",
            "plot_",
            "n_",
            "minSeconds_",
            "p25Seconds_",
            "p50Seconds_",
            "p75Seconds_",
            "maxSeconds_",
            "sampleSeconds_",
            "beyondAxis_",
          };
          java.lang.String info =
              "\u0000\u000b\u0000\u0000\u0001\u000b\u000b\u0000\u0001\u0000\u0001\u0208\u0002\u0004" +
              "\u0003\f\u0004\u0004\u0005\u0002\u0006\u0002\u0007\u0002\b\u0002\t\u0002\n%\u000b" +
              "\u0007";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<dev.ezcd.clarity.proto.Week> parser = PARSER;
        if (parser == null) {
          synchronized (dev.ezcd.clarity.proto.Week.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<dev.ezcd.clarity.proto.Week>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:clarity.v1.Week)
  private static final dev.ezcd.clarity.proto.Week DEFAULT_INSTANCE;
  static {
    Week defaultInstance = new Week();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Week.class, defaultInstance);
  }

  public static dev.ezcd.clarity.proto.Week getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Week> PARSER;

  public static com.google.protobuf.Parser<Week> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

